About page
Libre-TrainSim/Libre-TrainSim pull request #128
Opened 2021-09-04 21:27 UTC by bodamat

Create about page
To add new people just update aboutPeople.csv

2021-09-04 21:28 UTC, bodamat commented
I forgot add button for mobile :)

2021-09-04 21:34 UTC, bodamat commented
Now all done :)

2021-09-05 12:18 UTC, HaSa1002 commented
I don't think a CSV table is the best suited data format for saving contributers.
I would list contributers in a markdown or text file. Also please use the names listed on the GitHub profile/used in commits as contributer name.

2021-09-05 12:42 UTC, HaSa1002 commented on src/Translations/MainMenu.csv
> +,,,,,,
```suggestion
```

2021-09-05 13:04 UTC, HaSa1002 requested changes
Looks good, just left a few ideas to improve the code

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MainMenu.tscn
> +}
I don't think this is necessary

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	label = get_node(developers_vbox).get_child(0).duplicate()
Please put the label into a new scene and preload the scene.
```suggestion
var aboutLabel := preload("path/to/about_label.tscn")

func _ready() -> void:
```

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		node.remove_child(n)
```suggestion
		node.queue_free(n)
```
Otherwise we have orphan nodes and leaking memory

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	var maindata = {}
```suggestion
	var maindata = []
```
Use multidimensional array (see below)

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		maindata[maindata.size()] = data_set
```suggestion
		maindata.push_back(data_set)
```
If you use numeric keys which are ascending using a multidimensional array makes more sense

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
```suggestion
	for i in range(data.size()):
```
Why range(1, data.size())? Do you want to skip the first entry?

You could do
```suggestion
	for entry in data:
```
as well. `entry` would be your array.

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		var value = data[i][index]
If you use for each loop (second proposal above), your code would look like this:
```suggestion
		var value = entry[index]
```

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		var author_label : Label = label.duplicate()
```suggestion
		var author_label := aboutLabel.instance() as Label
```

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +			return
Same as show_authors
```suggestion
func show_translators(data: Array) -> void:
	for entry in data:
		var author_label := authorLabel.instance() as Label
		var value = entry[2] + " - " + entry[3]
		if str(entry[2]).strip_edges().empty():
			return
```

2021-09-05 13:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +func show_authors(data: Dictionary, index: int, parent_path_node: NodePath) -> void:
```suggestion
func show_authors(data: Array, index: int, parent_path_node: NodePath) -> void:
```

2021-09-05 13:04 UTC, HaSa1002 commented on src/project.godot
> +
```suggestion
```
This file and change should be reverted

2021-09-05 16:42 UTC, bodamat commented on src/project.godot
> +
why this change should be reverted?

2021-09-05 16:43 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MainMenu.tscn
> +}
Yes, this is not necessary, but give more kind to the project :)

2021-09-05 16:46 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
yes, I want to skip the first entry. I don't know how to do it in another way, but the first row needed to know the name of the column, but not needed when import and show information from it

2021-09-05 16:52 UTC, HaSa1002 commented on src/project.godot
> +
it's a debug setting. The reason for this setting is to set memory usage of the prints in the editor. Max Chars per Second is set to 2KiB by default (the buffer size). Set it at least to 10240 if you really want to change it, but I don't think it is needed

2021-09-05 16:56 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MainMenu.tscn
> +}
idk. I wouldn't do it

2021-09-05 17:01 UTC, bodamat commented
> I don't think a CSV table is the best suited data format for saving contributers.
> I would list contributers in a markdown or text file. Also please use the names listed on the GitHub profile/used in commits as contributer name.

I also think about this, but easily and fast parse in Godot I use csv

2021-09-05 17:02 UTC, bodamat commented on src/project.godot
> +
then we need less print in output because it really hard to debug

2021-09-05 17:03 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MainMenu.tscn
> +}
in some project, I saw this, but of course not in commercial projects :)

2021-09-05 17:04 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
🤔 I recommend splitting authors and translators into two files. We could omit the the header row then and only use get_line() for the authors and use get_csv_line() for translators.
Btw. `get_csv_line` doesn't care about any valid header row or stuff like that. Basically it is `get_line().split(delim)`

2021-09-05 17:05 UTC, HaSa1002 commented on src/project.godot
> +
You can change this setting for yourself, but I don't think it should be commited. Do you tried to set breakpoints?

2021-09-05 17:10 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
the best option is using a local database :) but this is also enough for now :)

2021-09-05 17:11 UTC, bodamat commented on src/project.godot
> +
yes, breakpoints I also use. But how I can change project settings and don't commit it? :)

2021-09-05 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
I disagree. Anyhow, Jean needs to decide that. I am not going to merge this work anyway xD

2021-09-05 17:16 UTC, bodamat commented
Thanks @HaSa1002 for reviewing my code

2021-09-05 17:18 UTC, HaSa1002 commented on src/project.godot
> +
You can commit only specific files. I mostly use VS Code hand in hand with my terminal to use git. GUI git to stage (git add) and terminal for everything else. I recommend checking out https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

2021-09-05 17:18 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
the local database has a lot of advantages and first advantage links. You don't need to create a lot of copies, just link

2021-09-05 17:21 UTC, bodamat commented on src/project.godot
> +
but I can't pull before commit all changes

2021-09-05 17:22 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
I am confused. You still need to iterate over a list of entries.

2021-09-05 17:24 UTC, HaSa1002 commented on src/project.godot
> +
git stash to get rid of all files and git stash apply to get them back. You could commit them to a seperate commit as well and do a rebase later. Speaking of rebase, when you update your branch, use git pull upstream_repo branch -r to rebase you changes on top and not merge your changes

2021-09-05 17:26 UTC, bodamat commented on src/project.godot
> +
thanks

2021-09-05 17:29 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
if we talk about the local database I know SQLLite so we don't need iterate through each line, only use SQL

2021-09-05 17:29 UTC, HaSa1002 commented
Thinking more about the format question, what about using a Resource? We can edit them in Engine and we don't need to parse them. Just create one like this:
```gdscript
class_name Authors
extends Resource

export(Array, String) authors := []
export(Array, Array, String) translators := [] # structure will be [[Name, Language]]
```
then just create the resource in the file system and assign it in your about script using
```gdscript
export var authors: Authors
```

2021-09-05 17:31 UTC, bodamat commented
I forgot about this idea, thanks. It should be much better. Do we need separate main developers and contributors?

2021-09-05 17:32 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
SQLLite stores the data in a binary format. Hence, it is not usable for a git-driven workflow. And you would still need to iterate about the results, because you need to add a new label for each entry

2021-09-05 17:46 UTC, bodamat commented
Good idea, but this method also has disadvantages. This is so hard to update now, maybe in Godot 4.0, it changes. Can't change order position in Array and can't redo operation

2021-09-05 17:53 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	for i in range(1, data.size()):
Try to use Resources from Godot. Should help

2021-09-05 19:02 UTC, HaSa1002 commented
But the order doesn't matter?
Keep in mind, that you can just edit the tres file by hand in a text editor

2021-09-05 19:03 UTC, bodamat commented
for language matter, but only first index of array :)

2021-09-05 19:09 UTC, HaSa1002 commented on src/about_authors.gd
> +export(Array, Array, String) var translators := []
```suggestion
export(Array, Array, String) var translators := [] # structure is [[Name, Language]]
```
Use only the translators array and put the language in the array behind the name like this
![grafik](https://user-images.githubusercontent.com/14185889/132138616-0e301a89-aff0-42c5-912c-1fea36084f7d.png)

2021-09-05 19:10 UTC, HaSa1002 commented
and please rename `about_authors.gd` to `authors.gd`

2021-09-05 19:14 UTC, bodamat commented on src/about_authors.gd
> +export(Array, Array, String) var translators := []
this is not what I want :) Here still matter order

2021-09-05 19:16 UTC, HaSa1002 commented
Do you want to group authors by their language?

Von: Bohdan Matviiv ***@***.***>
Gesendet: Sonntag, 5. September 2021 21:15
An: Jean28518/Libre-TrainSim ***@***.***>
Cc: Johannes Witt ***@***.***>; Mention ***@***.***>
Betreff: Re: [Jean28518/Libre-TrainSim] About page (#128)


@bodamat commented on this pull request.

________________________________

In src/about_authors.gd<https://github.com/Jean28518/Libre-TrainSim/pull/128#discussion_r702465234>:

> +export(Array, String) var languages := []

+export(Array, Array, String) var translators := []

this is not what I want :) Here still matter order

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Jean28518/Libre-TrainSim/pull/128#discussion_r702465234>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADMHLIIFY7VK2JTGR4UE32LUAO6R7ANCNFSM5DNVL3IA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-09-05 19:19 UTC, bodamat commented
yes, I want to group it. You can see this now in the last commit

2021-09-05 19:21 UTC, HaSa1002 commented
Okay then just do
![grafik](https://user-images.githubusercontent.com/14185889/132138895-2025604b-b6a5-46fd-bce8-3e9c64150a84.png)

2021-09-05 19:24 UTC, bodamat commented
Where do you get ideas? :)

2021-09-05 19:30 UTC, HaSa1002 reviewed
You could iterate like this

2021-09-05 19:30 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
```suggestion
export(Resource) var authors
```

2021-09-05 19:30 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +	show_authors(authours.contributors, contributors_vbox)
```suggestion
	show_authors(authors.developers, developers_vbox)
	show_authors(authors.contributors, contributors_vbox)
```

2021-09-05 19:30 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		show_authors(authours.translators[i], translators_vbox)
```suggestion
	for lang in authors.translators:
		var language := language_label.instance() as Label
		language.text = lang[0]
		get_node(translators_vbox).add_child(language)
		
		show_authors(lang.slice(1, -1), translators_vbox)
```

2021-09-05 19:33 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
I can't do this, because I miss a hint from the editor about what Resource I want to use. I know it will fix in Godot 4.0

2021-09-05 19:36 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
yeah but just fix the name (authors may work for hours, but the words are unrelated) and remove the assign. It is not needed. You could do
```suggestion
export(Resource) var authors = null
```

and do `assert(authors != null)` in `_ready`

2021-09-05 19:41 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
but I will don't have autocomplete. Problem not about is null or not

2021-09-05 19:43 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
But using the approach you used, you don't have autocompletion as well

2021-09-05 20:24 UTC, bodamat commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +export(Resource) var authours = authours as Authors
in code, I have, but not in the editor in inspector

2021-09-05 21:05 UTC, bodamat commented
How to use Resources created from class Author:
- For Developers and Contributors just add a new item and add text. The first is a name and the second is GitHub name after `-`. If you don't know the real name just add a GitHub account.
- For Translators add a new item what is Array. The first item in this Array is the language name and the other is people who help with translations. If you don't know the real name just add a GitHub account instead of the real name.

2021-09-05 23:57 UTC, HaSa1002 commented
Can you please squash all the commits into one?
You can either rebase or do a soft reset and create a new commit.

## Rebase

`git rebase HEAD~12 -i`, then change the eleven last `pick`s to `f`or `fixup`.
`git push -f`, once done

## Soft reset

`git reset --soft HEAD~12`
`git commit -m "Add about page"`
`git push -f`

2021-09-07 00:24 UTC, bodamat commented
I merged commits. It was pretty hard

2021-09-07 09:41 UTC, HaSa1002 requested changes
I did a quick test and it works fine. Just one thing left to ensure it works on all screens

2021-09-07 09:41 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MainMenu.tscn
> +rect_min_size = Vector2( 400, 563 )
```suggestion
margin_left = 16.0
margin_top = 16.0
margin_right = -16.0
margin_bottom = -16.0
```

2021-09-07 09:48 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/MenuAbout.gd
> +		show_authors(translators.slice(1, -1), translators_vbox)
```suggestion
export(PackedScene) var label := preload("res://Resources/Basic/UI/AboutAuthorLabel.tscn")
export(PackedScene) var language_label := preload("res://Resources/Basic/UI/AboutLanguageLabel.tscn")


func _ready() -> void:
	_clear_box(developers_vbox)
	_clear_box(contributors_vbox)
	_clear_box(translators_vbox)

	show_authors(authors.developers, developers_vbox)
	show_authors(authors.contributors, contributors_vbox)
	show_translators()


func _clear_box(box_path: NodePath) -> void:
	for n in get_node(box_path).get_children():
		n.queue_free()


func show_authors(data: Array, path_to_parent: NodePath) -> void:
	for entry in data:
		var author_label := label.instance() as Label
		author_label.text = str(entry).strip_edges()
		get_node(path_to_parent).add_child(author_label)


func show_translators() -> void:
	for translators in authors.translators:
		var language := language_label.instance() as Label
		language.text = translators[0]
		get_node(translators_vbox).add_child(language)
		show_authors(translators.slice(1, -1), translators_vbox)
```
It's the same code with the style guide applied

2021-09-07 10:15 UTC, HaSa1002 approved these changes
Nice work

2021-09-14 09:41 UTC, Jean28518 commented
Very nice work!

Thank you!

2021-09-14 09:41 UTC, merged