Add better logging
Libre-TrainSim/Libre-TrainSim pull request #145
Opened 2021-10-02 16:32 UTC by HaSa1002

* Adds `Logger.log(msg, context=null)` as print replacement
* Adds `Logger.vlog(msg, context=null)` as print verbose option
* Adds `Logger.warn(msg, context)` for warnings
* Adds `Logger.err(msg, context)` for errors

All logger functions log the time and the severity.

Used format:
`[YYYY-MM-DD][HH:MM:SS](context) message`

Depends on #133 and #144

2021-10-12 18:54 UTC, HaSa1002 commented
Note to self: Use get_stack() for stacktrace

2021-10-15 20:53 UTC, HaSa1002 commented
rebased and stack trace added. Ready for review

2021-10-16 08:41 UTC, DasCapschen requested changes
Looks great, but please check comments. 👍🏻

2021-10-16 08:41 UTC, DasCapschen commented on src/Resources/Basic/SignalTypes/Hl/Hl.gd
> +		Logger.warn(signal_logic.name + ": HL Signals cannot have Speed -1! Please set a speed limit for this Signal! Setting to 160 km/h", self)
do we still need to use `signal_logic.name`, if we're passing `self` as context? Since context is automatically printed.

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/loading_screen.gd
> +			get_tree().change_scene("res://addons/Libre_Train_Sim_Editor/Data/Modules/main_menu.tscn")
Should this change really be in this PR? Seems like something that was meant to go in #154 ...

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/ContactPoint.gd
> +		Logger.err("Contact Point "+ name + ": Specified signal point is no Signal. Aborting...", self)
again, is `name` still needed if `self` is context?

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Signal.gd
> +		# assert?
assert would crash the game, we don't want that. The signal code itself does not check if something is a main or presignal, I think, and just tries to set states. 
We would probably fix this if we introduces proper signal blocks...

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Signal.gd
> +		Logger.err(name + ": CAN'T FIND WORLD NODE!", self)
again, `name` necessary?

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/editor_configuration.gd
> +		Logger.err("Can't open directory '%s'" % editor_directory, self)
return?

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/editor_configuration.gd
> +		Logger.err("Can't open directory '%s'" % editor_directory, self)
return?

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/editor_configuration.gd
> +		Logger.err("Can't open directory '%s'" % editor_directory, self)
return?

2021-10-16 08:41 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/editor_configuration.gd
> +		Logger.err("Can't open directory '%s'" % editor_directory, self)
return?

2021-10-16 12:45 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/UI/loading_screen.gd
> +			get_tree().change_scene("res://addons/Libre_Train_Sim_Editor/Data/Modules/main_menu.tscn")
Yeah. I guess I changed that because of a merge conflict while rebasing

2021-10-16 12:46 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Signal.gd
> +		# assert?
assert does not crash the game. It causes a debug break in Debug mode, but is removed in relase builds. That is the whole point of asserts :D

2021-10-16 13:03 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Signal.gd
> +		# assert?
oh, it's removed in release builds? Well, okay. Still, we should not assert, because you would get debug breaks all the time. The signal system just doesn't care, and imo it doesn't have to.

2021-10-16 19:59 UTC, DasCapschen approved these changes
lgtm

2021-10-16 19:59 UTC, merged