Add: PZB Safety System
Libre-TrainSim/Libre-TrainSim pull request #163
Opened 2021-10-10 08:44 UTC by DasCapschen

This PR does 2 things:
- refactor how safety systems work (so far this was only sifa)
- add a second safety system, PZB

Safety systems are now separate nodes, placed in the train scene. Their script checks whatever the safety system should do, and if it detects an issue, it will request emergency braking of the train. 
Because of this change, Player.gd has no Sifa functionality anymore, and the `check_security()` function has changed. The Player will now iterate over all safety systems and check if they requested emergency braking. If any system did, the train will brake.

For a description of PZB, see #131 

This PR closes #131

2021-10-10 16:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/PZBModule.tscn
> +"
embedded GDScript. Good or bad?

2021-10-10 17:16 UTC, HaSa1002 requested changes
just minor stuff and code style

2021-10-10 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/DistanceMonitor.gd
> +export (int) var _distance = 0
```suggestion
export var _distance: int = 0
```

2021-10-10 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/DistanceMonitor.gd
> +signal reached()
signal definitions should be the first thing at the top

2021-10-10 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/DistanceMonitor.gd
> +
there should be two empty lines between functions

2021-10-10 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/SifaModule.gd
> +	player = find_parent("Player")
```suggestion
onready var player = find_parent("Player")
func _ready():
```
and maybe we should put that into SafetySystem

2021-10-10 17:16 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/TrainInfo.gd
> +#		$ScrollContainer/VBoxContainer/SiFa/dot.texture = green
```suggestion
```
YAGNI?

2021-10-11 14:43 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/PZBModule.tscn
> +"
I guess it shouldn't be embedded. That's just the script of the debug panel, good catch, I forgot to hide that by default 😅

2021-10-11 15:07 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/SifaModule.gd
> +	player = find_parent("Player")
I'm not sure, I feel like it shouldn't go into SafetySystem.

2021-10-11 15:09 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/PZBModule.tscn
> +"
FYI there are a few more embedded

2021-10-11 15:31 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/PZBModule.tscn
> +"
yeah, sifa was also embedded, but I fixed that. That should've been all though.

2021-10-11 19:17 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/SifaModule.gd
> +	player = find_parent("Player")
fair

2021-10-11 22:03 UTC, HaSa1002 approved these changes
lgtm

2021-10-15 19:58 UTC, HaSa1002 commented
1. The train does not work
![grafik](https://user-images.githubusercontent.com/14185889/137541665-a320377c-f215-49e2-a065-8bc14c1000bd.png)
2. Does the key change depending on the action?
![grafik](https://user-images.githubusercontent.com/14185889/137541884-4a672d91-e211-4430-89df-39c806c3916e.png)
3. Is there a message informing the player? Do we want that?
4. Do the magnets have textures?
5. Should Sifa be enabled in easy mode?
6. "Inavlid set index overrunnedRedSignal with value of type bool" (and it should be overrunRedSignal)

2021-10-16 08:25 UTC, DasCapschen commented
The train should've been fixed with #153 and #162 🤔 ... maybe I messed up a merge there.

Thanks for catching the keys in the text, I was meaning to code that, but then forgot... so no, the key text is hardcoded 🙈 

Informing the player? Of what?

The magnets are currently 2 or 3 materials I think, I can bake it into textures, probably better that way.

No, Sifa and PZB should *not* be enabled in easy mode, and they should also not be enabled in the mobile version. (since mobile is pretty much the easy mode)
We should make extra difficulty settings for enabling sifa / pzb separately.

2021-10-16 13:14 UTC, HaSa1002 commented
> Informing the player? Of what?

I mean sending a message when you are not pressing PgDn.

> The magnets are currently 2 or 3 materials I think, I can bake it into textures, probably better that way.

I asked, because the magnet looked plain white.

> No, Sifa and PZB should not be enabled in easy mode, and they should also not be enabled in the mobile version. (since mobile is pretty much the easy mode)

Sifa should be disabled then (It isn't right now).

2021-10-16 13:45 UTC, DasCapschen commented
> I mean sending a message when you are not pressing PgDn.

No, we shouldn't. Real PZB doesn't do it. I would, by default, disable PZB (we really need difficulty settings) and let the player decide if they are ready for it. 


> I asked, because the magnet looked plain white.

Then you've been trying a rather old version, I fixed that a while ago 😅 
Or did I forget to push? :thinking:

> Sifa should be disabled then (It isn't right now).

will do :+1:

2021-10-16 20:10 UTC, HaSa1002 approved these changes
lgtm

2021-10-16 20:30 UTC, merged

2021-10-16 20:30 UTC, HaSa1002 commented
thanks :)