add drag and drop for rails in editor :)
Libre-TrainSim/Libre-TrainSim pull request #164
Opened 2021-10-10 11:45 UTC by DasCapschen

Fixed #151 😄 

don't merge just yet, there might be some bugs.
we might want to add a minimum radius.

2021-10-10 17:27 UTC, HaSa1002 requested changes

2021-10-10 17:27 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	if event is InputEventMouseButton and event.button_index == BUTTON_LEFT and event.pressed == true and not $EditorHUD.mouse_over_ui:
```suggestion
	if event is InputEventMouseButton and event.button_index == BUTTON_LEFT and event.pressed and not $EditorHUD.mouse_over_ui:
```

2021-10-10 17:27 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	if event is InputEventMouseButton and event.pressed == false and drag_mode:
```suggestion
	if event is InputEventMouseButton and !event.pressed and drag_mode:
```

2021-10-10 17:27 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +		selected_object.calculate_from_start_end(mouse_pos_3d)
Could be done with PhysicsObject with InputEvent tracking.
![grafik](https://user-images.githubusercontent.com/14185889/136706662-00eb3d24-b975-43fe-bb5f-90015d9c5b93.png)
using those callbacks
![grafik](https://user-images.githubusercontent.com/14185889/136706680-2f9a6379-21cb-4063-8e19-96b554daf8f6.png)

2021-10-10 17:27 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
> +	# b = z - m2 * x
```suggestion
```
YAGNI

2021-10-10 18:03 UTC, HaSa1002 commented
Cursor is offset.
Repro:
1. Create Rail with curvature
2. Add new rail using "after rail"
3. Drag the endpoint of the second rail

2021-10-10 18:04 UTC, HaSa1002 commented
if you drag the endpoint onto the movement gizmo, you trigger the movement

2021-10-10 18:12 UTC, HaSa1002 commented
**Issue is not related to PR**
power line is not updated correctly
![grafik](https://user-images.githubusercontent.com/14185889/136708098-911a5d2d-e611-4b27-b0b4-cd9032f665e3.png)

2021-10-10 18:21 UTC, HaSa1002 commented
I would favor, if you could change the addition behaviour to:
1. Tell game, you want to add a rail
2. Move your mouse to start position
3. Press LMB and hold
	1. If near other rail, snap to that rail and get curvature and radius from that rails
	2. Else set Rotation to 0
4. Drag rail
5. Release LMB to end action

2021-10-11 15:12 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +		selected_object.calculate_from_start_end(mouse_pos_3d)
Not sure if we should use a node here. Because the y position should be the height of the current rail, not of a fixed collision plane node.
Though in the future, we would want collision with a heightmap shape there, so that might be useful afterall... 🤔

2021-10-11 15:12 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
> +	# b = z - m2 * x
was for documentation purposes, not as commented code

2021-10-11 15:51 UTC, DasCapschen commented
ty for review
- style changes applied
- cursor offset fixed
- ui updates while dragging
- gizmo hidden while dragging (gizmo itself still broken)
- powerline is a Rail.gd issue
- gonna code snapping now :)

2021-10-11 16:05 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +		selected_object.calculate_from_start_end(mouse_pos_3d)
I would create a sphere shape as collider and use the input_event callback for the xz movement. Raycast can then be used to determine the height (or just statically set to value for now)

2021-10-11 18:37 UTC, HaSa1002 requested changes

2021-10-11 18:37 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	yield(get_tree(), "idle_frame")
```suggestion
	# wait for physics update, else we can never un-snap
	yield(get_tree(), "physics_frame")
```
Physics frame is `physics_frame`

2021-10-11 18:46 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	yield(get_tree(), "idle_frame")
good point 🙈

2021-10-11 18:52 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	yield(get_tree(), "idle_frame")
actually, no, this needs to be idle_frame, it doesn't work otherwise... I'm not quite sure why 🤔 
basically the problem is that the position of the area needs to update before we check the snapping, else it will stay snapped once it has snapped.

2021-10-11 18:55 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +	yield(get_tree(), "idle_frame")
okay. It works. Maybe remove the comment though

2021-10-12 11:54 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +		selected_object.calculate_from_start_end(mouse_pos_3d)
But also, that would require connecting to the signal and installing a callback, right?
The way it is now, the code runs independent of that, without connecting and disconnecting signals.
I'm just not sure if it's really necessary to use those signals, they don't seem to provide any benefit over the code we have now.

2021-10-12 18:07 UTC, HaSa1002 commented
I doesn't do anything after I press OK and instead get that error:
```
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
```

2021-10-12 18:08 UTC, HaSa1002 commented
and when it starts to show the text box, it says:
```
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
[]
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
[]
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
[]
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
[]
ERROR: Signal 'confirmed' is already connected to given method '_snap_complex_connector' in that object.
   At: core/object.cpp:1512
```

2021-10-12 21:59 UTC, DasCapschen commented
Looks like you're triggering the complex connector, for arbitrary connections. That's not implemented yet, I guess I should have disabled the popup for it, but as it stands, this PR is WIP.

Signal errors should be fixed with a simple if check. (though I kinda wish godot just wouldn't throw an error on double connect...)
I have no idea where the `[]` print comes from...

2021-10-12 22:06 UTC, HaSa1002 commented
Yeah I figured the signals will be connected multiple times, because the snapping is in place, but the the popup connection logic is triggered every snapping mouse movement frame.

That is totally fine. I was just super confused, but I found the two working use cases, so no worried there (although the complex one may be used even in the 90° case).

2021-10-16 20:55 UTC, merged

2021-10-16 20:55 UTC, HaSa1002 commented
🥳