Implement station signal control
Libre-TrainSim/Libre-TrainSim pull request #202
Opened 2021-10-22 12:35 UTC by Jean28518

Also did some bugfixes. 
Resolves #116 

Editor function of station signal control not implemented, because will be deprecated with upcoming scenario editor

2021-10-23 07:45 UTC, DasCapschen requested changes
looks good :)

2021-10-23 07:45 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/SpeedLimitSignal.gd
> +	if Engine.is_editor_hint() or Root.Editor:
`Engine.is_editor_hint()` is not necessary, since this is not a tool script.

2021-10-23 07:45 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/SpeedLimitWarnSignal.gd
> +	if Engine.is_editor_hint() or Root.Editor:
`Engine.is_editor_hint()` not necessary because not a tool script :)

2021-10-23 07:45 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Station.gd
> +	if Engine.is_editor_hint() or Root.Editor:
`Engine.is_editor_hint()` not necessary because not a tool script :)

2021-10-23 07:45 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/World.gd
> +	return $Rails.get_node_or_null(rail_name)
is the `rail_name == ""` check necessary? I would expect `get_node_or_null` to handle this case and return null, so no need to do it explicitly.

2021-10-23 07:45 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/World.gd
> +	return $Signals.get_node_or_null(signal_name)
same as get_rail()

2021-10-23 17:20 UTC, HaSa1002 requested changes
Some minor and style stuff

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
>  #		if signal_ins.type == "Signal":
```suggestion
```
Remove for loop

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> +		pass
```suggestion
```
Remove for loop

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	print(current_time)
```suggestion
	Logger.vlog(signal_free_time)
	Logger.vlog(current_time)
```
or remove print

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Editor.gd
> -
one empty line at the end of the file :)

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> -
one empty line at the end of file

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Singletons/Math.gd
> +func time_to_seconds(time : Array):
```suggestion
func time_to_seconds(time: Array):
```

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Singletons/Math.gd
> +func seconds_to_time(seconds : int):
```suggestion
func seconds_to_time(seconds: int):
```

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Station.gd
> +export (String) var assigned_signal = ""
```suggestion
export var assigned_signal := ""
```

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/World.gd
> +	return $Rails.get_node_or_null(rail_name)
yes. `get_node_or_null` is enough

2021-10-23 17:20 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Docks/Configuration/time_field.gd
> -
one empty line at eof

2021-11-28 21:37 UTC, Jean28518 commented
For me this one can be merged. I cant apply your requested changes.

2021-11-30 11:25 UTC, DasCapschen approved these changes

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		return
Is this a bug? When would `next_station_index` be -1?
If this should never happen, it would be better to use `assert`.
If it is supposed to happen like this, then it's fine.

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +	Logger.vlog(_signal_was_freed_for_station_index)
Can you make more expressive logs, with more context?
For example 
```gdscript
Logger.vlog("Next station is %d. Signal freed status is %s" % [next_station_index, _signal_was_freed_for_station_index])
```
This would be easier to find in the logs than just a single number.

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +	Logger.vlog(current_time)
same here, more expressive logs would be nice.

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		return
This signal probably should not be null. 
Either assert, or at least add a `Logger.warn`.

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/SelectCollider.gd
> +		$CollisionShape.shape = mesh.create_convex_shape()
I don't like this. This is going to break again.
What if parent is not a MeshInstance? `get_parent().mesh` will break.
Also, it forces a very specific structure. What if my signal has a node `MeshInstance` instead of `Mesh`? Or the Mesh is not a direct child? It won't generate anything.
I would be in favor of using the `aabb_to_collider`, like you already did for Rail.

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/ContactPoint.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
1) we do not use `Engine.is_editor_hint()`, you want `Root.Editor`
2) Why not just use `aabb_to_collider` like in Rail?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Modules/SelectCollider.tscn
> +[node name="CollisionShape" type="CollisionShape" parent="."]
Do we really need this? Just use aabb_to_collider?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Signal.gd
> +				$SelectCollider.queue_free()
This is indented one too many times.
```suggestion
		if get_node_or_null("SelectCollider") != null:
			$SelectCollider.queue_free()
```

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/SpeedLimitSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
again, aabb_to_collider ?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/SpeedLimitWarnSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
same, aabb_to_collider?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Station.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
aabb_to_collider?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Station.gd
> +	if not Root.Editor:
```suggestion
	else:
```

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/Station.gd
> +		$Mesh.queue_free()
What if `$Mesh` does not exist?

2021-11-30 11:25 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
Could this be done with aabb_to_collider?
If not, this is the only use case where SelectCollider is okay, imo.

2021-11-30 11:25 UTC, DasCapschen commented on src/Editor/Modules/RailLogic.gd
> +	visible = is_instance_valid(current_rail_logic) and get_parent().current_tab == 2
why is this in _input ?

2021-11-30 11:25 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +	mesh_instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
would aabb_to_collider work?
If not, this is okay.

2021-11-30 11:26 UTC, DasCapschen requested changes
sorry, I meant to request changes, not approve... 😅 
See comments above.

2021-11-30 11:32 UTC, HaSa1002 commented on src/Editor/Modules/RailLogic.gd
> +	visible = is_instance_valid(current_rail_logic) and get_parent().current_tab == 2
I fixed that in a previous PR.

2021-12-15 16:12 UTC, Jean28518 commented
Functionality also in #278

2021-12-15 16:12 UTC, closed without merging