Add Highlight postprocessing to Editor selection (remove bouncing animation)
Libre-TrainSim/Libre-TrainSim pull request #208
Opened 2021-10-31 09:54 UTC by DasCapschen

This removes the "bouncing" animation from the selected object in Editor, and replaces it with Postprocessing Effects to outline and highlight the object.

This is what it would currently look like:
![image](https://user-images.githubusercontent.com/3923406/139576736-3afc757a-d5fb-4091-9948-22ee2f4ac404.png)

Of course, we can decide to only use outlines, or only use highlighting (they are 2 separate nodes that added to the Editor scene tree), and the colors are also configurable.

What is currently not configurable, though I'm sure I can work out how to do that, is the thickness of the outline, which is currently only about 2 pixels...

2021-10-31 11:44 UTC, HaSa1002 commented
I'd be in favor of only using the outline shader because the tint makes it hard to match colors.

2021-10-31 11:54 UTC, HaSa1002 requested changes

2021-10-31 11:54 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
`step`?

2021-10-31 11:54 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/ShaderPP.gd
> +	shader_camera = find_node("Camera")
```suggestion
onready var external_camera := get_viewport().get_camera()
onready var shader_camera := find_node("Camera") as Camera
```

2021-10-31 11:54 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/ShaderPP.gd
> +func _process(delta: float) -> void:
```suggestion
func _process(_delta: float) -> void:
```
Surpresses unused argument warning

2021-10-31 11:54 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/highlight_shader.gdshader
> +	}
`step`?

2021-10-31 12:52 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
what?

2021-10-31 22:03 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
```suggestion
	return step(texture(tex, uv).xyz, vec3(0)).x;
```

2021-10-31 22:03 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
because step is GPU accelerated it is faster (in theory)

2021-11-02 18:04 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
step is not going to work. It is defined as `b < a ? 0 : 1` and the minimum value rgb can have *is* 0, so `0 < 0` is always false and this will always return 1...

2021-11-02 18:54 UTC, DasCapschen commented
I've changed it to only use outlines. 
And I fixed the outline shader... it was discarding half of the outline 🙈 
So they are bigger now too, should be well visible.

2021-11-02 19:21 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/Postprocess/LaplaceEdgeDetect.gdshader
> +	}
yes. you're right

2021-11-05 19:49 UTC, DasCapschen commented
rebased

2021-11-05 21:59 UTC, HaSa1002 approved these changes
I mean it is ugly, but who cares xD
![grafik](https://user-images.githubusercontent.com/14185889/140583227-5578f105-1609-491b-8c35-565a971e4b94.png)

2021-11-05 21:59 UTC, merged

2021-11-05 21:59 UTC, HaSa1002 commented
thank you