Convert chunk system to use TSCN
Libre-TrainSim/Libre-TrainSim pull request #236
Opened 2021-11-07 15:15 UTC by DasCapschen

Instead of writing *.save files ourselves, we can simply save the data in tscn files.

Changes:
- instead of writing 1 .save file, write 1 tscn file per chunk
- chunks save THE SAME INFORMATION AS BEFORE, not extra information is added! (especially for multimeshes, those are still generated at runtime, and NOT saved in the file!)
- but: if we move files, change paths, change script variables, etc, Godot will rename everything FOR US, we don't have to manually edit their .save files anymore.
- Editor will automatically convert .save to .tscn's

Comparision for Tutorials:
- save ~ 8kB
- tscn's ~ 12kB

Comparision for Hainfurt:
- save ~833kB
- tscn's ~1000kB

2021-11-07 15:30 UTC, HaSa1002 requested changes
minor things

2021-11-07 15:30 UTC, HaSa1002 commented on src/Data/Scripts/TrackObjects.gd
> +	#d.materialPaths = materialPaths.duplicate()
```suggestion
```

2021-11-07 15:30 UTC, HaSa1002 commented on src/Data/Scripts/TrackObjects.gd
> +	#materialPaths = d.materialPaths
```suggestion
```

2021-11-07 15:56 UTC, HaSa1002 approved these changes
I am in favor of merging this.
The slightly increased file is fine, because we gain much cleaner code from the change. I believe, we will minify the size even more in the future by changing how we build objects.

2021-11-17 12:33 UTC, DasCapschen commented
Something still has an old path somewhere and writes res://chunks ...
Also I didn't fix the chunk system in this PR, just re-wrote it to support the new files.
This means all the bugs that are currently in the chunk system are still in this one too.

I now also converted scenarios.cfg to tres files.
- you have `world.tscn` and next to it `world_config.tres`, this is what used to be "world_config" in scenarios.cfg
  - it has an array of all scenarios, release date, author, ...
- a new folder `scenarios`
  - every scenario gets its own `scenario name.tres` file. It saves scenario name, description, time, trains, signals, etc.

2021-11-17 15:41 UTC, HaSa1002 commented
Issues noticed in Hainfurt:

- [ ] Non existing chunks are tried to be loaded causing error spam (Do dir.file_exists):
	```
	Loading resource: user://editor/hainfurt/Worlds/Hainfurt/chunks/chunk_8_1.tscn
	ERROR: Cannot open file 'user://editor/hainfurt/Worlds/Hainfurt/chunks/chunk_8_1.tscn'.
   	At: scene/resources/resource_format_text.cpp:1232
	ERROR: Failed loading resource: user://editor/hainfurt/Worlds/Hainfurt/chunks/chunk_8_1.tscn. Make sure resources have been 		imported by opening the project in the editor at least once.
   	At: core/io/resource_loader.cpp:282
	```
- [ ] Notes for authors was lost
- [ ] Scenarios with `:` weren't saved (Convert those to `_` maybe and do an `assert(file_name.is_valid_filename)`?)
- [ ] `Hainfurt.tscn` may include a bunch of unneeded adds (though this may be correct and not caused by this PR. Please check

Positive effects:
 * World loading and chunk spawning is faster.
 * We can, in the future, easily load chunks on world load
 * We don't need to maintain serialisation code

2021-11-17 17:42 UTC, DasCapschen commented
- You are right about the chunks, I'll add a check for the file.
- ah, notes are in the .save file... well that's inconvenient... 
- is there a function to sanitize a string to a valid path? I already replace / and \, guess I'll add :, what other symbols do we need to strip?
- What do you mean with unneeded adds?

2021-11-17 17:45 UTC, DasCapschen commented
Oh I see now. Looks like it added all the script variables to the tscn file, even if they are the default value. Maybe this is a Godot 3.4 thing? :thinking:

2021-11-17 17:48 UTC, HaSa1002 commented
>     * is there a function to sanitize a string to a valid path? I already replace / and , guess I'll add :, what other symbols do we need to strip?

Nope. Maybe this can help: https://docs.godotengine.org/en/stable/classes/class_string.html?highlight=String#class-string-method-is-valid-filename

>     * What do you mean with unneeded adds?

See https://github.com/Libre-TrainSim/hainfurt/commit/b6a54d0743fed0959bfbbeee62291e926be6ef4f#diff-54455ae5b354136ade47699cbb43ac891341d4ba8beb4ffc2a539b2b06da3ee0

2021-11-17 17:51 UTC, HaSa1002 commented
> Oh I see now. Looks like it added all the script variables to the tscn file, even if they are the default value. Maybe this is a Godot 3.4 thing? 🤔

I did my tests in 3.3.4

2021-11-17 18:04 UTC, DasCapschen commented
notes, file_exists and invalid filename should now be fixed.

don't know why godot adds a bunch of stuff to the tscn

2021-11-24 12:09 UTC, Jean28518 commented
Concept is okay for me!

2021-11-24 18:40 UTC, DasCapschen commented
Should be ready now. Please test both ingame and editor! Also try converting an old map and exporting.

World Origin Shift is kind of slow, but that's because *all* Rails and *all* TrackObjects update their MultiMesh...
For some reason, simply changing the position of those does not work...
I will investigate this in the future, it's good enough for now. v0.10 can improve on it.

Chunks are now added into the tree as a single node, like so:
This is potentially faster than adding many nodes individually. It also makes managing chunks a lot easier.
```
World
|--- Chunks
      |--- chunk_0_0
      |      \--- TrackObjects
      |--- chunk_1_0
             \--- TrackObjects
```

2021-11-25 22:29 UTC, HaSa1002 requested changes
Mostly style.
Though I still have to do some tests

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +}
`OS.get_system_time_secs`?
Thus use int as seconds. We could modulo just fine

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(float) var duration: int = 0  # Minutes?
```suggestion
export var duration: int = 0  # seconds
```
Goes hand in hand with comments two above

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(Dictionary) var time := {
```suggestion
export var time := {
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(String) var description: String = ""
```suggestion
export var title := ""
export var description : = ""
```
Export recognizes type. Use implicit types where types are evident.

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(float) var train_length: float = 0.0  # why???
¯\\_(ツ)_/¯

```suggestion
export var train_length: float = 0.0  # why???
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(Dictionary) var signals := {}
```suggestion
export var trains := {}

# Dict[String, Dict[String, Any]]
# see Signal.gd get_scenario_data()
export var signals := {}
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/world_config.gd
> +}
see comment in track_scenario.
```suggestion
export release_date: int = 1637869391
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/world_config.gd
> +export(String) var track_description := "My world, my track, my train, my scenario; from the 1st to the 16th stop."
lol
```suggestion
export var author := "Sido"
export var track_description := "My world, my track, my train, my scenario; from the 1st to the 16th stop."
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/Resources/world_config.gd
> +export(String) var notes := ""
```suggestion
export var notes := ""
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/TrackObjects.gd
> +			multimesh.mesh.surface_set_material(i, materials[i])
Use the material override of the node.
https://docs.godotengine.org/en/stable/classes/class_geometryinstance.html#class-geometryinstance-property-material-override

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	for train in current_scenario.trains.keys():
```suggestion
	for train in current_scenario.trains:
```
No need for keys. Train will be a key nontheless

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	jEssentials.call_delayed(1, $Players/Player, "show_textbox_message", [TranslationServer.translate(current_scenario.description)])
```suggestion
	jEssentials.call_delayed(1, $Players/Player, "show_textbox_message", [tr(current_scenario.description)])
```
FYI, I don't like this way of calling functions

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	var train = current_scenario.trains[trainName]
```suggestion
	var train: Dictionary = current_scenario.trains[trainName]
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +		new_player.currentSpeedLimit = train.get("InitialSpeedLimit", -1)
What is the default speed limit?
Do we really need the check?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +export (Vector3) var chunk_position: Vector3
```suggestion
export var is_empty := true
export var generate_grass := true  # set this to false when we have terrain

export var chunk_position: Vector3
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation.y = -0.5
isn't the grass a child of the the chunk?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +	translation = Vector3(0, 0, 0)
why don't we set the translation that gets set below here?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +	#translation += delta
```suggestion
func _on_world_origin_shifted(delta):
	if generate_grass:
		$DefaultGrass.translation += delta
	update()

	# FIXME: this does not actually work...
	#        it would be so nice, if we could just shift the entire chunk node
	#        instead of all the track objects,
	#        but I think that will require a TrackObject refactor
	#        ask DasCapschen about it for 0.10
	#translation += delta
```

Could be made workable with a change to instance transform? Not a blocker though

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	return "chunk_%s_%s" % [int(chunk.x), int(chunk.z)]
```suggestion
	return "chunk_%d_%d" % [chunk.x, chunk.z]
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		return
Bug IMO

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +			chunk.free()
```suggestion
			chunk.queue_free()
```
Why not queue_free? Aren't they still in tree?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	var dir = Directory.new()
```suggestion
	var dir = Directory.new()
	if dir.open("res://") != OK:
		Logger.err("Cannot open resource directory.", self)
		return
```
Not opening directories is undefined behaviour.

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +			chunk_file = chunk_file.plus_file(chunk_to_string(chunk_pos)) + ".tscn"
this is not thread safe
```suggestion
			var chunk_file := ""
			if Root.Editor:
				chunk_file = find_parent("Editor").current_track_path.get_base_dir().plus_file("chunks")
			else:
				chunk_file = Root.currentTrack.get_base_dir().plus_file("chunks")
			chunk_file = chunk_file.plus_file(chunk_to_string(chunk_pos)) + ".tscn"
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +			var chunk
```suggestion
			var chunk: Chunk
```
If Chunk has had a type hint.

2021-11-25 22:29 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +	$Play/Info/Info/Duration.text = "%s: %s min" % [tr("MENU_DURATION"), scenario.duration]
```suggestion
	$Play/Info/Info/Duration.text = "%s: %d min" % [tr("MENU_DURATION"), scenario.duration]
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	var dir = Directory.new()
`dir.open`

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s cannot be renamed to %s!" % [current_scenario, sName], self)
```suggestion
		Logger.err("Scenario '%s' cannot be renamed to '%s'!" % [current_scenario, sName], self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	var dir := Directory.new()
`dir.open`

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	Logger.log("Scenario %s successfully renamed to %s." % [current_scenario, sName])
```suggestion
	Logger.log("Scenario '%s' successfully renamed to '%s'." % [current_scenario, sName])
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "" or sName == "" or check_duplicate_scenario(sName) or sName == current_scenario:
```suggestion
	if current_scenario.empty() or sName.empty() or check_duplicate_scenario(sName) or sName == current_scenario:
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
>  	var sName: String = $Scenarios/VBoxContainer/HBoxContainer/LineEdit.text
```suggestion
	var sName: String = $Scenarios/VBoxContainer/HBoxContainer/LineEdit.text.strip_edges()
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "":
```suggestion
	if current_scenario.empty():
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	var dir = Directory.new()
`dir.open`

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +func update_ui_from_scenario_config() -> void: # fills the settings field with saved values
```suggestion
func update_ui_to_scenario_config() -> void: # fills the settings field with saved values
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s is not in scenario list!" % current_scenario, self)
```suggestion
		Logger.err("Scenario '%s' is not in scenario list!" % current_scenario, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "":
```suggestion
	if current_scenario.empty():
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	for scenario in scenarios.keys():
```suggestion
	for scenario in scenarios:
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s is not in scenario list!" % current_scenario, self)
```suggestion
		Logger.err("Scenario '%s' is not in scenario list!" % current_scenario, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
>  	for train in trains:
```suggestion
	for train in scenarios[current_scenario].trains:
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario != "":
```suggestion
	if !current_scenario.empty():
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_train != "":
```suggestion
	if !current_train.empty():
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	update_ui_from_scenario_config()
```suggestion
	update_ui_to_scenario_config()
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s is not in scenario list!" % current_scenario, self)
```suggestion
		Logger.err("Scenario '%s' is not in scenario list!" % current_scenario, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "":
```suggestion
	if current_scenario.empty():
```
Honestly a lot of those checks are probably bug hiding

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Cannot rename train %s to %s, already exists." % [oldTrain, trainName], self)
```suggestion
		Logger.err("Cannot rename train '%s' to '%s', already exists." % [oldTrain, trainName], self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	update_train_list()       # update ui
```suggestion
	load_current_train() # load old train
	current_train = trainName # rename
	save_current_train() # save new train
	delete_train(oldTrain) # delete old train
	update_train_list() # update ui
```
Please no.

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	update_train_list()       # update ui
or kill the comments completely. The methods are kinda explicit already

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s is not in scenario list!" % current_scenario, self)
```suggestion
		Logger.err("Scenario '%s' is not in scenario list!" % current_scenario, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.warn("Cannot delete Train " + train + ", does not exist...", self)
```suggestion
		Logger.warn("Cannot delete non existent train `%s`." % train, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +		Logger.err("Scenario %s is not in scenario list!" % current_scenario, self)
```suggestion
		Logger.err("Scenario '%s' is not in scenario list!" % current_scenario, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	for scenario in scenarios.keys():
```suggestion
	for scenario in scenarios:
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if scenarios.size() < 2:
warn?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "":
```suggestion
	if current_scenario.empty():
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/Configuration/Configuration.gd
>  		jEssentials.show_message("Nothing done. Can't copy and overwrite from current scenario to current scenario.")
Don't we have a show_message here. And we miss a log, probably

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Docks/RailAttachments/RailAttachments.gd
> +			mesh_instance.set_surface_material(i, material_array[i])
Do using material overwrite in the node?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	var dir = Directory.new()
`dir.open`

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +					i += 1
```suggestion
			if to_instance.multimesh.mesh != null:
				var i = 0
				for material_path in track_obj.data.materialPaths:
					to_instance.materials.append(load(material_path))
					to_instance.multimesh.mesh.surface_set_material(i, load(material_path))
					i += 1
			else:
				Logger.err("Could not load object '%s'" % track_obj.data.objectPath, self)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		or new_chunk.get_node("TrackObjects").get_child_count() > 0:
```suggestion
				or new_chunk.get_node("Buildings").get_child_count() > 0 \
				or new_chunk.get_node("TrackObjects").get_child_count() > 0:
```
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#formatting

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +			var path = current_track_path.get_base_dir().plus_file("chunks").plus_file(ChunkManager.chunk_to_string(old_chunk.position)) + ".tscn"
```suggestion
			var packed_chunk := PackedScene.new()
			packed_chunk.pack(new_chunk)
			var path: String = current_track_path.get_base_dir().plus_file("chunks").plus_file(ChunkManager.chunk_to_string(old_chunk.position)) + ".tscn"
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	var dir = Directory.new()
`dir.open`

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	var old_release_date = old_world_config.get("ReleaseDate", [1,1,2021])
```suggestion
	var world_config_path: String = current_track_path + "_config.tres"
	var world_config := WorldConfig.new()

	var old_world_config: Dictionary = jsavemodule.get_value("world_config")
	var old_release_date: Array = old_world_config.get("ReleaseDate", [1,1,2021])
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		var new_scenario = TrackScenario.new()
```suggestion
	var scenarios: Dictionary = jsavemodule.get_value("scenario_data")
	for key in scenarios:
		if key.empty()":  # there is always an empty scenario, pls ignore it...
			continue
		var old_scenario: Dictionary = scenarios[key]
		var new_scenario := TrackScenario.new()
```
What's the type of `old_scenario`?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		var scenario_path = scenario_dir.plus_file("%s.tres" % key)
```suggestion
		var scenario_path: String = scenario_dir.plus_file("%s.tres" % key)
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	var save_file = current_track_path + ".save"
```suggestion
	var save_file: String = current_track_path + ".save"
```

2021-11-25 22:29 UTC, HaSa1002 commented on src/Editor/Scripts/editor_configuration.gd
> +	var packed_chunk = PackedScene.new()
```suggestion
	var chunk_0_0 := preload("res://Data/Modules/chunk_prefab.tscn").instance() as Spatial
	chunk_0_0.rails = ["Rail"]
	var packed_chunk := PackedScene.new()
```
as `what`?

2021-11-25 22:29 UTC, HaSa1002 commented on src/Worlds/German-Safety-Tutorials/SafetyTutorialScript.gd
> +		return
What about ready or yield in ready?
We could do `set_process(!Root.Editor)` there as well.

2021-11-25 22:29 UTC, HaSa1002 commented on src/Worlds/Signal-Tutorial/Scripting.gd
> +		return
_ready?

2021-11-25 22:54 UTC, HaSa1002 commented
Game and editor as well as conversion still work. Well done
![grafik](https://user-images.githubusercontent.com/14185889/143506033-b328d9b8-7ea5-47ae-a6ac-2f72972bc02c.png)

2021-11-25 22:56 UTC, HaSa1002 commented
Oh wait. The generated multi meshes still get saved

2021-11-26 15:09 UTC, DasCapschen commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(float) var duration: int = 0  # Minutes?
IIRC, Duration is entered by the user and is AFAIK only so players know roughly what to expect when starting a scenario.
So it should probably be minutes

2021-11-26 15:09 UTC, DasCapschen commented on src/Data/Scripts/Resources/track_scenario.gd
> +}
well, the world script does everything using an [Hour, Minute, Second] Array for tracking time... 😅

2021-11-26 15:10 UTC, DasCapschen commented on src/Data/Scripts/TrackObjects.gd
> +			multimesh.mesh.surface_set_material(i, materials[i])
Material Override does not have seperate surfaces though. It overrides everything with 1 Material.
We need multiple Materials per Object though.

2021-11-26 15:13 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation.y = -0.5
Yes, Grass is a child of the chunk.
But objects inside the chunk (with the exception of grass) are not stored relative to the chunk, but rather in global coordinates.
This means the chunk itself needs to be at (0,0,0).
But Grass *is* relative to the chunk, so we need to move it.

2021-11-26 15:15 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +	#translation += delta
I tried moving all TrackObject instances, but that does not work. 
It only works when I trigger update() on all Track Objects. I have no idea why, moving transform *should* work.

Also, we should not call update here. Rails already call update on all their assigned TrackObjects.
(and Rails are updated by the signal)

2021-11-26 15:18 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		return
Yes, but it happens some times, usually when there is a huge lag due to world origin transform.

2021-11-26 15:18 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		return
If I assert this, we get memory leaks at runtime.

2021-11-26 15:18 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +			chunk.free()
free removes them from tree?

2021-11-26 15:20 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +	var dir = Directory.new()
We only use "static" function like checking if a file exists though... tbh it is beyond me why those are not static. 
There is no need to open a directory for that...

2021-11-26 15:21 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +			var chunk
chunk does not have a class_name

2021-11-26 15:22 UTC, DasCapschen commented on src/Editor/Docks/Configuration/Configuration.gd
> +func update_ui_from_scenario_config() -> void: # fills the settings field with saved values
why?

2021-11-26 15:23 UTC, DasCapschen commented on src/Editor/Docks/Configuration/Configuration.gd
> +	if current_scenario == "":
Honestly, checks are just making sure nothing crashes *if* a bug ever occured.

2021-11-26 15:25 UTC, DasCapschen commented on src/Editor/Docks/Configuration/Configuration.gd
> +	update_train_list()       # update ui
1) why are you against order? it's good to have them listed below each other... also, 2 spaces before a comment
2) yeah, I guess we can just remove them outright

2021-11-26 15:27 UTC, DasCapschen commented on src/Editor/Docks/Configuration/Configuration.gd
>  		jEssentials.show_message("Nothing done. Can't copy and overwrite from current scenario to current scenario.")
Maybe? idk, I didn't write this code

2021-11-26 15:28 UTC, DasCapschen commented on src/Editor/Docks/RailAttachments/RailAttachments.gd
> +			mesh_instance.set_surface_material(i, material_array[i])
again, material override does not support multiple materials per object

2021-11-26 15:30 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +		or new_chunk.get_node("TrackObjects").get_child_count() > 0:
next time, please link directly to the correct statement, I don't want to search through a huge webpage
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#format-multiline-statements-for-readability

2021-11-26 15:31 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +		var new_scenario = TrackScenario.new()
string

2021-11-26 15:33 UTC, DasCapschen commented
> The generated multi meshes still get saved

Well that's bad... that shouldn't have happened... will look into it

2021-11-26 15:35 UTC, DasCapschen commented on src/Worlds/Signal-Tutorial/Scripting.gd
> +		return
tbh, all scenario scripts are absolute jank

2021-11-28 11:25 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +	var dir = Directory.new()
> When creating a new Directory, its default opened directory will be res://.

https://docs.godotengine.org/en/stable/classes/class_directory.html

2021-11-28 11:57 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +		or new_chunk.get_node("TrackObjects").get_child_count() > 0:
honestly, I find it a lot *less* readable with 2 indentations...
without indentation, you get `if or or` underneath each other, with 2 indents... it's just hell...

2021-11-28 12:11 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +}
ok 0.10 then

2021-11-28 12:11 UTC, HaSa1002 commented on src/Data/Scripts/Resources/track_scenario.gd
> +export(float) var duration: int = 0  # Minutes?
ok

2021-11-28 12:18 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation.y = -0.5
0.10 fix probably

2021-11-28 12:23 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +			chunk.free()
queue_free does that as well, but at the end of the frame

2021-11-28 12:24 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	var dir = Directory.new()
> When creating a new Directory, its default opened directory will be res://. This may change in the future, so it is advised to always use open to initialize your Directory where you want to operate, with explicit error checking.

But ok :) We can still create a ResourceDirectory class and a UserDirectory class

2021-11-28 12:26 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		or new_chunk.get_node("TrackObjects").get_child_count() > 0:
yeah I agree two indents is not optimal, but the inconsistency is not better as well IMHO. I was confused at first because I parsed them as new statements.

2021-11-28 12:27 UTC, HaSa1002 commented on src/Worlds/Signal-Tutorial/Scripting.gd
> +		return
true

2021-11-28 14:59 UTC, HaSa1002 commented
I found these issues:
1. Big Chunk chunk swich breaks the current chunk
2. Not all multimeshes get deleted on convert
3. Let's decrease the big chunk to 5000 again...
4. UI needs to be updated as well

2022-04-21 19:54 UTC, HaSa1002 commented
Rebase is needed. We can continue with this path as master is open for 1.0 now

2022-08-20 22:51 UTC, closed without merging