Add very simple scoring system
Libre-TrainSim/Libre-TrainSim pull request #249
Opened 2021-11-12 21:13 UTC by DasCapschen

Closes #31 

Scoring works like:
- you get 100 points when you arrive at a station
- you lose `speed - speedlimit` points when you drive too fast
	- example: speed limit = 80, you drive 90, you lose 10 points every 5 seconds until you slow down
- you lose 10 points if you arrive late (less than 1 minute)
- you lose 50 points if you arrive very late (more than 1 minute)
- you lose 50 points if you depart early
- you lose 100 points if you get an emergency braking
- you lose 1000 points if you pass a red light

At the end of the scenario, you get a message telling you the scenario is over and how many points you have scored.
Clicking OK will end the scenario and load the main menu.
![grafik](https://user-images.githubusercontent.com/3923406/141535025-c047a866-c3c0-4a79-884e-b60ef4b448f9.png)
(i used debug mode, so a lot of speeding, that's why it's -800 points 😅 )

2021-11-13 10:12 UTC, HaSa1002 approved these changes
I am not so sure about the amount of points, but that is easily fixable. Looks good otherwise (except for comment, but sadly has to be this way atm)

2021-11-13 10:12 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +### SIGNALS ###
ouf. Another thing in the player script. Like it isn't big enought already

2021-11-13 10:20 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +### SIGNALS ###
Yeah I know...
I could make it into its own script running on a node in the player, but then it still needs to be connected to the player by signals. I'm not sure if that makes it any better 🙈 

We can always refactor it later, it's pretty straightforward since it's only 1 variable and it doesn't interact with anything else.

2021-11-13 10:26 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +### SIGNALS ###
yeah I know.

2021-11-17 15:19 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +
```suggestion

```
You reset your editor settings 😅

2021-11-17 17:34 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +
Oh, yeah I had to wipe Godot because of some issue, guess I forgot to turn it back on. Will fix.

2021-11-21 13:23 UTC, HaSa1002 requested changes
Just nitpicking

2021-11-21 13:23 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +		score -= int((Math.speedToKmH(speed) - currentSpeedLimit) * SCORE_MULTIPLIER_TOO_FAST)
```suggestion
		score -= int(round((Math.speedToKmH(speed) - currentSpeedLimit) * SCORE_MULTIPLIER_TOO_FAST))

2021-11-21 13:28 UTC, HaSa1002 approved these changes
lgtm

2021-11-21 13:30 UTC, merged