Fix a few bugs
Libre-TrainSim/Libre-TrainSim pull request #266
Opened 2021-11-21 22:33 UTC by HaSa1002

- Fix content selector not displaying resources in builds
- Fix RailAttachments causing script error because of TrackObject.update
- Fix signals (the ingame one) causing script error because of types
- Remove select collider (without replacement for now. The objects should provide their own collider)

Fixes #242

2021-11-22 10:25 UTC, DasCapschen requested changes
Please consider comments. Other than that, looks good.

2021-11-22 10:25 UTC, DasCapschen commented on src/Data/Scripts/Singletons/Root.gd
> +			ext = file.get_extension()
Was the problem really the .import files? 🤔 
It used to work when we didn't load multiple mods...

But I guess this filters out the .import files from the file list?

2021-11-22 10:25 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> -		signal_ins.add_child(preload("res://Editor/Modules/SelectCollider.tscn").instance())
- We won't be able to select any Objects or Signals. That's not good. Why did you remove the select collider at all? What was the problem with it?

- >The objects should provide their own collider

  - Can you at least provide colliders for Signals then?

2021-11-22 10:25 UTC, DasCapschen commented on src/Resources/SignalTypes/Hp/Form/HpForm.tscn
> -
This will break Signal animations.
I'm guessing Godot removed this by itself (though I don't understand why, it does not for me). 
Please fix though.

2021-11-22 12:45 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +			ext = file.get_extension()
> Was the problem really the .import files? 🤔
> It used to work when we didn't load multiple mods...

yes it is. It was always broken.

> But I guess this filters out the .import files from the file list?

C'mon. That is not a valid use case.

2021-11-22 12:46 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> -		signal_ins.add_child(preload("res://Editor/Modules/SelectCollider.tscn").instance())
They don't work with signals as well. I just have to put colliders onto the signals itself. I tend to push towards the same direction for the buildings and just use them as scenes

2021-11-22 12:47 UTC, DasCapschen commented on src/Data/Scripts/Singletons/Root.gd
> +			ext = file.get_extension()
>yes it is. It was always broken.

Ah, alright then. Still kinda weird, how it worked before then.

>C'mon. That is not a valid use case.

I meant your code, what you're doing now is basically changing the path so it points to the original, instead of the .import, so we shouldn't see any .import files in the list.

2021-11-22 12:49 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +			ext = file.get_extension()
Yes that is the case. Because the loader loads the "non existent" file using the resource path

2021-11-22 12:49 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> -		signal_ins.add_child(preload("res://Editor/Modules/SelectCollider.tscn").instance())
Yeah, I get that you removed the select collider because they are broken. But can you add colliders to the Signals scenes itself then, like you suggested? So we can select them again?

2021-11-22 12:51 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> -		signal_ins.add_child(preload("res://Editor/Modules/SelectCollider.tscn").instance())
yeah will do tomorrow or the day after or when I have time again :D
Soon™

2021-11-22 12:53 UTC, DasCapschen commented on src/Data/Scripts/Singletons/Root.gd
> +			ext = file.get_extension()
Alright. Sounds good then.

2021-11-23 23:50 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> -		signal_ins.add_child(preload("res://Editor/Modules/SelectCollider.tscn").instance())
fixed

2021-11-23 23:51 UTC, HaSa1002 commented
Added more fixes 🙈 Sorry for bloating this one. This PR is insanly packed now

2021-11-24 08:17 UTC, DasCapschen approved these changes
lgtm

2021-11-24 08:19 UTC, merged