Draft: Use Radians for Calculations
Libre-TrainSim/Libre-TrainSim pull request #277
Opened 2021-12-05 15:23 UTC by DasCapschen

I changed all the calculations to use Radians instead of Degrees. 
Also refactors some variable and function names to match the coding style.
Should not be considered done yet, because I think currently .tscn and .save files use Degrees, so I need to make sure to convert those when loading an old version, for backwards compatibility.

We should not merge this for 0.9, because it's too close to release

Depends on #276

2022-04-21 19:54 UTC, HaSa1002 commented
Please rebase. We can go all in for 1.0 now :)

2022-04-21 21:35 UTC, DasCapschen commented
Rebased, but untested. Will test hopefully this weekend.

2022-08-20 13:01 UTC, HaSa1002 requested changes
Mostly minor things

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	SpeedPerKmH = (SpeedPointerRotationAt100 - SpeedPointerZero)/100.0
Using my superior math this should not work 😅
I am actually wondering how that ever worked? It looks more like it worked by accident.
(Also true for the next two calculations)

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +onready var cameraY: float = rotation.y - (PI/2.0)
```suggestion
onready var cameraY: float = rotation.y - (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +	cameraY = rotation.y - (PI/2.0)
```suggestion
	cameraY = rotation.y - (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +		rotation.y = cameraY + (PI/2.0)
```suggestion
		rotation.y = cameraY + (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +			rotation.y = attachedSeat.rotation.y + (PI/2.0)
```suggestion
			rotation.y = attachedSeat.rotation.y + (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +			rotation.y = atan(vector_delta.x/vector_delta.z)+PI
```suggestion
			rotation.y = atan(vector_delta.x / vector_delta.z) + PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +			var motionFactor = (refDelta / delta * refDelta) * mouseSensitivity * (camera_fov / ref_fov) * deg2rad(1)
Is that an arbitrary scale factor? What's the purpose?

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +			cameraX = clamp(cameraX, deg2rad(-85), deg2rad(85))
To me that looks like it should be clamped to PI. Anyway for the future.

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +			cameraNode.rotation.x = -cameraX
see points above

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +		currentrot = currentR.start_rot - 180.0
start_rot is still in degrees?

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +			currentrot = currentR.start_rot - 180.0
Bug? Is that still in degrees?

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +		return Transform(Basis().rotated(Vector3(1,0,0), parallel_rail.get_tend_at_distance(parDistance)).rotated(Vector3(0,0,1), parallel_rail.get_height_rot(parDistance)).rotated(Vector3(0,1,0), parallel
Woah! That's a line. Do you mind breaking it 😅

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	return(Vector3(circlePos.x, get_height(distance), -circlePos.y)).rotated(Vector3(0,1,0), start_rot)+start_pos
```suggestion
	return(Vector3(circlePos.x, get_height(distance), -circlePos.y)).rotated(Vector3(0,1,0), start_rot) + start_pos
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/RailMap.gd
> +		camera.rotation = (PI/2.0)
```suggestion
		camera.rotation = 0.5 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/RailMap.gd
> +		camera.rotation = $PlayerPolygon.rotation + (PI/2.0)
```suggestion
		camera.rotation = $PlayerPolygon.rotation + (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/TrackObjects.gd
> +						rot = rand_range(0, 2*PI)
```suggestion
						rot = rand_range(0, TAU)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Data/Scripts/WagonSound.gd
> +		sollCurveSound = -25.0 + (Math.speed_to_kmh(player.speed)/80.0 * abs(300.0/wagon.currentRail.radius))*5
Irgh. Goodt to know where the curve squeeking is in.

2022-08-20 13:01 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	track_object.rotationObjects = -(PI/2.0)
```suggestion
	track_object.rotationObjects = -(0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	camera.rotation.y -= (PI/2.0)
```suggestion
	camera.rotation.y -= (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_map.gd
> +	sprite.rotation = -rotation + (PI/2.0)
```suggestion
	sprite.rotation = -rotation + (0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +			node.rotation.y = deg2rad(-90)
```suggestion
			node.rotation.y = -0.5 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +	node.rotation.z = (PI/4.0)*command + deg2rad(1)
```suggestion
	node.rotation.z = (0.25 * PI)*command + deg2rad(1)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +		rotation = PI/4.0
```suggestion
		rotation = 0.25 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +		rotation = (PI/4.0) + command*(PI/2.0)
```suggestion
		rotation = (0.25 * PI) + (command * 0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +		rotation = PI/4.0
```suggestion
		rotation = 0.25 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScripting.gd
> +		rotation = (PI/4.0) - command*(PI/2.0)
```suggestion
		rotation = (0.25 * PI) - (command * 0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +			node.rotation.y = deg2rad(-90)
```suggestion
			node.rotation.y = -0.5 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +	node.rotation.z = (PI/4.0)*command + deg2rad(1)
```suggestion
	node.rotation.z = (0.25 * PI) * command + deg2rad(1)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +		rotation = PI/4.0
```suggestion
		rotation = 0.25 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +		rotation = (PI/4.0) + command*(PI/2.0)
```suggestion
		rotation = (0.25 * PI) + (command * 0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +		rotation = PI/4.0
```suggestion
		rotation = 0.25 * PI
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/Trains/JFR1/SpecificScriptingGrey.gd
> +		rotation = (PI/4.0) - command*(PI/2.0)
```suggestion
		rotation = (0.25 * PI) - (command * 0.5 * PI)
```

2022-08-20 13:01 UTC, HaSa1002 commented on src/test.tscn
> +curve = SubResource( 1 )
What is that?

2022-08-20 13:03 UTC, DasCapschen commented on src/test.tscn
> +curve = SubResource( 1 )
oops, that shouldn't have been there, I though I reset that with git before making changes 🤔 
I'll remove it asap

2022-08-20 13:05 UTC, DasCapschen commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	SpeedPerKmH = (SpeedPointerRotationAt100 - SpeedPointerZero)/100.0
Hmm, no, this actually works 😅 
SpeedPointerRotationAt100 is set in the scene, it's the rotation for 100km/h
SpeedPointerZero is the rotation for 0 km/h, which is the default rotation
(RotationAt100 - SpeedPointerZero) is thus the angle between 0 and 100 km/h
divide by 100 to get the angle the pointer needs to move per km/h
🤔

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +			var motionFactor = (refDelta / delta * refDelta) * mouseSensitivity * (camera_fov / ref_fov) * deg2rad(1)
Not arbitrary. Before, this calculation used degrees. Now we use radians. This would speed up the camera, because 1 radian = ~57 degrees. Thus, I slow down the movement by the inverse of that, so the camera remains as quick as before.

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +			cameraX = clamp(cameraX, deg2rad(-85), deg2rad(85))
If anything, `0.5 * PI` (90 degrees). But it makes sense to clamp it to a little bit less, maybe `PI * 0.45`

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +			cameraNode.rotation.y = cameraY + (PI/2.0)
```suggestion
			cameraNode.rotation.y = cameraY + (0.5 * PI)
```

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		currentrot = currentR.start_rot - 180.0
Nope, that's an oversight

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		currentrot = currentR.start_rot - 180.0
```suggestion
		currentrot = currentR.start_rot - PI
```

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +			currentrot = currentR.start_rot - 180.0
```suggestion
			currentrot = currentR.start_rot - PI
```

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/Rail.gd
> +		return Transform(Basis().rotated(Vector3(1,0,0), parallel_rail.get_tend_at_distance(parDistance)).rotated(Vector3(0,0,1), parallel_rail.get_height_rot(parDistance)).rotated(Vector3(0,1,0), parallel
I'll try 😅

2022-08-20 13:23 UTC, DasCapschen commented on src/Data/Scripts/TrackObjects.gd
> +						rot = rand_range(0, 2*PI)
I didn't know that was an available constant :D

2022-08-20 14:27 UTC, HaSa1002 approved these changes
lgtm

2022-08-20 14:27 UTC, merged

2022-08-20 14:27 UTC, HaSa1002 commented
Thanks ❤️

2022-08-20 14:27 UTC, HaSa1002 commented
Cherrypick or not?

2022-08-20 15:30 UTC, DasCapschen commented
> Cherrypick or not?

We can cherry pick it (plus bugfix for the camera as soon as I have it), but I don't know how many conflicts it will generate 😅