Add Scenario Editor
Libre-TrainSim/Libre-TrainSim pull request #278
Opened 2021-12-09 21:56 UTC by Jean28518

This PR comes with many changes:

- New Scenario Handling: We now have Tracks -> Scenarios -> Routes -> Selectable Time
- New Scenario Editor
- New Scenario Ingame Handling
- New Scenario File Structure
- New .trackinfo File
- New Main Menu Play Selection (Also with a proposal for a new list style)
- Station Signal Control (other PRs can be ignored)
- I started a new complete menu theme (`res://Data/UI/styles/complete_menu.theme`) (Makes it easier for huds in the future)
- Adjusted Tutorials for the new scenario file handling
- Track Editor Improvement
- Complete new Station Table Handling - (Every component except station jumping where adjusted to it, I will do this as I have time, this are just a few adjustments)
- Route baking at runtime by the Route Manager -> Old rail_route baking and handling is still active, but should be switched later to the new rail route format.
- Fixed bugs in Track Editor

I hope I didn't forget something :)

**Attention: All Scenarios of "old" tracks need to be rebuilded.** That should be very easy and much faster than before.

2021-12-09 23:08 UTC, HaSa1002 commented
I can't say I am happy about his PR. It is huge, it does a bunch of things, we want to release next week and I have to review it. Please take my language with a little distance. I don't know how harsh it's gonna sound.

I started with checking out your branch.

> I started a new complete menu theme (res://Data/UI/styles/complete_menu.theme) (Makes it easier for huds in the future)

There have been reasons why the UI was as granualar as it has been. Take this for instance:
![grafik](https://user-images.githubusercontent.com/14185889/145486195-e2e2ee89-ef74-4740-9c02-d62ef27a4e44.png)
Compared to:
![grafik](https://user-images.githubusercontent.com/14185889/145487267-d05a388a-6b6e-42f9-ae06-14ffe763ce8c.png)

Or see this image:
![grafik](https://user-images.githubusercontent.com/14185889/145486270-83f062a2-eef3-43ed-9063-937f2fe46d44.png)

Let's stick with the screenshot for a moment.
1. The header should not be SCREAMING AT OUR USERS! Instead it should use a bigger font. No text shadows pls.
2. Why do we need the inner border? It doesn't help with readability.
3. Focus and hover style don't match
4. Focused items round corners don't fit. The only excuse I have for round corners are departure tables. That is the sole reason the top corners are rounded. I absolutley hate round corners. They waste space. Not only space but whitespace that acts better as separator.

![grafik](https://user-images.githubusercontent.com/14185889/145485429-2c091a18-ab62-44d8-a5b1-30ff195bad5c.png)

Why do we need an entirley new scenario editor separated from the current editor? Why can't they be unified with the existing editor. What is the reasoning. (Though I have to admit, I like the schematic style but not at all for this purpose). It's hard to read, too.

![grafik](https://user-images.githubusercontent.com/14185889/145485961-73c5eee3-f1bf-4bd9-86fa-e2c4f859a925.png)

Ignoring the english, but that is exactly the reason I am not happy about the split.

![grafik](https://user-images.githubusercontent.com/14185889/145486857-8dda0da7-e8ab-4518-a35a-4765bd84a823.png)

Pressing back goes back into menus that have been previously omitted. I am not sure about the spacing. But again the round corners break with the buttons.
Pressing select between every click is honestly annoying. Granted, the menu has benefits for mobile devices but why do we need to sacrifice mouse input for touch input? (I know it is a trend, but I am the one using windows :P)

> New Scenario Handling: We now have Tracks -> Scenarios -> Routes -> Selectable Time

This can be achieved way easier. I dislike the menu structure.

> New Scenario File Structure
> New .trackinfo File

Do you want to punish @DasCapschen? The idea is to move to Godot native files. Are the new files really necessary? Couldn't you have been using resources?

> Station Signal Control (other PRs can be ignored)

See, this is my problem with this PR. You should have reacted to our reviews and acted on them. They already have taken a considerable amount of time. And yet, here I am again and have to review them a third time. It's not like I am jobless.

> Complete new Station Table Handling - (Every component except station jumping where adjusted to it, I will do this as I have time, this are just a few adjustments)

Don't know what to do with the info. I guess I will know how to react once I got into code review. But fix station jumping ASAP.

> Route baking at runtime by the Route Manager -> Old rail_route baking and handling is still active, but should be switched later to the new rail route format.

Same as above. Why didn't you remove the old code completely?

> Fixed bugs in Track Editor

Namely?

> Changed the default time format in world to seconds. You are still able to convert between array and seconds mode with Math Libary

Please don't do half baked changes. Either completely or not. Why is it necessary to keep the array time stuff?

> Signals now have an operation_mode: They can be a block signal, a station signal or in manual mode.

I thought they already worked that way. But again, why in a PR named "Add Scenario Editor".

Why did you change the clear color of 2D just for the scenario editor?
![grafik](https://user-images.githubusercontent.com/14185889/145488917-75d9cfba-f6d4-4752-9b67-4b82fb7f4f6f.png)

2021-12-10 15:54 UTC, Jean28518 commented
The complete_menu_theme is just a proposal.
With it you are also able to overwrite some button styles e.g.
It's just to save a bit time creating huds.
I don't agree with your meaning about round corners, for example this view looks very nice in my opinion:
![grafik](https://user-images.githubusercontent.com/39700889/145596264-e86882f0-a819-4ddf-aec8-6e9a0bdd90ed.png)
But for me the UI is completely irrelevant.

> Why do we need an entirley new scenario editor separated from the current editor? Why can't they be unified with the existing editor. What is the reasoning. (Though I have to admit, I like the schematic style but not at all for this purpose). It's hard to read, too.

The track editor contains everything about track building and the scenario editor contains everything about making scenarios. With it you are able to create new scenarios for existing tracks. Without scraping the original track data. In my opinion that's very nice. Other Train Simulators have this feature too.
The scenario editor and track editor don't have the same functionality - beside the small exception with the station settings you mentioned. But that exception well thought and useful.

> Granted, the menu has benefits for mobile devices but why do we need to sacrifice mouse input for touch input? (I know it is a trend, but I am the one using windows :P)
> >New Scenario Handling: We now have Tracks -> Scenarios -> Routes -> Selectable Time

> This can be achieved way easier. I dislike the menu structure.

What's your proposal about this? What do you dislike about the current structure?

> Do you want to punish @DasCapschen? The idea is to move to Godot native files. Are the new files really necessary? Couldn't you have been using resources?
These files don't contain much path information. There is no big advantage using them. But I have no problem in changing this.

> See, this is my problem with this PR. You should have reacted to our reviews and acted on them. They already have taken a considerable amount of time. And yet, here I am again and have to review them a third time. It's not like I am jobless.

I implemented your reviews and comments.. Why isn't that PR in master? But yeah.. this PR depends on station signals... 

> Same as above. Why didn't you remove the old code completely?

Because this brings many code adjustments with it and much bug potential. For the time everything is working as usual about this topic.

> > Changed the default time format in world to seconds. You are still able to convert between array and seconds mode with Math Libary
> Please don't do half baked changes. Either completely or not. Why is it necessary to keep the array time stuff?

The array stuff is sometimes useful for example the digital clock in the displays.

> > Signals now have an operation_mode: They can be a block signal, a station signal or in manual mode.

> I thought they already worked that way. But again, why in a PR named "Add Scenario Editor".

Because the scenario manager is working with the operation mode, It's just a better declaration, how the signals are working.

> Why did you change the clear color of 2D just for the scenario editor?

SImple hack for the background of the scenario editor. For the time that's okay, we don't use that color at any other point.


> I can't say I am happy about his PR. It is huge, it does a bunch of things, we want to release next week and I have to review it. Please take my language with a little distance. I don't know how harsh it's gonna sound.

That's no excuse. Please keep kind :)

At the time I don't see a release next week.. Also without this PR there are so many things to fix and polish.
E.g. just look at the cabin. The materials are looking ugly and the cabin is not modeled. The train info (F2) has bugs.
Also the track editor at upstream is kind of unusable. E.g. there weren't any options for selecting a building or changing a value and fly around after is just pain. (I fixed many small bugs like these in this PR). 

Will start working at some adjusments in this PR tomorrow.

2021-12-12 17:50 UTC, HaSa1002 requested changes

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/Rail.tscn
> +script = ExtResource( 4 )
Remove script

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/RouteManager.tscn
> +[gd_scene load_steps=2 format=2]
Why do you add a RouteManager scene? You could simply do RouteManager.new() in code.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/ScenarioManager.tscn
> +[gd_scene load_steps=3 format=2]
Same as for RouteManager

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/SelectCollider.tscn
> +[gd_scene load_steps=2 format=2]
I would prefer to no have this.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/Station.tscn
> +[node name="Mesh" type="MeshInstance" parent="."]
That is the reason I removed the SelectCollider.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Modules/World-Pattern.tscn
> +[node name="ScenarioManager" parent="." instance=ExtResource( 5 )]
Not sure this should be in world pattern. WDYT @DasCapschen

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Screens/ScreenTimeTable/screen_time_table.gd
> +func update_display(station_table, current_station_table_index, is_in_station):
Please add type hints for the function args

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Screens/ScreenTimeTable/screen_time_table.gd
> +	for i in range (current_station_table_index, station_table.size()):
```suggestion
	for i in range(current_station_table_index, station_table.size()):
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Screens/ScreenTimeTable/screen_time_table.gd
> +		if [StopType.BEGINNING, StopType.DO_NOT_HALT].has(station_table[i].stop_type):
@DasCapschen WDYT about those constructs?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/ContactPoint.gd
> +	disabled = not d.enabled
TBH. I would prefer not using `not`. I think that is more readable:
```suggestion
	disabled = !d.enabled
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Enums/stop_type.gd
> +	DO_NOT_HALT = 0,
```suggestion
	DO_NOT_STOP = 0,
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +var current_station_node: Node # If we are in a station, this variable stores the current station node, otherwise its null.
```suggestion
var current_station_table_index: int = 0 # Displays the index of the next or current station of station_table
var current_station_table_entry: Dictionary = null
var current_station_node: Node = null # If we are in a station, this variable stores the current station node, otherwise its null.
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +export var doors: bool = true # Defines, if this train has doors.
```suggestion
var is_in_station := false # true if the train speed = 0, the train is fully in the station, and doors were opened. - Until depart Message
var real_arrival_time: int # Time is set if train successfully arrived
var route_distance_at_station_begin: float = 0 # distance of the station begin on route
const GOODWILL_DISTANCE: float = 10 # distance the player can overdrive a station, or it's train end isn't in the station.

export var doors := true # Defines, if this train has doors.
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +	forward = route_information[0].forward
then delete pls.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +				Logger.warn("Route incorrect! Reached station %s but the next_station should be %s." % [signal_passed.name, world.get_signal(station_table[current_station_table_index].node_name).name], self)
This is a bug. Please err. Please add assert as well

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +	or (current_station_table_entry.stop_type == StopType.BEGINNING and not is_in_station)):
```suggestion
			((doorLeft and current_station_node.platform_side == PlatformSide.LEFT) \
			or (doorRight and current_station_node.platform_side == PlatformSide.RIGHT)\
			or (doorLeft and doorRight and current_station_node.platform_side == PlatformSide.BOTH)\
			or current_station_node.platform_side == PlatformSide.NONE)\
			or (current_station_table_entry.stop_type == StopType.BEGINNING and not is_in_station)):
```
Multiline statements are indented by two tabs.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +	world.time >= real_arrival_time + current_station_table_entry.minimal_halt_time:
```suggestion
			world.time >= real_arrival_time + current_station_table_entry.minimal_halt_time:
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +var route: Array = [] # Array of strings. Is obsolete, like bake_route().
delete pls.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +# For more information look to the comment at the variable definition of 'route_information'.
pls fix RouteManager and remove code.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/RailMap.gd
I am not so sure about using the rail map as gameplay feature and as editor. Splitting it into a base that shares the common functionality and seperate it in to a editor map and game map seems to be better to me. @DasCapschen opinions?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/SifaModule.gd
> +	return stage > 0
????

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Signal.gd
> +export var signal_free_time = -1 # the signal will be turned to status = 1 at this specified time. Set to -1 to deactivate. Only available in manual mode.
```suggestion
export var signal_free_time: int = -1 # the signal will be turned to status = 1 at this specified time. Set to -1 to deactivate. Only available in manual mode.
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Signal.gd
> +export var operation_mode: int = SignalOperationMode.BLOCK
```suggestion
export(SignalOperationMode) var operation_mode: int = SignalOperationMode.BLOCK
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Signal.gd
> +				$SelectCollider.queue_free()
Remove SelectCollider from signals pls.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Math.gd
> +	return time2String(time)
```suggestion
func seconds_to_string(time_seconds: int) -> String:
	return "%02d:%02d:%02d" % [time_seconds/3600, (time_seconds/60)%60, time_seconds%60]
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +var selected_time: int # start time of scenario in seconds
Please try to avoid global variables. There are ways to pass them. The loading screen did that for example. On a different note. Why do you have nulled variables? Why don't you set empty strings. That would be safer.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +var current_editor_track_path: String = ""
see comment above.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> -# found_files is return value
why do you removed that?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +	current_editor_track = path_to_tscn.get_file().get_basename()
please do local passing

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
What do you do here? The content repo should contain all that info.
wdyt @DasCapschen

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/SpeedLimitSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
remove pls. Signals have their colliders.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/SpeedLimitSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
and if they don't. Generate and commit them.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/SpeedLimitWarnSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
see above.
This code is duplicated. Maybe we should consider a common base inheriting RailLogic.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/Station.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
Wait. That is the blue arrow, right? Remove this and click on generate convex collision polygon and add to blue arrow scene

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +		$StationJumper/ItemList.add_item(player.station_table[station_index].station_name)
If `station_name` is a dict entry please use square brackets.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		return
This **is** a bug. Please treat it as a bug.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +var pending_train_spawns: Array = []
```suggestion
var pending_train_spawns := []
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +var passive: bool = false
```suggestion
var passive := false
```
I haven't read the code yet. But if this turns out to be a flag that is checked on every method call wether or not the world is used in the scenario editor then the relevant code should be ported to a base class which used in the scenario editor and this class.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +		passive = true
```suggestion
	passive = Root.scenario_editor
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +		add_child(preload("res://Data/Modules/ScenarioManager.tscn").instance())
@DasCapschen you removed them iirc, wdyt?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +		return
...

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +}
What is that? And why is is burried down here?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +				signal_two.update()
@DasCapschen wdyt? May it clash with the save system?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
No. Not here.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/route_manager.gd
> +}
If you create a pattern for a dict, it's probably better to create a class.
\+ Those classes could inherit from resource and thus can easily saved using Godots resource system.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/route_manager.gd
> +}
see above.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/route_manager.gd
> +extends Node
```suggestion
class_name RouteManager
extends Reference
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/route_manager.gd
> +	var minimal_platform_length: int = 1000000000000000
```suggestion
	var minimal_platform_length: int = INF
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/route_manager.gd
> +		return {}
Do asserts for these kind of checks. These are all bugs

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/scenario_manager.gd
> +extends Node
```suggestion
class_name ScenarioManager
extends Node
```

What is the purpose of this class?
Why do we need a ScenarioManager that babysits RouteManagers.
I feel like the whole system should just consist of Route classes that inherit Resource. We wouldn't need any custom save or get or whatever logic. The bits of custom logic can then be put inside the Route class.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/Scripts/select_collider.gd
> +		$CollisionShape.shape = mesh.create_convex_shape()
please remove. Buildings are the only valid use case, but they should use the aabb collider instead.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/main_menu.tscn
> +rect_min_size = Vector2( 330, 0 )
Why? This is full rect.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/main_menu.tscn
> +margin_right = 330.0
They are a multiple of four for scaling reasons.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/main_menu.tscn
> +[node name="CreateMenu" type="VBoxContainer" parent="."]
own scene please

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/map.gd
> -
empty line at eof.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/map.gd
> +	map_status = MapStatus.FULL
idk. This feels hacky. Wdyt @DasCapschen

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +var selected_train: String = ""
```suggestion
var selected_track := ""
var selected_scenario := ""
var selected_route := ""
var selected_time: int = -1
var selected_train := ""
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +extends Panel
Please use Containers.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +		update_scenarios()
Why? This won't be the case anyway. Remove pls.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +func _on_Trackst_item_selected(index) -> void:
`trackst`?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +	var screenshot_texture: Texture
Why did you make that local?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
Please fix file structure.
```
01. tool
02. class_name
03. extends
04. # docstring

05. signals
06. enums
07. constants
08. exported variables
09. public variables
10. private variables
11. onready variables

12. optional built-in virtual _init method
13. built-in virtual _ready method
14. remaining built-in virtual methods
15. public methods
16. private methods
17. callbacks
```

and always use *exactly* two empty lines between functions

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu_old.gd
> +extends PanelContainer
remove pls.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu_old.tscn
> +[gd_scene load_steps=10 format=2]
remove pls

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/play_menu.tscn
> +[node name="PlayMenu" type="Panel"]
Please use a PanelContainer. Please use Containers whenever possible

2021-12-12 17:50 UTC, HaSa1002 commented on src/Data/UI/styles/font_main_menu.tres
> +[ext_resource path="res://addons/Libre_Train_Sim_Editor/Data/Misc/FontMedium.tres" type="DynamicFont" id=1]
I think this is a rebase error

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Editor.tscn
> +[ext_resource path="res://Data/UI/styles/complete_menu.theme" type="Theme" id=13]
Buttons should be centred variants

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/Collider2D.gd
> +	$CollisionShape2D.shape.radius = new_radius
What?
Are you sure get_parent().get_parent().name is safe?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/Collider2D.gd
> +	$CollisionShape2D.shape.radius = new_radius
and which type is input_handling_node?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/Rail2DCollider.gd
> +	var width = get_parent().width
That is absolutely prone to breaking.
I cannot only break but rather will break.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/Rail2DCollider.gd
> +extends Area2D
Please supply a class name, format according to style guide and remove commented code.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/Rail2DCollider.tscn
> +[gd_scene load_steps=2 format=2]
This can and should be done from within the rail collider script.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/RailLogic.gd
> +	visible = is_instance_valid(current_rail_logic) and get_parent().current_tab == 2
No. We don't need this code. If the signal is deleted, hide should explicitly called.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/RailLogic.gd
> -	$ContactPointSettings.visible = current_rail_logic_type == RailLogicTypes.CONTACT_POINT
Idk this code. Why has so much been removed here?

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Modules/scenario_editor.tscn
> +[gd_scene load_steps=11 format=2]
No way I can review this file. Please break this huge scene in multiple smaller once.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +
please remove (as well as the button). I am going to fix that in a separate PR with a built-in method.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	mesh_instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
If you could replace that with the aabb collider, you can remove the select collider.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +				+ "Please use a build of Libre TrainSim for exporting tracks. ")
That is not correct.
You can export but you can't test them.
```suggestion
		send_message("Can't test tracks if runs Libre TrainSim using the Godot Editor. " \
				+ "Please use a build of Libre TrainSim to test tracks. ")
```

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/ScenarioConfiguration.gd
> +extends Panel
That script is 750 lines too long. I guess there is stuff in it that I don't like but YOLO.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/ScenarioMap.gd
> +onready var despawn_point_icon = preload("res://Data/Misc/despawn_point_icon.png")
onready is unnecessary.

2021-12-12 17:50 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_map.gd
> +extends Node
please delete the other scenario map script.

2021-12-12 17:50 UTC, HaSa1002 commented
Just for the record. This review took me almost five hours.

2021-12-13 13:21 UTC, Jean28518 commented on src/Data/Scripts/Player.gd
> +				Logger.warn("Route incorrect! Reached station %s but the next_station should be %s." % [signal_passed.name, world.get_signal(station_table[current_station_table_index].node_name).name], self)
Can't assert that, because the code line in 801 happens, when the train jumps between stations.
But will err that message.

2021-12-13 13:26 UTC, Jean28518 commented on src/Data/Scripts/Player.gd
> +	forward = route_information[0].forward
Wouldn't touch the old route baking process before the release. Now everything is working with this workaround. Would change this in v.010

2021-12-13 13:27 UTC, Jean28518 commented on src/Data/Scripts/Player.gd
> +var route: Array = [] # Array of strings. Is obsolete, like bake_route().
Wouldn't touch the old route baking process before the release. Now everything is working with this workaround. Would change this in v.010

2021-12-13 13:27 UTC, Jean28518 commented on src/Data/Scripts/Player.gd
> +# For more information look to the comment at the variable definition of 'route_information'.
Wouldn't touch the old route baking process before the release. Now everything is working with this workaround. Would change this in v.010

2021-12-13 13:29 UTC, Jean28518 commented on src/Data/Scripts/RailMap.gd
I am not using the RailMap,.
It was my intentional thought, but these both two differ too much.
I kept the code inside, which could be useful, if we want to use this Map in the Track Editor e.g.

2021-12-13 13:30 UTC, Jean28518 commented on src/Data/Scripts/SifaModule.gd
> +	return stage > 0
If the sifa want's to be pressed, so I can display the message in the tutorial to press the sifa key

2021-12-13 13:37 UTC, Jean28518 commented on src/Data/Scripts/Singletons/Root.gd
> -# found_files is return value
Because now the function doesn't return anything anymore..

2021-12-13 13:39 UTC, Jean28518 commented on src/Data/Scripts/Singletons/Root.gd
> +	current_editor_track = path_to_tscn.get_file().get_basename()
done

2021-12-13 13:41 UTC, HaSa1002 commented on src/Data/Scripts/RailMap.gd
The code ist not going to be useful. It's going to be dead code. If we are going to need it again then we can reimplement it. Please remove.

2021-12-13 13:41 UTC, Jean28518 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
We need a place for these script functions. But we can move these functions to a new separate file if you want.
But in my opinion these functions suit to this script.

2021-12-13 13:43 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> -# found_files is return value
Well it does. found_files is passed as reference and it is good to mention where to find the result

2021-12-13 13:44 UTC, Jean28518 commented on src/Data/Scripts/StationJumper.gd
> +		$StationJumper/ItemList.add_item(player.station_table[station_index].station_name)
These are all dict entries... for me if I change these all to square brackets, the code gets harder to read.

2021-12-13 13:44 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
I am talking about the crawling. That shouldn't happen IMO. The info you are looking for should be in the content repo.

2021-12-13 13:45 UTC, Jean28518 commented on src/Data/Scripts/chunk_manager.gd
> +		return
But crashing the game because of this isn't the right way. It isn't critical.

2021-12-13 13:51 UTC, Jean28518 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
That makes things much more complicated with editor.
Then a track builder can't add or remove files at the editor location easier. 
For ready game packs I can understand the sense of the the content.repo. But for editor tracks in my opnion that makes things just more complicated. 
And for us that works just fine. Why change this?

2021-12-13 13:54 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +				signal_two.update()
Doesn't clash.
Save system doesn't save this at all. It's just saved in the .tscn file.

2021-12-13 13:58 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +}
because this is all important information for the train spawner in the world. It's just used of two functions in this script. Nowhere else.

2021-12-13 14:02 UTC, Jean28518 commented on src/Data/UI/map.gd
> +	map_status = MapStatus.FULL
Was my fault. Don't need this at all anymore.. I removed the function

2021-12-13 14:07 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +var selected_train: String = ""
I didn't find anything about this convention in the official style guide. So we document that convention somewhere.

2021-12-13 14:09 UTC, Jean28518 commented on src/Data/Scripts/scenario_manager.gd
> +extends Node
route manager just handles the route points. Not the whole scenario or the general information about the route such as time, interval or anything else.

2021-12-13 14:12 UTC, Jean28518 commented on src/Data/UI/main_menu.tscn
> +rect_min_size = Vector2( 330, 0 )
Then these buttons have the same size like the new Create Button Menu. That Min size determines the width, not the height.

2021-12-13 14:14 UTC, Jean28518 commented on src/Data/UI/main_menu.tscn
> +margin_right = 330.0
done

2021-12-13 14:15 UTC, Jean28518 commented on src/Data/UI/main_menu.tscn
> +[node name="CreateMenu" type="VBoxContainer" parent="."]
These are just the three main menu buttons.

2021-12-13 14:18 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> +
done

2021-12-13 14:22 UTC, Jean28518 commented on src/Editor/Modules/RailLogic.gd
> -	$ContactPointSettings.visible = current_rail_logic_type == RailLogicTypes.CONTACT_POINT
Because I cleaned the Editor Functionality. So such things like signal status should be only set in the scenario editor.

2021-12-13 16:20 UTC, Jean28518 commented on src/Data/Modules/World-Pattern.tscn
> +[node name="ScenarioManager" parent="." instance=ExtResource( 5 )]
removed these nodes

2021-12-13 16:23 UTC, Jean28518 commented on src/Data/Scripts/RailMap.gd
done

2021-12-13 16:24 UTC, Jean28518 commented on src/Data/Scripts/Singletons/Root.gd
> +var selected_time: int # start time of scenario in seconds
I don't have any plan how to get the loading screen working with scenario editor.
When we get that running, I have no problem with it.

2021-12-13 16:26 UTC, Jean28518 commented on src/Data/Scripts/Singletons/Root.gd
> -# found_files is return value
done

2021-12-13 16:29 UTC, Jean28518 commented on src/Data/Scripts/chunk_manager.gd
> +		return
added `Logger.err("Tried to ad an object to world, which is already loaded. Skip loading this object...", instance)` to it.

2021-12-13 16:33 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +		add_child(preload("res://Data/Modules/ScenarioManager.tscn").instance())
removed..

2021-12-13 16:35 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +		return
yeah we could invest one hour in separting this niceley, but then we also should separate code functions between ingame and Track Editor too. 
So for me this way is okay. It doesn't waste many system resources.

2021-12-13 16:37 UTC, Jean28518 commented on src/Data/Scripts/route_manager.gd
> +		return {}
You are right, done

2021-12-13 16:40 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +extends Panel
What is the advantage?
With Panels I can define margins of the children very easily

2021-12-13 16:41 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +		update_scenarios()
If someone wants to export the game with only one track this would be skipped.

2021-12-13 16:49 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +func _on_Trackst_item_selected(index) -> void:
fixed

2021-12-13 16:49 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +	var screenshot_texture: Texture
Do we need this global?

2021-12-13 16:55 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
done

2021-12-13 16:57 UTC, Jean28518 commented on src/Data/UI/styles/font_main_menu.tres
> +[ext_resource path="res://addons/Libre_Train_Sim_Editor/Data/Misc/FontMedium.tres" type="DynamicFont" id=1]
done

2021-12-13 16:59 UTC, Jean28518 commented on src/Editor/Editor.tscn
> +[ext_resource path="res://Data/UI/styles/complete_menu.theme" type="Theme" id=13]
done

2021-12-13 20:39 UTC, HaSa1002 commented on src/Data/Scripts/scenario_manager.gd
> +extends Node
But why doesn't do it? What is the issue with having that in a Route class?

2021-12-13 20:40 UTC, HaSa1002 commented on src/Data/UI/main_menu.tscn
> +rect_min_size = Vector2( 330, 0 )
To me this looks like the anchors are screwed up

2021-12-13 20:43 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +extends Panel
You only need to ensure the parent has the correct anchors. The rest is set using size flags. It often results in easier working menus.

2021-12-13 20:44 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +		update_scenarios()
Yes and again that won't happen. We have at least three tracks with the tutorials. In release builds we are going to have five.

2021-12-13 20:45 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +	var screenshot_texture: Texture
I thought I reused the screenshot_texture, but apparently I don't so this is fine.

2021-12-15 14:14 UTC, Jean28518 commented on src/Data/Scripts/Signal.gd
> +				$SelectCollider.queue_free()
Its the Select Collider from your aabb creator

2021-12-15 14:15 UTC, Jean28518 commented on src/Data/Scripts/SpeedLimitSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
done

2021-12-15 14:15 UTC, Jean28518 commented on src/Data/Scripts/SpeedLimitWarnSignal.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
done

2021-12-15 14:16 UTC, Jean28518 commented on src/Data/Scripts/Station.gd
> +		add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
done, with the aabb collider generator

2021-12-15 14:24 UTC, Jean28518 commented on src/Data/Scripts/chunk_manager.gd
> +		instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
done. Added it to line 327

2021-12-15 14:28 UTC, DasCapschen commented on src/Data/Screens/ScreenTimeTable/screen_time_table.gd
> +		if [StopType.BEGINNING, StopType.DO_NOT_HALT].has(station_table[i].stop_type):
I would prefer a classic `==` check, which is most likely also faster, and more readable.

2021-12-15 14:32 UTC, DasCapschen commented on src/Data/Scripts/ContactPoint.gd
> +	disabled = not d.enabled
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#boolean-operators

in the same vain, I would actually encourage `not` over `!`

2021-12-15 14:35 UTC, DasCapschen commented on src/Data/Scripts/RailMap.gd
So are you using the RailMap as an Editor feature or not?
Because if you are not, then could you remove all the `if not Root.Editor` from the file and restore it to the way it was before?

2021-12-15 14:36 UTC, DasCapschen commented on src/Data/Scripts/SifaModule.gd
> +	return stage > 0
Then this should be in the tutorial script, not in the Sifa Module!

2021-12-15 14:36 UTC, Jean28518 commented on src/Data/Scripts/chunk_manager.gd
> +		instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
Removed it colpletely.

2021-12-15 14:45 UTC, DasCapschen commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
@HaSa1002 those look similar to functions you wrote for loading Editor maps. The content loader does not load anything from `user://editor`, so editor maps are not in the global content repo upon loading. 
see `editor_configuration.gd` function `_find_content()`.

2021-12-15 14:48 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		return
Keep. The. Assert.

2021-12-15 14:52 UTC, Jean28518 commented on src/Data/Scripts/route_manager.gd
> +}
![grafik](https://user-images.githubusercontent.com/39700889/146207909-c353c491-b5f9-40cc-837b-1317cdd5e251.png)

Tried it, but get errors out of this. 
Also don't know how to save it easily and load it again.
I don't have the time to invest several hours to get this running properly.

2021-12-15 14:52 UTC, Jean28518 commented on src/Data/Scripts/route_manager.gd
> +}
see above

2021-12-15 14:58 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> +	mesh_instance.add_child(preload("res://Data/Modules/SelectCollider.tscn").instance())
done, but we need to handle building selection for the release. don't want to do this in this PR

2021-12-15 14:59 UTC, Jean28518 commented on src/Data/Scripts/select_collider.gd
> +		$CollisionShape.shape = mesh.create_convex_shape()
done

2021-12-15 15:03 UTC, Jean28518 commented on src/Data/UI/main_menu.tscn
> +rect_min_size = Vector2( 330, 0 )
done

2021-12-15 15:08 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +extends Panel
![grafik](https://user-images.githubusercontent.com/39700889/146210994-ba86a536-ec77-4340-8ca0-8e480f1e9a41.png)
With Panel

![grafik](https://user-images.githubusercontent.com/39700889/146211502-f1ed1130-a730-4c29-b596-da0b73451e33.png)
With PanelContainer

Do you see the difference?
Didn't get the space with PanelContainer

2021-12-15 15:11 UTC, Jean28518 commented on src/Data/UI/play_menu.gd
> +		update_scenarios()
Yes and again: If someone wants to export the game with only one track this would be skipped.

2021-12-15 15:11 UTC, Jean28518 commented on src/Data/UI/play_menu.tscn
> +[node name="PlayMenu" type="Panel"]
see discussion above

2021-12-15 15:13 UTC, Jean28518 commented on src/Editor/Modules/Collider2D.gd
> +	$CollisionShape2D.shape.radius = new_radius
For the use cases that is safe. 
added type to variable.

2021-12-15 15:14 UTC, Jean28518 commented on src/Editor/Modules/Rail2DCollider.gd
> +	var width = get_parent().width
For our use cases that just works fine.

2021-12-15 15:33 UTC, Jean28518 commented on src/Editor/Modules/Rail2DCollider.gd
> +extends Area2D
done

2021-12-15 15:33 UTC, Jean28518 commented on src/Editor/Modules/RailLogic.gd
> +	visible = is_instance_valid(current_rail_logic) and get_parent().current_tab == 2
done

2021-12-15 15:33 UTC, Jean28518 commented on src/Editor/Modules/Rail2DCollider.tscn
> +[gd_scene load_steps=2 format=2]
done, removed

2021-12-15 15:38 UTC, Jean28518 commented on src/Editor/Modules/scenario_editor.tscn
> +[gd_scene load_steps=11 format=2]
done

2021-12-15 15:46 UTC, Jean28518 commented on src/Data/Screens/ScreenTimeTable/screen_time_table.gd
> +		if [StopType.BEGINNING, StopType.DO_NOT_HALT].has(station_table[i].stop_type):
done. these constructs are removed.

2021-12-15 15:47 UTC, Jean28518 commented on src/Data/Scripts/RailMap.gd
Don't use it. already done.

2021-12-15 15:50 UTC, Jean28518 commented on src/Data/Scripts/SifaModule.gd
> +	return stage > 0
done.

2021-12-15 15:50 UTC, Jean28518 commented on src/Data/Modules/SelectCollider.tscn
> +[gd_scene load_steps=2 format=2]
done

2021-12-15 15:51 UTC, Jean28518 commented on src/Data/Modules/Rail.tscn
> +script = ExtResource( 4 )
done

2021-12-15 15:51 UTC, Jean28518 commented on src/Data/Modules/RouteManager.tscn
> +[gd_scene load_steps=2 format=2]
done

2021-12-15 15:51 UTC, Jean28518 commented on src/Data/Modules/ScenarioManager.tscn
> +[gd_scene load_steps=3 format=2]
done

2021-12-15 15:53 UTC, Jean28518 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	return ""
Also using this function in @DasCapschen mentioned function

2021-12-15 15:56 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +var pending_train_spawns: Array = []
done

2021-12-15 15:56 UTC, Jean28518 commented on src/Data/Scripts/World.gd
> +var passive: bool = false
done

2021-12-15 15:58 UTC, Jean28518 commented on src/Data/Scripts/scenario_manager.gd
> +extends Node
You are right. Maybe we could merge it together. I will merge this both two

2021-12-15 16:08 UTC, Jean28518 commented
Thank you very much for your time. Sorry for sometimes being harsh in the comments.
I am already sitting about 70 hours on this PR, want to get this finally done.

Next time I will make multiple, smaller PRs. Fingers crossed.

2021-12-16 14:03 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +extends Panel
Alright. I will change it.

2021-12-16 14:13 UTC, HaSa1002 approved these changes
I have no further energy for this PR. Please squash the commits.

2021-12-16 17:16 UTC, DasCapschen approved these changes
Let's get this in. We can deal with any problems in further PRs.

2021-12-16 21:25 UTC, merged