Fix export and test buttons
Libre-TrainSim/Libre-TrainSim pull request #302
Opened 2022-01-08 16:01 UTC by Jean28518

Should now work as expected.
Now testing and exporting is available from the scenario editor too.
Created a new export_track class to keep to avoid code duplications.

Does NOT implement #187

2022-01-09 19:06 UTC, HaSa1002 requested changes

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> -			selected_object.get_child(1).queue_free()
Why is that? Can you still delete a building?

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		send_message("To test this track you need to create a scenario in the scenario editor first")
```suggestion
		send_message("Cannot test the track! Please create a scenario using the scenario editor.")
```

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		return("No scenario found! To export this track you need to create a scenario in the scenario editor first")
```suggestion
		send_message("No scenario found! Please create a scenario in the scenario editor to enable track exporting.")
		return
```
Please send the message in the function and return void instead.

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	send_message(export_mod())
```suggestion
	export_mod()
```

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/export_track.gd
> +class_name ExportTrack
I assume this is the code that was in editor.gd? Please compare and check with the mod_tools script. In doubt the exporting of the mod tools is correct and should be used instead.

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +	show_message(export_mod())
```suggestion
	export_mod()
```

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +		show_message("To test this track you need to create a scenario in the scenario editor first")
```suggestion
		send_message("Cannot test the track! Please create a scenario.")
```

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +		return "No scenario found! To export this track you need to create a scenario in the scenario editor first"
```suggestion
func export_mod() -> void:
	if ContentLoader.get_scenarios_for_track(current_track_path).size() == 0:
		send_message("No scenario found! Please create a scenario.")
		return
```

2022-01-09 19:06 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +	return ExportTrack.export_editor_track(track_name, export_path)
```suggestion
	send_message(ExportTrack.export_editor_track(track_name, export_path))
	return
```

2022-01-12 21:01 UTC, Jean28518 commented on src/Editor/Scripts/export_track.gd
> +class_name ExportTrack
Tried this already.
But didn't work out.
I think it was about different pathes somewhere.

2022-01-12 21:01 UTC, Jean28518 commented on src/Editor/Scripts/scenario_editor.gd
> +	show_message(export_mod())
Why?

2022-01-12 21:02 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> +	send_message(export_mod())
Why?

2022-01-16 07:54 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> -			selected_object.get_child(1).queue_free()
Thanks for your hint.
This change was wrong of me. It was crashing there.

Reimplemented it without any crashes in the latest commit.

2022-01-16 07:54 UTC, Jean28518 commented
For me this one can be merged.

2022-01-17 12:12 UTC, HaSa1002 approved these changes
untested. Let's merge and see what breaks :P

2022-01-17 12:12 UTC, merged