Add deletion of content and tracks
Libre-TrainSim/Libre-TrainSim pull request #303
Opened 2022-01-09 14:43 UTC by Jean28518

Implements #192 .
Didn't add any functionality to the content view, because it has a weird ui structure without a item list.

2022-01-11 14:24 UTC, DasCapschen requested changes

2022-01-11 14:24 UTC, DasCapschen commented on src/Data/UI/styles/panel_background.tres
> +border_width_bottom = 4
Why is this in this PR?
Same for `complete_menu.theme`.

2022-01-11 14:24 UTC, DasCapschen commented on src/Editor/editor_configuration.tscn
> +cancel_text = "CANCEL"
Why not use a key + translation for the confirmation text as well?

2022-01-11 14:24 UTC, DasCapschen commented on src/Editor/Modules/scenario_editor_selection.tscn
> +remove_confirmation_text = "Do you really want to delete these scenarios (from harddisk!)?"
key + translation, instead of hardcoding text?

2022-01-11 14:24 UTC, DasCapschen commented on src/Editor/Scripts/editor_configuration.gd
> +	jEssentials.remove_folder_recursively(editor_directory.plus_file(tracks[entry_names[0]][0].unique_name))
only removing the first one?

2022-01-11 14:24 UTC, DasCapschen commented on src/addons/jean28518.jTools/jList/jList.gd
>  export (String) var copy_button_text = "Copy"
Why are all of those texts hardcoded? Use translations?

2022-01-11 14:24 UTC, DasCapschen commented on src/addons/jean28518.jTools/jList/jList.gd
>  	$VBoxContainer/HBoxContainer/Copy.text = TranslationServer.translate(copy_button_text)
always use `tr()`, not `TranslationServer`

2022-01-11 14:24 UTC, DasCapschen commented on src/addons/jean28518.jTools/jList/jList.gd
> +	print("HUHU")
HUHU

2022-01-11 14:24 UTC, DasCapschen commented on src/addons/jean28518.jTools/jList/jList.gd
> +	print("HUHU")
HUHU

2022-01-11 14:40 UTC, HaSa1002 commented on src/Data/UI/styles/panel_background.tres
> +border_width_bottom = 4
In case there is a reason this file shouldn't be a `.theme` file but a `.tres` file becasue the latter is serialised as text.

2022-01-12 20:51 UTC, Jean28518 commented on src/Data/UI/styles/panel_background.tres
> +border_width_bottom = 4
> In case there is a reason this file shouldn't be a `.theme` file but a `.tres` file becasue the latter is serialised as text.


I generated it with the built in godot theme editor. Don't want to change this.


> Why is this in this PR? Same for `complete_menu.theme`.

It's just looking not good without it. If you want you can delete this line change and open a new PR. But for me that's not worth it..

2022-01-12 20:52 UTC, Jean28518 commented on src/Editor/Scripts/editor_configuration.gd
> +	jEssentials.remove_folder_recursively(editor_directory.plus_file(tracks[entry_names[0]][0].unique_name))
jList is accepting here only one selection.

2022-01-12 20:53 UTC, Jean28518 commented on src/addons/jean28518.jTools/jList/jList.gd
>  export (String) var copy_button_text = "Copy"
This comes from https://github.com/Jean28518/Godot-jTools.git

2022-01-12 20:54 UTC, Jean28518 commented on src/addons/jean28518.jTools/jList/jList.gd
> +	print("HUHU")
Uups, sorry we have to delete this

2022-01-16 07:36 UTC, Jean28518 commented on src/addons/jean28518.jTools/jList/jList.gd
>  	$VBoxContainer/HBoxContainer/Copy.text = TranslationServer.translate(copy_button_text)
Would fix this in my future translation PR

2022-01-16 07:42 UTC, Jean28518 commented on src/Editor/Modules/scenario_editor_selection.tscn
> +remove_confirmation_text = "Do you really want to delete these scenarios (from harddisk!)?"
Done

2022-01-16 07:43 UTC, Jean28518 commented
For me this one can now be merged

2022-01-17 11:27 UTC, HaSa1002 commented on src/Data/UI/styles/panel_background.tres
> +border_width_bottom = 4
Please **rename it in Godot** and recommit. `.theme` is a binary file and unnecessarily increases the repo size. Nothing will break because Godot knows how to handle those files.

2022-01-17 12:14 UTC, HaSa1002 requested changes
no. It can't :) Please rename `complete_menu.theme` inside Godot to `complete_menu.tres`.

2022-01-17 12:15 UTC, DasCapschen commented on src/addons/jean28518.jTools/jList/jList.gd
>  	$VBoxContainer/HBoxContainer/Copy.text = TranslationServer.translate(copy_button_text)
I'm OK with this. Make a Translation PR for these issues, so to not bloat this one.
But please also translate the jTools texts.

2022-01-20 15:24 UTC, Jean28518 commented
Done :)
Did a rebase before and fixed the some crashes which where caused by last PR-changes

2022-01-20 20:58 UTC, HaSa1002 approved these changes
lgtm

2022-01-20 21:01 UTC, merged