Add: Selection of buildings in the editor
Libre-TrainSim/Libre-TrainSim pull request #305
Opened 2022-01-09 20:15 UTC by Jean28518

Fixes #288

2022-01-11 14:19 UTC, DasCapschen requested changes

2022-01-11 14:19 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +					instance.set_script(null)
I think this would be better, in case the object already has a script.
Although, I don't really like that we're modifying script at run time at all 🤔 
```suggestion
					var old_script = instance.get_script()
					instance.set_script(preload("res://Data/Scripts/aabb_to_collider.gd"))
					instance.target = NodePath(".")
					instance.generate_collider()
					instance.set_script(old_script)
```

2022-01-11 14:19 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +	mesh_instance.set_script(null)
same as above, probably better to save a potential old script before overwriting it.

2022-01-12 20:46 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> +	mesh_instance.set_script(null)
Done!

2022-01-16 07:20 UTC, Jean28518 commented
Can we merge this one? :)

2022-01-17 12:11 UTC, merged