Address some warnings
Libre-TrainSim/Libre-TrainSim pull request #363
Opened 2022-05-14 22:24 UTC by nalquas

Godot currently throws a *lot* of warnings (far over 100 at times...).
I'm going through them and fixing some stuff I come across.

Changes include:

- Remove some unused variables
- Remove/correct some lines that have no effect
- Some variable shadowing warnings addressed
- Follow Godot conventions regarding underscores on parameters that aren't used

Not done yet.

2022-05-14 22:31 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +var train_spawn_information_template: Dictionary = {
Just as general note (not necessarily for you), these dictionaries should be converted into classes

2022-05-16 22:18 UTC, nalquas commented on src/Data/Scripts/World.gd
> +var train_spawn_information_template: Dictionary = {
Okay, I addressed this (for this specific dictionary) in 8f3bc6a3ee8408c50aed54823183f2ad4f5acbe0

2022-05-17 14:48 UTC, HaSa1002 requested changes
looking mostly good except for the one commit. Please also drop the changes in World.gd in https://github.com/Libre-TrainSim/Libre-TrainSim/commit/4ce16ce7baf99f096892c52edf64404c37cd6c4b

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +		$HUD.connect("textbox_closed", self, "_on_textbox_closed")
What has been the warning? Creating a function to only then emit is kinda unnecessary IMO

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	Root.world_origin_shifted(delta)
@DasCapschen please check this commit (https://github.com/Libre-TrainSim/Libre-TrainSim/pull/363/commits/2843dbba333b86f359929dbedc5f31071d6e878d). There was a reason for the external emit_signal.

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/UI/debug_ui.gd
> -	$DebugContainer.mouse_filter
I think this should have been `= MouseFilterIgnore` though not sure if it is still needed

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		call_deferred("_emit_thread_finished_loading")
Same here

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +		dir.list_dir_end()
I strongly disagree this being more readable. Quite the opposite. The rule here is to try to keep you code as left bound as possible.

@DasCapschen please check, too.

2022-05-17 14:48 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +		dir.list_dir_end()
Same here.

@DasCapschen please check, too.

2022-05-19 14:43 UTC, nalquas commented on src/Data/Scripts/Player.gd
> +		$HUD.connect("textbox_closed", self, "_on_textbox_closed")
Godot gave me the following warning:
```
W 0:00:31.095   The signal 'textbox_closed' is declared but never emitted.
  <C++ Error>   UNUSED_SIGNAL
  <Source>      HUD.gd:8
```
It seems Godot doesn't consider connections calling emit_signal directly into this.

2022-05-19 14:44 UTC, nalquas commented on src/Data/Scripts/chunk_manager.gd
> +		call_deferred("_emit_thread_finished_loading")
The corresponding warning message here was:
```
W 0:00:30.792   The signal '_thread_finished_loading' is declared but never emitted.
  <C++ Error>   UNUSED_SIGNAL
  <Source>      chunk_manager.gd:5
```

2022-05-19 15:12 UTC, nalquas commented on src/Data/Scripts/Singletons/Root.gd
> +		dir.list_dir_end()
> I strongly disagree this being more readable. Quite the opposite. The rule here is to try to keep you code as left bound as possible.
Makes sense. I'll push my changes shortly.

2022-05-19 15:14 UTC, nalquas commented on src/Data/Scripts/Player.gd
> +		$HUD.connect("textbox_closed", self, "_on_textbox_closed")
Yeah, seems like we're not the first to run into this. Doesn't look like it will be fixed though:
https://github.com/godotengine/godot/issues/40496

2022-05-19 15:16 UTC, nalquas commented
> Please also drop the changes in World.gd in [4ce16ce](https://github.com/Libre-TrainSim/Libre-TrainSim/commit/4ce16ce7baf99f096892c52edf64404c37cd6c4b)

Okay, I've dropped the changes to World.gd from that commit.

2022-05-19 23:12 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +		$HUD.connect("textbox_closed", self, "_on_textbox_closed")
I see. It's fine then

2022-05-19 23:13 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	Root.world_origin_shifted(delta)
I think this is fine, too

2022-05-19 23:13 UTC, HaSa1002 approved these changes
lgtm

2022-05-19 23:13 UTC, merged