Prefer queue_free() over free() where appropriate
Libre-TrainSim/Libre-TrainSim pull request #375
Opened 2022-06-29 17:06 UTC by nalquas

This pull request replaces all remaining uses of `free()` with `queue_free()`.
My reasoning behind this is that `queue_free()`, contrary to `free()`, ensures it's safe to delete a node ([according to Godot Docs](https://docs.godotengine.org/en/stable/classes/class_node.html?highlight=queue_free()#class-node-method-queue-free)), and thus should be more reliable.

Please test for side-effects.

2022-06-29 21:26 UTC, HaSa1002 requested changes
Please fix the mentioned one.
I need @DasCapschen review, too.

2022-06-29 21:26 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/content_loader.gd
> +	top_most.queue_free()
This change is wrong. We can't queue free as the node is not inside the scene tree. We just use the nodes to build our hierachy :D

2022-06-29 21:26 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +		$OverheadLine.queue_free()
those two changes feel safe. AFAIK these are only used to safe performance

2022-06-29 21:26 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +				child.queue_free()
I am unsure about that one. @DasCapschen do you know more?

2022-06-29 21:26 UTC, HaSa1002 commented on src/Editor/Docks/RailBuilder/RailBuilder.gd
> +	currentRail.queue_free()
feels safe

2022-06-29 21:26 UTC, HaSa1002 commented on src/Editor/Scripts/ScenarioConfiguration.gd
> +		child.queue_free()
feels safe

2022-06-29 21:26 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_map.gd
> +		child.queue_free()
feels safe

2022-06-29 21:26 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jTable/jTable.gd
> +		heading.queue_free()
*should* be safe

2022-06-30 19:23 UTC, DasCapschen requested changes
Looks good to me, apart from the one @HaSa1002 mentioned.

2022-06-30 19:23 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +				child.queue_free()
I think I used free() on purpose, because the chunks should unload immediately, but as I think queue_free() should work fine too.

2022-07-03 21:02 UTC, nalquas commented on src/Data/Scripts/chunk_manager.gd
> +				child.queue_free()
> I think I used free() on purpose

In that case, I'll leave it as it is, so we'll keep the `free()` here.

2022-07-03 23:08 UTC, HaSa1002 approved these changes
lgtm

2022-07-03 23:12 UTC, merged

2022-07-03 23:12 UTC, HaSa1002 commented
Thsnks. Possible candidate for 0.9