Input handling improvements
Libre-TrainSim/Libre-TrainSim pull request #376
Opened 2022-06-29 17:15 UTC by nalquas

This pull request should improve some of the input handling code.

The changes are:

- In `Player.gd`, use the provided input events where appropriate, instead of unnecessarily checking `Input.is_action_pressed`.
- In `Player.gd`, move code from the custom `handle_input()` function to `_unhandled_input()`, thus making use of events and not actively checking for Input every frame.
- Somewhat modernize the movement code in `Camera.gd`. It now uses Vectors and Input Actions instead of manually checking the keyboard keys with if statements.

2022-06-29 21:39 UTC, HaSa1002 requested changes
I don't think this change really improves the code, tbh. I do think @DasCapschen should take a look though.

2022-06-29 21:39 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +		).normalized()
FYI: https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html?highlight=Input.get_vector#which-input-singleton-method-should-i-use

2022-06-29 21:39 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +
The reason we used the input filter (and to be honest there is no shame in doing so) is that it supplies **is_action_just** methods. IMHO using the Input singleton instead of events is not an issue

2022-06-29 21:45 UTC, HaSa1002 commented
Hmm. The docs do encourage a different style: https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html?highlight=Input So I guess these changes may be fine except for the non existent echoing check. So you'll need to return early `if event.is_echo()`

2022-06-30 19:35 UTC, DasCapschen requested changes
Please check the comments.

2022-06-30 19:35 UTC, DasCapschen commented on src/Data/Scripts/Camera.gd
> +		).normalized()
can't we just do something like
`if  not Input.is_key_pressed(KEY_CONTROL): var direction = Input.get_vector(...)` ?

2022-06-30 19:35 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +	if event.is_action_pressed("debug") and not ai:
Does `is_action_pressed` actually behave the same as `is_action_*just*_pressed`? Or does `is_action_pressed` return true as long as the action is held down?

If it does not behave the same, please stick with `is_action_just_pressed`.

2022-06-30 19:35 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +	if event.is_action_pressed("acc+") and reverser == ReverserState.NEUTRAL:
same as above

2022-06-30 19:35 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> -func handle_input() -> void:
this is a good idea, thanks 😄

2022-07-04 16:40 UTC, nalquas commented on src/Data/Scripts/Player.gd
> +	if event.is_action_pressed("debug") and not ai:
As I understand it:
Since we're using the InputEvent instead of Input, `event.is_action_pressed` should only trigger when the action is first activated (like with `Input.is_action_just_pressed`). However, holding down a key would result in many presses happening (like when you're holding down a key in a text editor). We can prevent this by ensuring that `not event.is_echo()` is true, though.

2022-07-04 16:46 UTC, nalquas commented on src/Data/Scripts/Camera.gd
> +		).normalized()
> can't we just do something like `if not Input.is_key_pressed(KEY_CONTROL): var direction = Input.get_vector(...)` ?

Good idea. You wouldn't want to move while holding down CTRL anyway, so this should work pretty well / looks more clean.

2022-07-04 17:13 UTC, nalquas commented
I've further improved the Camera.gd movement rewrite, which now uses `Input.get_axis` instead of `Input.get_action_strength`.
As for the `event.is_action_pressed` vs `Input.is_action_just_pressed`, I've added a check for `event.is_echo()` to ensure that it behaves the same as before.

2022-07-04 17:41 UTC, HaSa1002 requested changes

2022-07-04 17:41 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +			)
```suggestion
			var direction := Vector3(\
				Input.get_axis("left", "right"), \
				0.0, \
				Input.get_axis("forward", "backward") \
			).normalized()
```
Please use typed variables where possible. 

FYI, not doing `.normalized()` enables players to fly faster, when the go directional.

2022-07-04 17:57 UTC, nalquas commented on src/Data/Scripts/Camera.gd
> +			)
> Please use typed variables where possible.

I didn't realize static typing was a thing in GDScript. Makes sense to use it though.
 
> FYI, not doing `.normalized()` enables players to fly faster, when going directional.

I think an advantage of *not* using `.normalized()` would be future support for analog input (e.g. analog sticks / joysticks), however I see your point. I'll re-add it.

2022-07-04 19:31 UTC, HaSa1002 commented on src/Data/Scripts/Camera.gd
> +			)
> I didn't realize static typing was a thing in GDScript. Makes sense to use it though.

👍 

> I think an advantage of not using .normalized() would be future support for analog input (e.g. analog sticks / joysticks), however I see your point. I'll re-add it.

Input,get_vector has support for that built-in. It also has a circular deadzone instead of a squared one. And btw. we already inexplicitely support controllers. Have a look at the key bindings :D

2022-07-05 12:10 UTC, nalquas commented on src/Data/Scripts/Camera.gd
> +			)
Hm, then I'll try to use `get_vector` instead. I didn't use it because it only gives us a `Vector2` and I didn't want to manually have to add another dimension to get a `Vector3`, but it's pretty trivial nonetheless.

2022-07-05 17:11 UTC, DasCapschen requested changes

2022-07-05 17:11 UTC, DasCapschen commented on src/Data/Scripts/Camera.gd
> +				self.translate(direction * deltaFlyspeed)
One more thing I've just noticed here: 
did you actually test how the camera moves now? 

Because `direction` now only depends on the input, but not on the current rotation of the camera.
While before, `get_global_transform().basis` was used to account for the current rotation of the camera.

Meaning, when pressing forward, you now wouldn't actually move forward, but along the Z axis.
Unless I've missed something. 🤔 
I believe `var direction := Vector3(...) * get_global_transform().basis` should do it.

What do you think @HaSa1002 

(unfortunately, I don't have the time to test it myself right now)

2022-07-05 17:11 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		if event.is_action_pressed("zoom_out"):
Why are those ifs nested? 🤔 
I feel like we don't need `if event.is_action_pressed("zoom_in") or event.is_action_pressed("zoom_out"):`

2022-07-05 17:56 UTC, nalquas commented on src/Data/Scripts/Camera.gd
> +				self.translate(direction * deltaFlyspeed)
The rotation is accounted for by `self.translate(...)`. It seems to work just fine for me:

https://user-images.githubusercontent.com/22664233/177387462-dfd48f68-0503-48e6-9515-f25830398054.mp4

2022-07-05 17:59 UTC, DasCapschen commented on src/Data/Scripts/Camera.gd
> +				self.translate(direction * deltaFlyspeed)
Okay, thank you for confirming that. :) 
Sorry 😅

2022-07-05 18:08 UTC, nalquas commented on src/Data/Scripts/Player.gd
> +		if event.is_action_pressed("zoom_out"):
Because lines 442-443 (which are in that if clause's block) only really need to happen when one of the zoom events happened.
https://github.com/Libre-TrainSim/Libre-TrainSim/blob/9d4bafcff6179e3bc17fc11a5b9924b44c4b8e62/src/Data/Scripts/Player.gd#L442-L443

Although before, it was just always called if `event.is_pressed()` was true and a comment in the zoom blocks stated to "call the zoom function" (which doesn't exist, therefore I assume those two lines were meant).

2022-07-05 18:13 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		if event.is_action_pressed("zoom_out"):
True, I've missed that, sorry.
Everything looks fine then :)

2022-07-05 18:14 UTC, DasCapschen approved these changes

2022-07-06 22:41 UTC, HaSa1002 requested changes
lgtm. Please clean up the history

2022-07-08 17:48 UTC, nalquas commented
> lgtm. Please clean up the history

Done.

2022-07-08 18:14 UTC, HaSa1002 approved these changes

2022-07-08 18:15 UTC, merged

2022-07-08 18:15 UTC, HaSa1002 commented
Thank you very much ❤️