Refactor configuration into window
Libre-TrainSim/Libre-TrainSim pull request #381
Opened 2022-07-31 12:52 UTC by HaSa1002

I also made some adjustments to the buttons in the top left (from now on global menu). Most importantly making the jump station button a MenuButton and putting all of these buttons into a container.

The config window is instantiated every time and saves its values when pressing save. Cancel, close, or pressing escape won't save the values.
Speaking of escape... In order to fix escape really working the way we wanna have it working, I had to refactor the menu into its own script. So that's that. I took the chance and replaced `get_parent().get_parent().save_world()` with a signal, too.

Sorry for that huge boy of a commit. I am out of practice :sweat_smile:

2022-08-01 15:30 UTC, DasCapschen requested changes
Haven't tried it, but the code mostly looks good. 
Thank you.

2022-08-01 15:30 UTC, DasCapschen commented on src/Editor/Scripts/pause_menu.gd
> +	LoadingScreen.load_main_menu()
This isn't `SaveWithoutExit`, this is `ExitWithoutSave`

2022-08-01 15:37 UTC, HaSa1002 commented on src/Editor/Scripts/pause_menu.gd
> +	LoadingScreen.load_main_menu()
uh lol. I just copied the code and that is the name Jean gave it xD

2022-08-01 21:09 UTC, HaSa1002 commented on src/Editor/Scripts/pause_menu.gd
> +	LoadingScreen.load_main_menu()
fixed

2022-08-02 08:31 UTC, DasCapschen approved these changes
lgtm

2022-08-02 08:31 UTC, merged