Draft: Add Input Settings + Revamp Settings Menu
Libre-TrainSim/Libre-TrainSim pull request #392
Opened 2022-08-21 21:24 UTC by nalquas

### Summary
This PR revamps the settings menu GUI and implements rudimentary input settings.

### Details
The following things are part of this PR:

- Adjust/expand theming (`complete_menu.tres`) slightly to work better for the settings menu
- Split the settings GUI into tabs (General, Visuals, Audio, Controls)
- Replace `CheckBox`'s with `CheckButton`'s (which, according to [Godot Docs](https://docs.godotengine.org/en/stable/classes/class_checkbutton.html#description), is the correct UX pattern to use for toggles with immediate effect)
- Add a "Reset to default" button (doesn't reset language or input settings, though)
- Implement an input remapping system and GUI which internally uses `InputMap` and `ProjectSettings`
- Ability to export and import input maps (e.g. for sharing) which saves input maps as a `Resource` on disk
- Add two input map presets: "Libre Train Sim" and "OpenBVE". The presets use the export/import system mentioned before.

The OpenBVE layout is reconstructed from information I've gathered from [this](https://sites.google.com/site/openbvesim/using-openbve/default-keyboard-controls) and [this](https://railsimroutes.net/openbve/openbve_windows10_2.php) site as well as #112.

This should close #35.

### Notes

- The input capturing actually allows adding key combinations (like `Ctrl+F`), but will simultaneously add `Ctrl`. You'd then have to press `Ctrl` again to get rid of it.
- The input capturing purposely ignores `InputMouseEvent`'s as the selection (and deselection) of the buttons is done via mouse and we don't want to lock users out accidentally.
- It should also work with gamepad/joystick/whatever inputs, although I haven't actively tested it.

I don't think this system is perfect, but I think it's an acceptable base we can expand/rework/finetune later on when the need arises.

### Screenshots / Videos

Here's some screenshots of the different tabs:
![Screenshot_20220821_230119](https://user-images.githubusercontent.com/22664233/185810962-7e146df8-ecda-444b-bb67-229e7d552695.png)
![Screenshot_20220821_230124](https://user-images.githubusercontent.com/22664233/185810966-27dbea0d-3c75-48f1-aaa7-541298373836.png)
![Screenshot_20220821_230127](https://user-images.githubusercontent.com/22664233/185810970-2e6801c6-403b-4d26-af7b-ef7291383030.png)
![Screenshot_20220821_230137](https://user-images.githubusercontent.com/22664233/185810973-90556b8a-4d43-4a1c-8cb5-0c3992e6fa85.png)

Here's a video of me adjusting some settings and applying preset layouts. You can select any input field and the GUI automatically makes sure only one is selected at a time. You can press any key to add it to the action **and** remove it again while a field is selected.

https://user-images.githubusercontent.com/22664233/185810990-6cfc2d85-1eca-4b30-ac4a-18df0dc830f3.mp4

And here's a video of the export/import system at work. I've created the presets with this system, too.

https://user-images.githubusercontent.com/22664233/185811167-ecd4f511-52fd-40c1-a4f5-0501468d3a82.mp4

2022-08-22 23:10 UTC, HaSa1002 commented
Is this PR meant to be a draft? Also, a review will follow soon (At most in two weeks)

2022-08-23 09:10 UTC, nalquas commented
> Is this PR meant to be a draft? Also, a review will follow soon (At most in two weeks)

It was, but I think it's ready for review now.

2022-08-23 18:09 UTC, DasCapschen submitted a review, later dismissed
Haven't tested it, but the code looks good.
Great feature, and I love the rework of the settings menu 👍🏻

2022-08-23 18:09 UTC, DasCapschen commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +		$"%Label7".hide()
Can we give Label7 a proper name? This is very nondescript.

2022-08-23 19:57 UTC, nalquas commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +		$"%Label7".hide()
Turns out `Label7` doesn't exist anymore. I think I renamed the node to `LabelLanguage` in a previous PR but forgot to change the code reference. Curious that Godot didn't warn me about it.

I've corrected it in 64ec9c659c3f499f3dcf3afd18185ceed02340f7.

2022-08-23 20:06 UTC, nalquas commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +		$"%Label7".hide()
Ah, seems I made the mistake in 552f6372578db1ab19b84ea61f43cf9c11534231, the first commit of *this* PR.
Thanks for the warning again

2022-08-24 21:27 UTC, DasCapschen submitted a review, later dismissed
lgtm 👍🏻

2022-09-04 19:33 UTC, HaSa1002 reviewed
just a few questions

2022-09-04 19:33 UTC, HaSa1002 commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
That was actually on purpose because it was meant to resemble a departure sign

2022-09-04 19:33 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +	$"%ResetConfirmationDialog".get_ok().text = "YES"
```suggestion
	# Localize the Reset Dialog
	$"%ResetConfirmationDialog".get_cancel().text = tr("NO")
	$"%ResetConfirmationDialog".get_ok().text = tr("YES")
```
Is the localisation done automatially?

2022-09-04 19:33 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/input_button.gd
> +	update_text()
What about making this a queue with a limited lenght?

2022-09-04 19:33 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/input_button.gd
> +			text += event.as_text()
All these inherit from InputEventWithModifiers and thus have Alt, Ctrl, Shift modifiers

2022-09-04 19:33 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/input_settings.gd
> +const path_preset_openbve = "res://addons/jean28518.jTools/jSettings/input_presets/layout_openbve.tres"
Perhaps `preload` all of that?

2022-09-04 19:34 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +	$"%ResetConfirmationDialog".get_ok().text = "YES"
Nevermind me

2022-09-04 19:41 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jSettings/input_button.gd
> +			text += event.as_text()
ignore me

2022-09-04 19:42 UTC, HaSa1002 commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
@nalquas yeah this change is definitely causing visual regression. I'd like to have that reverted

2022-09-04 19:46 UTC, HaSa1002 requested changes
looking good, apart from the one thing

2022-09-04 19:46 UTC, HaSa1002 commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
Please revert that and use an override in the settings menu. It is causing regression

2022-09-05 13:37 UTC, nalquas commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
That change was intended to fix popup menus, like the "reset" dialog. Without it, you end up having this situation:

![Screenshot_20220905_153505](https://user-images.githubusercontent.com/22664233/188461957-ee5813c0-aa3b-442c-a4e6-afcd533511ac.png)

But sure, I'll use overrides instead.

2022-09-05 13:40 UTC, nalquas commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
Actually, having another look at that, `AcceptDialog` and the like don't allow me to do theme overrides. So I think I'll have to create an additional `panel_popup_full.tres` (or something like that) and apply that to dialogs.

2022-09-05 13:47 UTC, HaSa1002 commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
Hmm. These don't look good either. What about giving them a shadow?

2022-09-05 13:57 UTC, nalquas commented on src/Data/UI/styles/panel_popup.tres
> +border_width_bottom = 4
> Hmm. These don't look good either. What about giving them a shadow?

Sure. Here's the panel with no bottom border, but with the same shadows (color `80000000`, size 1, offset y+2) as are already applied to the buttons:

![Screenshot_20220905_155604](https://user-images.githubusercontent.com/22664233/188465873-79af43b2-81d0-4251-a218-c9c5b9f7ef17.png)

2022-09-05 14:12 UTC, HaSa1002 approved these changes, later dismissed
lgtm

2022-09-05 14:15 UTC, nalquas commented
> lgtm

Sorry, forgot a minor thing. You can review now :grimacing:

2022-09-05 14:30 UTC, HaSa1002 approved these changes
lgtm

2022-09-05 14:32 UTC, merged

2022-09-05 14:46 UTC, HaSa1002 commented
Thanks ❤️