Updated Bulgarian Translation
Libre-TrainSim/Libre-TrainSim pull request #402
Opened 2022-08-28 18:02 UTC by RacerBG

2022-09-05 14:37 UTC, nalquas requested changes
Looks good to me, thanks.
However, please apply the suggested changes as the formatting of `Ingame.csv` has broken due to removing quotation marks.
Edit: I've taken the liberty to commit the changes myself.

2022-09-05 14:37 UTC, nalquas commented on src/Translations/Ingame.csv
> +TRAIN_INFO_ACCELERATION_1,"Acceleration (Apply: '%s', Release: l'%s', check doors)","Beschleunigung (Erhöhen: '%s', Verringern: '%s'; Überprüfen: Türen)",,力行 (‘%s’上矢印キー、‘%s’右矢印キー),"Gaz (przyspiesz: '
```suggestion
TRAIN_INFO_ACCELERATION_1,"Acceleration (Apply: '%s', Release: l'%s', check doors)","Beschleunigung (Erhöhen: '%s', Verringern: '%s'; Überprüfen: Türen)",,力行 (‘%s’上矢印キー、‘%s’右矢印キー),"Gaz (przyspiesz: '%s', zwolnij: '%s', sprawdż drzwi)","Прискорення (додати: ‘%s’; відпустити: ‘%s’; перевірте двері)","Aceleración (Aplicar: '%s', Liberar: l'%s', comprobar las puertas)","Ускорение (прилагане: „%s“, освобождаване: „%s“, проверете вратите)","Accélération (Appliquer : '%s', Libérer : l'%s', vérifier les portes)"
```

2022-09-05 14:37 UTC, nalquas commented on src/Translations/Ingame.csv
> +TRAIN_INFO_ENGINE,Engines ('%s'; Check: Pantograph),Motoren ('%s'; Pantograf überprüfen),,,"Silniki (""%s""; Sprawdź: Pantograf)",,Motores ('%s'; Chequea: Pantógrafo),Двигатели („%s“),Moteurs ('%s' ;
```suggestion
TRAIN_INFO_ENGINE,"Engines ('%s'; Check: Pantograph)","Motoren ('%s'; Pantograf überprüfen)",,,"Silniki (""%s""; Sprawdź: Pantograf)",,"Motores ('%s'; Chequea: Pantógrafo)","Двигатели („%s“)","Moteurs ('%s' ; Contrôle : Pantographe)"
```

2022-09-06 16:38 UTC, nalquas approved these changes
lgtm

2022-09-06 17:08 UTC, merged

2022-09-06 18:28 UTC, HaSa1002 commented
Thanks ❤️

2022-09-07 16:45 UTC, RacerBG commented
> Looks good to me, thanks. However, please apply the suggested changes as the formatting of `Ingame.csv` has broken due to removing quotation marks. Edit: I've taken the liberty to commit the changes myself.

These were automatically made by LibreOffice, sorry about that.