Work around crashes caused by Godot overriding the class_name storage
Libre-TrainSim/Libre-TrainSim pull request #405
Opened 2022-09-04 22:33 UTC by HaSa1002

If your export in compiled script mode crashes, you need to remove your
current user://overrides.cfg. THIS CHANGE IS ONLY EFFECTIVE ON SAVE!

To reiterate, this is caused because Godot simply dumps the
ProjectSettings when using save_custom. The project settings also store
the _global_script_classes that GDScript parses to find and determine
class_named scripts. On a further note: If modders choose to create new
scripts and reference them by name, it won't work because Godot is not
designed to support that because, again, these class_names are stored in
the project settings. A custom registration is needed.

2022-09-05 14:21 UTC, nalquas requested changes
Looks good, though I haven't tested it. However, this looks like it might very well require a restart of Godot (or the game) after the `override.cfg` has been edited/saved. I feel we should alert the user to restart the game here somehow.

2022-09-05 14:21 UTC, nalquas commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +					"Please ensure removal of the file!", self)
I assume you meant `threat`, not `treat`?
```suggestion
			Logger.err("Couldn't load user://override.cfg for _global_script_classes" + \
					"stripping. This is a major functionality threat! " + \
					"Please ensure removal of the file!", self)
```

2022-09-05 14:21 UTC, nalquas commented on src/addons/jean28518.jTools/jSettings/JSettings.gd
> +					"Please ensure removal of the file!", self)
Same thing here.
```suggestion
			Logger.err("Couldn't load user://override.cfg for _global_script_classes" + \
					"stripping. This is a major functionality threat! " + \
					"Please ensure removal of the file!", self)
```

2022-09-05 14:34 UTC, HaSa1002 commented
> However, this looks like it might very well require a restart of Godot (or the game) after the override.cfg has been edited/saved. I feel we should alert the user to restart the game here somehow.

Nope. The overrides.cfg is only applied on startup. The changes to the settings themselves are immediate.
We just ensure this data is not read on the next startup and thus replaces the class definitions we deliver in the pack file.

2022-09-05 14:44 UTC, HaSa1002 commented
Testable with an old overrides.cfg like this: 
[override.cfg.txt](https://github.com/Libre-TrainSim/Libre-TrainSim/files/9490661/override.cfg1.txt)
Repro:
1. Checkout #390 
2. merge this PR
3. copy and rename the provided override.cfg into the user directory
4. Export LTS

2022-09-05 18:49 UTC, DasCapschen approved these changes
lgtm

2022-09-06 08:36 UTC, nalquas approved these changes
Have tested and can confirm it works as intended.
lgtm

2022-09-06 11:29 UTC, merged