Gizmo improvements
Libre-TrainSim/Libre-TrainSim pull request #413
Opened 2022-09-14 19:26 UTC by bkeys

I made some improvements to the gizmo in the editor. But I wanted to discuss using the built-in gizmo that is available in Godot 4 (if the plan is to move over there once a stable release has been made).
Either way I am excited for you to take a look!

2022-09-14 20:54 UTC, HaSa1002 requested changes
I can't review the scene changes currently so here is just the code.

I forgot to mention the commit message style earlier. These are good, but please use imperative language. So "Add" instead of "Added" and "Pretty" instead of "Prettied". The reason being the commit message is releveant *before* the commit is applied. Meaning, you read the message as "If I apply this commit, I <commit message>". We do wanna have a capitalised first word for style, though :)

2022-09-14 20:54 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	manual_moving = true
Please set this value as default above

2022-09-14 20:54 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		  mouseMotion = mouseMotion + event.relative
```suggestion
		 	mouseMotion = mouseMotion + event.relative * (-1 if z_active else 1)
```

I don't think comments justifying changes is a good thing. Perhpas that is just me. What's definitely me is using a factor and a ternary if to reduce repition and line usage. If you don't follow that, please fix your indention issue on line 18.

2022-09-14 20:54 UTC, HaSa1002 commented on src/authors.tres
> +contributors = [ "librebob", "Bohdan Matviiv - bodamat", "Michele Comignano - comick", "Matthew - skyace65", "Yann Dirson - ydirson", "IntinteDAO", "Uli Horn - ulihorn", "simfann", "SeaMac", "Jupiter
```suggestion
contributors = [ "librebob", "Bohdan Matviiv - bodamat", "Michele Comignano - comick", "Matthew - skyace65", "Yann Dirson - ydirson", "IntinteDAO", "Uli Horn - ulihorn", "simfann", "SeaMac", "JupiterRider", "rogerm4242", "nalquas", "Brigham Keys, Esq. - bkeys" ]
```
Please use a hyphen to split real name and nick name.

2022-09-15 12:42 UTC, bkeys commented on src/Data/Scripts/Rail.gd
> +	manual_moving = true
If we set `manual_moving` to false in the `_ready()` function of the rail then it will not be visible by default. How do you recommend achieving this?

2022-09-15 12:44 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	manual_moving = true
remove the line there and set `manual_moving` to true in line 13

2022-09-15 15:13 UTC, nalquas requested changes
Please revert your changes to `src/Data/UI/styles/complete_menu.tres`, they cause theming regressions in the settings menu.

2022-09-15 15:13 UTC, nalquas commented on src/Data/UI/styles/complete_menu.tres
> +CheckButton/icons/on = null
```suggestion
CheckButton/icons/off = ExtResource( 15 )
CheckButton/icons/on = ExtResource( 4 )
```

2022-09-15 15:13 UTC, nalquas commented on src/Data/UI/styles/complete_menu.tres
>  [ext_resource path="res://Data/UI/styles/button_right_normal.tres" type="StyleBox" id=16]
```suggestion
[ext_resource path="res://Data/UI/check_button/off.png" type="Texture" id=15]
[ext_resource path="res://Data/UI/styles/button_right_normal.tres" type="StyleBox" id=16]
```

2022-09-15 15:13 UTC, nalquas commented on src/Data/UI/styles/complete_menu.tres
>  [ext_resource path="res://Data/UI/styles/line_edit_normal.tres" type="StyleBox" id=5]
```suggestion
[ext_resource path="res://Data/UI/check_button/on.png" type="Texture" id=4]
[ext_resource path="res://Data/UI/styles/line_edit_normal.tres" type="StyleBox" id=5]
```

2022-09-15 15:13 UTC, nalquas commented on src/Data/UI/styles/complete_menu.tres
> +[gd_resource type="Theme" load_steps=27 format=2]
```suggestion
[gd_resource type="Theme" load_steps=29 format=2]
```

2022-09-15 16:31 UTC, bkeys commented on src/Data/UI/styles/complete_menu.tres
> +CheckButton/icons/on = null
I never even opened that file I don't know how it somehow got edited, reverting it now.

2022-09-15 17:48 UTC, HaSa1002 requested changes
Please clean the history into two commits. One for the gizmo changes and and one adding yourself as author. Additionally, please rephrase both. If you need help, feel free to ask here or on Discord.

2022-09-15 17:48 UTC, HaSa1002 commented on src/Data/UI/styles/complete_menu.tres
> +WindowDialog/styles/panel = ExtResource( 24 )
still not reverted

2022-09-15 17:52 UTC, HaSa1002 commented
The code change is good for sure. The cylinders are a change. It definitely needs more radical changes but a proposal will follow in #166 I'd merge the changes as soon as the history is looking good :)

2022-09-23 19:17 UTC, bkeys commented
Alright I cleaned up the git history, please review at your earliest convenience.

2022-09-23 21:56 UTC, HaSa1002 approved these changes
lgtm. I just did the edit myself and removed the one line ending change.

2022-09-24 12:19 UTC, HaSa1002 commented
CC @nalquas

2022-09-24 13:18 UTC, nalquas approved these changes
lgtm

2022-09-24 14:03 UTC, merged

2022-09-24 14:04 UTC, HaSa1002 commented
Thank you very much (and) for your patience and congrats to your first merged PR 🎉