make whole rail selectable
Libre-TrainSim/Libre-TrainSim pull request #423
Opened 2022-09-16 18:06 UTC by DasCapschen

fixes #

2022-09-16 21:42 UTC, HaSa1002 requested changes
just gh review. Mostly style related topics. Also, please use an uppercase first letter in your commit message

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	var mm: MultiMesh = $MultiMeshInstance.multimesh
It's unused. What about caching `$MultiMeshInstance/Area` instead?

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	var child_count = $MultiMeshInstance/Area.get_child_count()
```suggestion
	var child_count := $MultiMeshInstance/Area.get_child_count()
```

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	var col_shape_prefab = $MultiMeshInstance/Area/CS1
```suggestion
	var col_shape_prefab := $MultiMeshInstance/Area/CS1 as CollisionShape
```

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	for i in range(2*step, length, 2*step):
```suggestion
	for i in range(2 * step, length, 2 * step):
```

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +		var col_shape = col_shape_prefab.duplicate()
```suggestion
		var col_shape := col_shape_prefab.duplicate() as CollisionShape
```

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +		var offset = col_shape_prefab.transform.origin
```suggestion
		var offset := col_shape_prefab.transform.origin
```

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +		var offset = col_shape_prefab.transform.origin
but var can also be defined out of the loop as the prefab stays the same throughout the execution

2022-09-16 21:42 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	var count = 0
```suggestion
	var positions := []
	var count := 0
```

2022-09-19 14:20 UTC, HaSa1002 requested changes
still not a tested review

2022-09-19 14:20 UTC, HaSa1002 commented on src/Data/Scripts/Rail.gd
> +	var step := int(clamp(length/100, 3, 10))
```suggestion
	var step := int(clamp(length / 100, 3, 10))
```

2022-09-20 13:40 UTC, nalquas commented
Feature seems to work as intended. The regular direction arrows are a nice touch.

However, as I tried saving in the editor (on a new map), i got the following error:
`Attempt to call function 'get_child_count' in base 'null instance' on a null instance.` with the following stack trace:
![Screenshot_20220920_153940](https://user-images.githubusercontent.com/22664233/191273072-42331bc7-6549-4cac-96ea-a4504127e8fb.png)

2022-11-25 10:47 UTC, DasCapschen commented
> Feature seems to work as intended. The regular direction arrows are a nice touch.
> 
> However, as I tried saving in the editor (on a new map), i got the following error: `Attempt to call function 'get_child_count' in base 'null instance' on a null instance.`


I cannot replicate this issue. Though your stack-trace suggests to me you are using the old chunk system. That might be the issue.

I think this is ready to be merged.

2022-11-25 11:34 UTC, nalquas approved these changes
Yup, can't reproduce that error anymore. You probably fixed it with the rebase.
lgtm

2022-11-25 14:55 UTC, HaSa1002 approved these changes
lgtm

2022-11-25 16:19 UTC, merged