Fixed some spelling and grammar in english and german
Libre-TrainSim/Libre-TrainSim pull request #429
Opened 2022-11-06 09:37 UTC by FSaurenbach

2022-11-13 07:57 UTC, HaSa1002 requested changes
Sorry for the late review and thanks for the PR. I was a little bit busy throughout the week and got stuck with one phrase. Text reviews always tend to be on the heavy end :D I didn't check the import itself, though.

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/German-Safety-Tutorials.csv
> +SIFA_TUTORIAL_3,"Do you see the ""Sifa"" text that lighted up? It shows you that you need to press the Sifa Reset button. For demonstration purposes of what will happen, don't press it and wait some
```suggestion
SIFA_TUTORIAL_3,"Do you see the ""Sifa"" text that lighted up? It requests you to press the Sifa reset button. For demonstration purposes, don't press the button and stand by.","Die 30 Sekunden wurden erreicht. Sehen Sie den leuchtenden \""Sifa\"" Schriftzug? Dieser zeigt ihnen, dass es höchste Zeit wird den Schalter zu drücken. Zu Demonstrationszwecken warten Sie noch ein paar Sekunden ab.",,,,,"Pouvez vous voir le mot ""Sifa"" qui s'est illuminé ? Cela vous informe qu'il faut appuyer sur le bouton de remise à zéro du Sifa. Pour l'exemple ne touchez à rien, et attendez encore.","¿Ve el texto “Dispositivo HM” que se ha encendido? Indica que necesita presiona el botón Reinicio Sifa. Para una demostración, no lo presione, espere un poco más."
```

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/German-Safety-Tutorials.csv
> +SIFA_TUTORIAL_7,"Congratulations, you finished the sifa tutorial!","Herzlichen Glückwunsch, Sie haben die Sifa Einweisung abgeschlossen!",,,,,"Félicitations, vous avez fini le tutoriel sur le Sifa.",
```suggestion
SIFA_TUTORIAL_7,"Congratulations! You finished the sifa tutorial!","Herzlichen Glückwunsch! Sie haben die Sifa Einweisung abgeschlossen!",,,,,"Félicitations, vous avez fini le tutoriel sur le Sifa.","¡Enhorabuena, ha terminado el tutorial de sifa!"
```

Maybe two sentences? Idk tbh.

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/German-Safety-Tutorials.csv
> +PZB_TUTORIAL_9,"The 500 Hz lamp has activated. You can not free yourself from PZB anymore. Within the next 153 meters, you need to slow down until you are below 45 km/h. The signal should then change
```suggestion
PZB_TUTORIAL_9,"The 500 Hz lamp has activated. You can not free yourself from PZB anymore. Within the next 153 meters, you need to slow below 45 km/h. If the signal changed to green, you still have to stay below 45 km/h! PZB will deactivate itself after 250 meters. If the signal stays red, come to a stop before it. Passing a red signal will result in emergency braking.","Die 500Hz Lampe wurde aktiviert. Sie können sich ab sofort nicht mehr aus der PZB Überwachung befreien. Innerhalb der nächsten 153 Meter müssen Sie Ihre Geschwindigkeit auf unter 45 km/h reduzieren. Sollte das Signal jetzt auf grün wechseln, bleiben Sie unter 45 km/h! Die PZB-Überwachung deaktiviert sich nach 250 Metern von selbst.\n\nIn diesem Fall bleibt das Signal rot, also müssen Sie vor dem Signal anhalten. Sollten Sie ein rotes Signal überfahren, erfolgt eine Zwangsbremsung.",,,,,"La lampe ""500 Hz"" s'est activée. Vous ne pouvez plus vous libérer du PZB. Dans les prochains 153 mètres, vous devrez ralentir sous 45 km/h. Si le signal devait passer au vert, restez sous 45 km/h! PZB se désactivera de lui-même après 250 mètres. Si le signal reste rouge, arrêtez vous avant. Franchir un signal rouge déclenchera un freinage d'urgence.","El indicador de 500 Hz se ha activado. Ahora ya no puede liberar el sistema PZB. En los próximos 153 metros necesita reducir por debajo de 45 km/h. Si la señal cambiara entonces a verde, manténgase por debajo de 45 km/h. PZB se desactivará automáticamente tras recorrer 250 metros. Si la señal se mantiene roja, deténgase antes de rebasarla. Rebasar una señal en rojo provocará un frenado de emergencia."
```

Two changes, I'd do (GH markup fails with the long line):
> Within the next 153 meters, you need to slow below 45 km/h.

I wasn't happy with both constructions. This very sentence is the reason the review is so late. I tried finding examples in a similiar fashion. However, [definition three](https://www.merriam-webster.com/dictionary/slow) points to down being a preposition and thus replacing it with a more appropriate one feels better to me.

> If the signal changed to green, you still have to stay below 45 km/h!

Here we need to use an if-clause. First, the statement is a general one and second, the sentence didn't work with the `the`. I'd also use a hypothetical if-caluse here as the case won't happen anyway in this specific situation.

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/German-Safety-Tutorials.csv
> +PZB_TUTORIAL_12,"PZB Monitoring was deactivated, but you are still in restrictive mode. Since the 500 Hz lamp turned off, you can go up to 45 km/h, and you can also now free yourself. But remember th
@DasCapschen is the German term "Restriktiver Modus" or "Restriktierten Modus"? Does that matter? I'd use "eingeschränkter Modus" or something more accessible.

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +EXIT_GAME,Exit game,Spiel beenden,Esci dal gioco,終了してOSに戻る,Wyjdź do Systemu,Вийти з гри,Salir al SO,Изход,Quitter vers le bureau
I am in favor of this change.

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +END_OF_YOUR_TRAIN_NOT_IN_STATION,"The end of your train hasn't reached the station yet. Please drive a bit forward, and try again.",Das Zugende hat noch nicht die hintere Bahnsteigkante erreicht. Bit
```suggestion
END_OF_YOUR_TRAIN_NOT_IN_STATION,"The end of your train hasn't reached the station yet. Please drive a bit forward, and try again.",Das Zugende hat noch nicht die hintere Bahnsteigkante erreicht. Bitte fahren Sie etwas vorwärts und halten Sie noch einmal an.,La coda del treno non ha raggiungo la banchina. Prova ad avanzare ancora.,列車の後ろがまだ駅に入っていません。もう少し前進してください。,Koniec twojego Pociągu nie jest na Stacji Podjedź Trochę Bliżej i Spróbuj ponownie,"Кінець поїзда не дістався станції. Будь ласка, під’їдьте трішки вперед, і спробуй знову.","El final del tren no ha llegado a la estación todavía. Por favor, conduce un poco hacia delante y vuelva a intentarlo.","Влакът не е спрял на перона. Моля, продължете напред и опитайте отново.",La fin de votre train n'a pas encore atteint la gare. Veuillez avancer un peu et réessayer.
```

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +FRONT_OF_YOUR_TRAIN_NOT_IN_STATION,"The front of your train is not in the station, please reverse a bit (change reverser with '%s' and '%s').","Sie sind über das Stationsende hinaus gefahren, bitte f
```suggestion
FRONT_OF_YOUR_TRAIN_NOT_IN_STATION,"The front of your train is not in the station, please reverse a bit (change reverser with '%s' and '%s').","Sie sind über das Stationsende hinaus gefahren, bitte fahren Sie zurück und halten noch einmal an (Richtung mit '%s' und '%s' wählen).",,,,,"La parte delantera de su tren no está en la estación, por favor da un poco de marcha atrás (cambia de marcha con '%s' y '%s').","Влакът не е спрял на перона. Моля, върнете се назад (сменете скоростите с „%s“ и „%s“).","L'avant de votre train n'est pas en gare, veuillez faire un peu marche arrière (changer l'inverseur avec '%s' et '%s')."
```

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +TRAIN_INFO_ACCELERATION_1,"Acceleration (Apply: '%s', Release: l'%s', check doors)","Beschleunigung (Erhöhen: '%s', Verringern: '%s'; Überprüfen: Türen)",,力行 (‘%s’上矢印キー、‘%s’右矢印キー),"Gaz (przyspiesz: '
It will require another check, but please don't arbitrarily remove quotation marks. The import may fail

2022-11-13 07:57 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +TRAIN_INFO_ENGINE,Engines ('%s'; Check: Pantograph),Motoren ('%s'; Pantograf überprüfen),,,"Silniki (""%s""; Sprawdź: Pantograf)",,Motores ('%s'; Chequea: Pantógrafo),Двигатели („%s“),Moteurs ('%s' ;
see above.

2022-11-13 07:57 UTC, HaSa1002 commented on src/project.godot
> +"base": "Reference",
That is a bug and should be reverted.

2022-11-13 08:50 UTC, FSaurenbach commented on src/Translations/German-Safety-Tutorials.csv
> +PZB_TUTORIAL_12,"PZB Monitoring was deactivated, but you are still in restrictive mode. Since the 500 Hz lamp turned off, you can go up to 45 km/h, and you can also now free yourself. But remember th
Ich werde es auf eingeschränkten Modus verändern. Das klingt auf jeden Fall besser.

2022-11-13 11:36 UTC, DasCapschen commented on src/Translations/German-Safety-Tutorials.csv
> +PZB_TUTORIAL_12,"PZB Monitoring was deactivated, but you are still in restrictive mode. Since the 500 Hz lamp turned off, you can go up to 45 km/h, and you can also now free yourself. But remember th
Bitte nicht auf "eingeschränkter Modus" ändern. Das ist Bahn-Fachsprache und nennt sich tatsächlich "restriktiver Modus"
https://tf-ausbildung.de/BahnInfo/oberezugart.htm

2022-11-13 11:37 UTC, FSaurenbach commented on src/Translations/German-Safety-Tutorials.csv
> +PZB_TUTORIAL_12,"PZB Monitoring was deactivated, but you are still in restrictive mode. Since the 500 Hz lamp turned off, you can go up to 45 km/h, and you can also now free yourself. But remember th
> Bitte nicht auf "eingeschränkter Modus" ändern. Das ist Bahn-Fachsprache und nennt sich tatsächlich "restriktiver Modus" https://tf-ausbildung.de/BahnInfo/oberezugart.htm

Ok ich reverte das

2022-11-13 11:38 UTC, DasCapschen commented on src/Translations/Ingame.csv
> +TRAIN_INFO_ACCELERATION_1,"Acceleration (Apply: '%s', Release: l'%s', check doors)","Beschleunigung (Erhöhen: '%s', Verringern: '%s'; Überprüfen: Türen)",,力行 (‘%s’上矢印キー、‘%s’右矢印キー),"Gaz (przyspiesz: '
This sometimes happens when using CSV Editors instead of editing the raw text. It should usually be fine, since the CSV editor would check if the string contains delimiters or not and then decides to place quotes around it or not.

2022-11-13 11:53 UTC, DasCapschen reviewed
Apart from the comments that @HaSa1002 has already made, this looks good to me :)
Thanks for your contribution! :+1:

2022-11-13 13:26 UTC, HaSa1002 approved these changes
lgtm. Do you wanna rebase the PR yourself or should I do it for you? I'd like to squash the commits into one and get rid of the `project.godot` changes entirely

2022-11-17 15:18 UTC, FSaurenbach commented
> lgtm. Do you wanna rebase the PR yourself or should I do it for you? I'd like to squash the commits into one and get rid of the `project.godot` changes entirely

Cant merge it myself anyway so you do it

2022-11-25 14:54 UTC, HaSa1002 commented
@FSaurenbach congrats to your first merged contribution (via #431) 🎉 and thanks for the work.

2022-11-25 14:54 UTC, closed without merging