Fix end - end rail connector
Libre-TrainSim/Libre-TrainSim pull request #436
Opened 2022-11-27 13:30 UTC by Jean28518

2022-11-28 20:14 UTC, DasCapschen requested changes

2022-11-28 20:14 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +			snap_rot = snapped_object.end_rot - deg2rad(180.0)
use `PI` instead of `deg2rad(180)`

Otherwise thanks for the fix :+1:

2022-11-29 15:33 UTC, Jean28518 commented on src/Editor/Scripts/Editor.gd
> +			snap_rot = snapped_object.end_rot - deg2rad(180.0)
Done. thanks for reviewing!

2022-11-29 15:42 UTC, DasCapschen approved these changes
lgtm

2022-11-29 15:43 UTC, merged