Fix grass and chunk not agreeing on the correct coordinate system to use
Libre-TrainSim/Libre-TrainSim pull request #452
Opened 2022-12-27 18:58 UTC by HaSa1002

... Which leads to missing grass planes.

We should add some math to the chunk itself and use that for all calculations.

Fixes #442

2022-12-29 22:13 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
1. you could've just changed the DefaultGrass in the scene? 🤔 
2. The chunk coordinates are at the chunk centre... chuck (0,0,0) should have grass in all 4 quadrants 🤔

2022-12-30 15:31 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
> you could've just changed the DefaultGrass in the scene? 🤔

Yes, however, Hainfurt and the tutorials all'd need to be resaved as the node gets saved inside the chunk.

> The chunk coordinates are at the chunk centre... chuck (0,0,0) should have grass in all 4 quadrants 🤔
No they are not. See this function: Perhpas the chunk position deciphering should have been inside the chunk. Dunno if you can actually access the class to get access to perhaps static methods.
https://github.com/Libre-TrainSim/Libre-TrainSim/blob/master/src/Data/Scripts/chunk_manager.gd#L19-L21

2023-01-01 16:03 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
`Vector3(int(position.x / chunk_size), 0, int(position.z / chunk_size))`

if `position.x` is between `-chunksize .. chunksize`, the result is 0 ; same for `position.z`

ex.: chunk size is 1000
if position = (0,0,0), chunk is (0,0,0)
if position = (600, 0, 300), chunk is (0,0,0)
if position = (-700, 0, -700), chunk is (0,0,0)

-> chunk position is the centre of the chunk

2023-01-01 16:11 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
So chunk_size is not 1000 but 2000 metres which would explain why there are missing grass planes.

2023-01-01 16:12 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
Maybe I am just super stupid right now. Idk :/

2023-01-01 16:30 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
You're onto something, the chunk position is *not* the centre... but it's very weird... I made a sketch
![grafik](https://user-images.githubusercontent.com/3923406/210177943-ccd08bac-402a-4ca3-bc46-e9f146a11670.png)

2023-01-01 16:31 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
nvm, that was wrong, lemme try again xD

2023-01-01 16:33 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
xD
The chunks overlap and that's why the issues was never apparent until you get to a corner case where it doesn't load the new chunk.

2023-01-01 16:42 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
So this is how it *should* work, this is the idea behind it:
- has no overlap
- extend of chunk in each direction is `chunk_size / 2`
- I feel like we've forgotten the `/2` part somewhere maybe? 🤔 
![grafik](https://user-images.githubusercontent.com/3923406/210178263-72a008b6-f28a-48a3-a69a-6232f52aa5b8.png)

2023-01-01 16:42 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
but... Idk what we do with that knowledge (if it is correct)

2023-01-01 16:46 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
> So this is how it _should_ work, this is the idea behind it:
> 
>     * has no overlap

This is the part I am most worried about. We likely break our maps by fixing it (and we do need to fix it). I think, it will actually work most of the time because Jean heavily used rail attachments whoose position is derived from their rail. However, the maps will not load properly, so what do we do?

>     * extend of chunk in each direction is `chunk_size / 2`
>
>     * I feel like we've forgotten the `/2` part somewhere maybe? 🤔

Yeah I agree.

2023-01-01 16:49 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
well, if we are saying that the `chunk_position` is the centre of the chunk, then it should be calculated as `chunk_position = Vector( int(position.x/chunk_size*2), 0, int(position.z/chunk_size*2) )`
🤔 

and because the grass position is `chunk_position * chunk_size`, but `chunk_position` is wrong... the grass position is wrong!
Well, for chunk (1,0,0) the grass position becomes (1000, 0, 0)
But because we forget to that the chunk position is the centre, and didn't multiply by 2, the chunk starts at 1000, not 500 ; and instead of overlap, we actually have GAPS between the chunks? 🤯 

or maybe I've got something wrong here...

2023-01-01 17:15 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
If it would work, we wouldn't have overlaps because the grass is position around (0|0|0). But because of the bug, we have gaps of 500 metres when the chunk gets generated on the fly in one direction because it is empty.

What I don't get is why we never used Vector3.snapped tbh. It would do the propper rounding.
Here's a geogebra file for visual representation:
[LTS Chunks.ggb.txt](https://github.com/Libre-TrainSim/Libre-TrainSim/files/10329138/LTS.Chunks.ggb.txt)
(you have to remove the `.txt` part... GH didn't allow me uploading the file without it...)

2023-01-01 18:08 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
Yup, exactly, that's the issue, so that's what we have to fix. Do you want to do it in this PR? And feel free to use `Vector3.snapped`. I didn't use it because I didn't know it existed... 🙈

2023-01-01 19:02 UTC, HaSa1002 commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
I am going to leave this PR open for now. Maybe I am doing it here, maybe in a new PR. I'll have to think about a migration strategy for a bit. I really hope, we can simply push the fix and be lucky that nothing will break... idk.

2023-01-01 19:12 UTC, DasCapschen commented on src/Data/Scripts/chunk.gd
> +		$DefaultGrass.translation += Vector3(500, 0, 500) # because the default grass thinks the coordinates of the chunk is in the centre point, but it is actually not.
You could try to fix it and check if any of the maps break? I'm not sure if they would... 🤔

2023-01-20 21:10 UTC, HaSa1002 commented
I think there's still something wrong with the chunks https://youtu.be/SQfjWXMiTqE

2023-01-28 16:50 UTC, DasCapschen commented
> I think there's still something wrong with the chunks https://youtu.be/SQfjWXMiTqE

Could be a Loader Problem? Maybe the interactive loader doesn't get enough time to stream in the assets?  
Are we making sure we load 2 chunks ahead, instead of just 1? That should also give enough buffer to ensure this doesn't happen 🤔 

Or is it actually the Chunk Manager not spawning in the right chunk / at the right position?

2023-01-28 16:53 UTC, HaSa1002 commented
[No, we just load one chunk ahead afaik.](https://github.com/Libre-TrainSim/Libre-TrainSim/blob/master/src/Data/Scripts/chunk_manager.gd#L112-L115) That'll fix this issue probably. The streaming itself shouldn't be an issue tbf.

2023-01-28 21:49 UTC, HaSa1002 commented
Should be working now

2023-02-04 11:59 UTC, DasCapschen requested changes
generally looks good. just a few minor comments

2023-02-04 11:59 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +	return Vector3(round(position.x / chunk_size), 0, round(position.z / chunk_size))
Didn't you want to use Vector.snapped?

2023-02-04 11:59 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +	_shift_world_origin_to(-chunk_position * chunk_size)
That's a good idea! 😄

2023-02-04 11:59 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(chunk_position, ProjectSettings["game/gameplay/chunk_unload_distance"]))
Should we really re-use `chunk_unload_distance` for loading?
Perhaps just introduce a second variable `chunk_loading_distance`?

2023-02-04 11:59 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
Shouldn't you re-order them?
If something has to be converted to the new chunk system first, and then ported to the v2 system?

2023-02-04 11:59 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +		if not (chunk in chunks):
can't you use `if chunk not in chunks` ? 🤔

2023-02-04 11:59 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +	#chunk_manager.resume_chunking()
why not resume chunking?

2023-02-04 13:11 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +	return Vector3(round(position.x / chunk_size), 0, round(position.z / chunk_size))
Because the Y coordinate has to be 0. So if I'd use snapped, I've the vector with Vector(1, 0, 1). Seemed wasted to me, tbh..

2023-02-04 13:12 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(chunk_position, ProjectSettings["game/gameplay/chunk_unload_distance"]))
Yeah probably. But with the current implementation the loading distance is one chunk less than the unloading distance which should be fine, I guess

2023-02-04 13:14 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
eh maybe. You did inverse order, too. Hence I followed xD

2023-02-04 13:24 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +		if not (chunk in chunks):
Nope

2023-02-04 13:25 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> +	#chunk_manager.resume_chunking()
Because save_world already does that

2023-02-04 13:25 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
I guess the idea was that you only convert them once?

2023-02-04 16:32 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +	return Vector3(round(position.x / chunk_size), 0, round(position.z / chunk_size))
fair enough

2023-02-04 16:33 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(chunk_position, ProjectSettings["game/gameplay/chunk_unload_distance"]))
I'd rather we just implement the extra variable. It's basically no work to do it, but we won't have to refactor stuff in the future 😅

2023-02-04 16:34 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
huh... you're right, I did it in reverse ... that was not on purpose 🙈 
we should reorder them to try and run everything in one go... if it breaks, we can do it one step at a time

2023-02-04 16:35 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
> +		if not (chunk in chunks):
okay, my bad. Been using python for too long 🙈

2023-02-04 22:15 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
Well it'll break because you don't save afaik. In all honesty, I'd like to not change that. There are maybe six maps in existence right now. Not worth the trouble.

2023-02-04 22:15 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(chunk_position, ProjectSettings["game/gameplay/chunk_unload_distance"]))
fair.

2023-02-04 22:26 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(chunk_position, ProjectSettings["game/gameplay/chunk_unload_distance"]))
fixed.

2023-02-04 22:27 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
I changed the order but prevented it from executing directly afterwards because as I said, the chunks are not yet saved and because of that the next conversion step will make it a mess

2023-02-05 15:51 UTC, DasCapschen commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(active_chunk, ProjectSettings["game/gameplay/chunk_unload_distance"]))
still using `chunk_unload_distance` :)

2023-02-05 15:51 UTC, DasCapschen commented on src/Editor/Scripts/Editor.gd
>  	_port_to_new_chunk_system()
Chunks should immediately be saved to file upon conversion... 🤔 
Anyways, not really important, like you said there's basically no maps that need it 😄

2023-02-05 15:51 UTC, DasCapschen submitted a review, later dismissed

2023-02-05 16:57 UTC, HaSa1002 commented on src/Data/Scripts/chunk_manager.gd
> +		loader.load_chunks(get_chunks(active_chunk, ProjectSettings["game/gameplay/chunk_unload_distance"]))
done.

2023-02-05 16:59 UTC, DasCapschen approved these changes
lgtm

2023-02-05 17:26 UTC, merged