UI keyboard and controller navigation
Libre-TrainSim/Libre-TrainSim pull request #481
Opened 2023-02-12 19:41 UTC by Jomosoto

Allows navigating through the UI using the keyboard or a controller in the main menu, ingame and the editor pause menus:
- Grab UI focus
- Go back on "ui_cancel" input

Bugs to fix:
- [ ] Selecting a button in the ingame pause menu while a message is open closes the message
- [ ] Controller navigation should be possible with the left stick, but `ItemList` doesn't support it

2023-02-15 13:30 UTC, HaSa1002 requested changes
That's a pure code review. I haven't tested the PR yet. Please use typed GDScript whenever possible. There's also an editor setting to use typed GDScript in code completions.
The other issue I have is setting the focus on mouse enter. I understand why you did that, but I don't feel like that's common practice. Anything else is in the review comments. I'll give it another shot once it's finished. I'll do a functionality test then.

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +func _ready():
Please use typed GDScript. There's an editor setting for autocompletion to add types by default

```suggestion
func _ready() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +func show():
```suggestion
func show() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +func _unhandled_input(event):
```suggestion
func _unhandled_input(event: InputEvent) -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
	if visible and event.is_action_pressed("ui_cancel"):
```

Please check properties first, especially if they're bools before calling methods

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
What about caching the item list and other UI controls?

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +		get_tree().set_input_as_handled()
Just FYI, you may get away with [`accept_event()`](https://docs.godotengine.org/en/stable/classes/class_control.html?highlight=Control#class-control-method-accept-event)

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +func _on_ItemList_item_activated(index):
```suggestion
func _on_ItemList_item_activated(index: int) -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/Content.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	$CreateMenu/ScenarioEditor.connect("mouse_entered", self, "createMenu_focus_button", ["ScenarioEditor"])
Please don't. Focus should only set by mice when pressing the button. That's the default behaviour.
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	$Buttons.get_node(name).grab_focus()
```suggestion
func focus_button(button: Button):
	button.grab_focus()
```

Use a node reference instead. It won't break the same way strings do.

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	if event.is_action_pressed("ui_cancel") and $CreateMenu.visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if $CreateMenu.visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	$CreateMenu.get_node(button_name).grab_focus()
note needed with change above.
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	if $CreateMenu.visible:
```suggestion
func _on_CreateMenu_visibility_changed() -> void:
	if $CreateMenu.visible:
```
What about caching create menu?

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/menu_about.gd
> +func show():
```suggestion
func show() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/menu_about.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	$CenterContainer/HBox/QuitOS.connect("mouse_entered", self, "focus_button", ["QuitOS"])
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +func show():
```suggestion
func show() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	if Input.is_action_just_pressed("pause") and not jSettings.get_node("JSettings").visible:
Can't you ask `jSettings` for its visible state?

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	if Input.is_action_just_released("ui_accept") and visible:
```suggestion
	if visible and Input.is_action_just_released("ui_accept"):
		# Prevent "ui_accept" event from closing a potential message behind the menu
```
Personal preference: I'd move comments describing a block into the block.

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	$CenterContainer/HBox.get_node(button_name).grab_focus()
```suggestion
func focus_button(button: Button) -> void:
	button.grab_focus()
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +func _ready():
```suggestion
func _ready() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +func _on_menu_visibility_changed():
```suggestion
func _on_menu_visibility_changed() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Data/UI/styles/button_both_focus.tres
> +border_color = Color( 0.164706, 0.6, 0.819608, 1 )
What's that? Wasn't the focus distinguishable enough?

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Modules/scenario_editor_selection.tscn
> -select_mode = 1
That's the track selection in the scenario editor menu, right?

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/editor_configuration.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/pause_menu.gd
> +	$VBoxContainer/SaveAndExit.connect("mouse_entered", self, "_on_button_mouse_entered", ["SaveAndExit"])
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/pause_menu.gd
> +	$VBoxContainer.get_node(button_name).grab_focus();
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
> +
```suggestion
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor_selection.gd
> +	if event.is_action_pressed("ui_cancel") and visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if visible and event.is_action_pressed("ui_cancel"):
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor_selection.gd
> +func show():
```suggestion
func show() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor_selection.gd
> +func _ready():
```suggestion
func _ready() -> void:
```

2023-02-15 13:30 UTC, HaSa1002 commented on src/addons/jean28518.jTools/jList/jList.gd
> +	if Input.is_action_just_pressed("ui_cancel") and $ConfirmationDialog.visible:
```suggestion
func _unhandled_input(event: InputEvent) -> void:
	if $ConfirmationDialog.visible and Input.is_action_just_pressed("ui_cancel"):
```

2023-02-15 13:55 UTC, Jomosoto commented on src/Editor/Modules/scenario_editor_selection.tscn
> -select_mode = 1
Yes, it was set to muti select so you can't move the selection by going up and down

2023-02-15 14:39 UTC, Jomosoto commented on src/Data/Scripts/StationJumper.gd
What do you mean by caching?

2023-02-15 14:50 UTC, Jomosoto commented
> The other issue I have is setting the focus on mouse enter. I understand why you did that, but I don't feel like that's common practice

I thought this is better for non-keyboard users, because otherwise there would be two highlighted buttons in every menu.

2023-02-15 21:33 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
onready var node: ControlWhatEver = $What/Ever/Control

2023-02-15 21:34 UTC, HaSa1002 commented
Hmm. I see. I'd argue, we'd better hide the mouse and prevent hovered states that way?

2023-02-17 05:58 UTC, Jomosoto commented
Sorry, I mean for those who use the mouse, there's always another item focused.

2023-02-17 12:54 UTC, HaSa1002 commented
Yeah but that's how every other UI works across all OS'

2023-02-17 14:20 UTC, Jomosoto commented on src/Data/UI/main_menu.gd
> +	$Feedback.connect("popup_hide", self, "focus_button", ["Play"])
```suggestion
	$Feedback.connect("popup_hide", $Buttons/Play, "grab_focus")
```
Is this better?

2023-02-17 15:14 UTC, HaSa1002 commented on src/Data/UI/main_menu.gd
> +	$Feedback.connect("popup_hide", self, "focus_button", ["Play"])
That's an option, too 😅

2023-02-18 16:51 UTC, Jomosoto commented on src/Data/UI/pause.gd
> +	if Input.is_action_just_pressed("pause") and not jSettings.get_node("JSettings").visible:
jSettings is always visible, only the visibility of jSettings/JSettings is changed.

2023-02-18 17:00 UTC, Jomosoto commented on src/Data/UI/styles/button_both_focus.tres
> +border_color = Color( 0.164706, 0.6, 0.819608, 1 )
No, there was just a small blue line around the button

2023-02-18 17:14 UTC, Jomosoto commented
I'll fixup the commits called "Fixup" into the corresponding commits before merging. It's almost done, I just have to do the caching.

2023-02-20 18:57 UTC, HaSa1002 reviewed
code review done. I'll continue with a test later this evening or tomorrow

2023-02-20 18:57 UTC, HaSa1002 commented on src/Data/Scripts/StationJumper.gd
> +onready var itemList: ItemList = $StationJumper/ItemList
For the future, use snake_case for node references. [See the offical style guide.](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#functions-and-variables) I am not going to make that a blocker though. So fix if you like.

2023-02-20 18:57 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	if visible and not settings.visible and (Input.is_action_just_pressed("pause") or Input.is_action_just_pressed("ui_cancel")):
```suggestion
	if visible and not settings.visible and \
			(Input.is_action_just_pressed("pause") \
			or Input.is_action_just_pressed("ui_cancel")):
```

FYI, you can add line breaks with the backslash to limit the line length.

2023-02-21 16:17 UTC, HaSa1002 requested changes
Please change the controller inputs to "All Devices". That's because the device handling is sadly a bit bad here when having multiple controller connected. I am going through alle the menus I can find now

2023-02-21 16:29 UTC, HaSa1002 requested changes
Here's a quick test review:
- [ ] You can't move through the tabs in the settings
- [ ] You can't scroll (may need an autoscroll)
- [ ] Dunno if because of stick and list views but you there are two items focused in the play menu and the stick just ignores the list view
- [ ] The start message button is not focused (A/Enter will work anyway because of the custom code there)
- [ ] Btw. we can't close doors on a controller 🤣  (not your bug)
- [ ] Pressing the menu button sometimes closes the pause menu immediately again
- [ ] Pressing Back (B) ingame while in some menu also closes the pause menu

2023-03-02 11:02 UTC, Jomosoto commented
> You can't move through the tabs in the settings

Done, I just have to add controler icons. I took L1 and R1 to switch between tabs on controller and Page up and Page down on keyboard. (I wanted to take ctrl + left/right, but when focused the sliders steal the left/right input even if there are modifiers like ctrl. This is changed in Godot 4 if I remember correctly). Maybe I would only show the icons on controller, to not disturb mouse users(?). Is this fine in all?

> You can't scroll (may need an autoscroll)

> The start message button is not focused (A/Enter will work anyway because of the custom code there)

Done (locally)

> Dunno if because of stick and list views but you there are two items focused in the play menu and the stick just ignores the list view

I'm not sure what you mean. Because of the bug you can't change the selection in the ItemLists, but it's possible to focus the item list. I couldn't find where two items are focused; can you please send a screenshot?

> Pressing the menu button sometimes closes the pause menu immediately again

I couldn't reproduce. Can you please try in what conditions this happens or look why this happens?

> Pressing Back (B) ingame while in some menu also closes the pause menu

Hm, I can't reproduce. Do you mean pressing B while for example in the station jumper menu? For me this just closes the station jumper.

2023-03-03 00:23 UTC, HaSa1002 commented
> Maybe I would only show the icons on controller, to not disturb mouse users(?). Is this fine in all?

If you feel like adding Icons, go ahead but it's not gonna be an easy task. Could be done in a later PR.

> I'm not sure what you mean. Because of the bug you can't change the selection in the ItemLists, but it's possible to focus the item list. I couldn't find where two items are focused; can you please send a screenshot?

You can't move the focus with the left stick in the list. But not too much of an issue. Looks like a Godot issue to me.


> >Pressing the menu button sometimes closes the pause menu immediately again
>
> I couldn't reproduce. Can you please try in what conditions this happens or look why this happens?
> > Pressing Back (B) ingame while in some menu also closes the pause menu
>
> Hm, I can't reproduce. Do you mean pressing B while for example in the station jumper menu? For me this just closes the station jumper.

Yeah can't repro either. So seems to be not an issue anymore.

2023-03-03 00:28 UTC, HaSa1002 approved these changes, later dismissed
lgtm

2023-03-03 00:29 UTC, HaSa1002 commented
I'll leave that unmerged for now. Tell me if you wanna continue here with the icons, but I'd merge without them. I think this PR is a great improvement and one of the last steps towards another beta.

2023-03-03 07:40 UTC, Jomosoto commented
Thanks. I just have to fix the problem, that you can't see if a check_button is focused. I'll do the icons in a later PR.

2023-03-03 23:28 UTC, HaSa1002 approved these changes
lgtm

2023-03-03 23:30 UTC, merged

2023-03-03 23:30 UTC, HaSa1002 commented
Thank you very much ❤️