Optimise Pathfinding
Libre-TrainSim/Libre-TrainSim pull request #507
Opened 2023-03-22 15:34 UTC by HaSa1002

I implemented a propper A* pathfinding that searches in the direction of the target. I also prevented a few crashes that happen when you add new stations and auto update mode is enabled.

I couldn't edit Hainfurt at all. With the new pathfinding it's almost instant.

2023-03-22 15:42 UTC, DasCapschen submitted a review, later dismissed
untested, but lgtm 👍🏻

2023-03-22 15:42 UTC, DasCapschen commented on src/Data/Scripts/World.gd
> +			if explored[rail][0] + adjacent.length < reachable[adjacent][0]:
shouldn't this be an `else if` ?
Because if the we saw the node first time, we already set all these values and don't need to check again :)

2023-03-22 15:44 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +			if explored[rail][0] + adjacent.length < reachable[adjacent][0]:
Good point. Added a continue in the previous if

2023-03-22 21:54 UTC, DasCapschen requested changes

2023-03-22 21:54 UTC, DasCapschen commented on src/Data/Scripts/World.gd
> +		rail = explored[rail][1]
You are not appending the start rail!

Example:
```gdscript
rail = end_rail
explored = { 
    end_rail=start_rail, 
    start_rail=null 
}

# iteration 1
while explored[rail]: # explored[end_rail] = start_rail ; True
    path.append(rail)
    rail = explored[rail]

# iteration 2
while explored[rail]: # explored[start_rail] = null ; False
    pass # do nothing

# MISSING:
path.append(rail)

path.invert()
return path  # path = [end_rail]
```

You can also **see** this in the scenario editor:
![grafik](https://user-images.githubusercontent.com/3923406/227047235-4d50acbe-553a-488f-9c09-579ce896d167.png)
(green arrow (start) is on a dark blue rail (not part of the path) ; first greenish rail (part of the path) is the one after)

2023-03-23 14:02 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +		rail = explored[rail][1]
true

2023-03-26 11:33 UTC, DasCapschen approved these changes
code lgtm

tested, pretty fast, seems to work

2023-03-26 11:33 UTC, merged

2023-03-26 11:33 UTC, DasCapschen commented
Thank you ❤️