Gizmo upgrade
Libre-TrainSim/Libre-TrainSim pull request #519
Opened 2023-07-23 20:42 UTC by Jomosoto

Fixes parts of #166 

# Summary

- Change the model to a conventional style
- Make the movement axes draggable
- Add rotation for all axes
- Fix a bug, where you can't interact with the gizmo when it's inside of objects

---

# Movement

The difference to the start position is calculated by using the law of sines on the triangle between the origin of the camera, the position where the gizmo is grabbed:

<img width="953" alt="grafik" src="https://github.com/Libre-TrainSim/Libre-TrainSim/assets/40580158/fc8d2c13-f7b8-46db-aae0-7c3ef1c48f7c">

This is the best approach I found, however this is pretty long in code and I feel like there must be something shorter. Please tell me if you know a better approach.

# Rotation

For the rotation, the player circles with the mouse pointer around the object, like in the the godot editor.

The angle to rotate is calculated like this:

<img width="958" alt="grafik" src="https://github.com/Libre-TrainSim/Libre-TrainSim/assets/40580158/5f705ed7-9fb0-4872-8416-7aa8b33005fc">

--- 

To fix the bug, where you couldn't interact with the gizmo when it's inside of objects I moved the interaction to physic layer 2.

2023-07-23 21:25 UTC, HaSa1002 commented
Nice. I am gonna check out your work hopefully tomorrow. I haven't yet looked into your code in depth but it didn't seem overly verbose. But you couldn't project the cursor into the world? Anyway, I am too tired this evening

2023-07-24 10:18 UTC, HaSa1002 requested changes
Gizmo is looking good, behaving as expected. Just some typing stuff and exporting the gizmo colours as variables. Your code is fine. We are dealing with 2d to 3d projection after all and it's not that long. Not at all, in fact. Nobody said the "easy" stuff is easy and short :>

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Modules/Gizmo.tscn
> +data = PoolVector3Array( 1.9358, 0, 19.6549, 0, 0, 19.75, 1.8258, 1.5455, 18.5375, 1.8258, 1.5455, 18.5375, 0, 0, 19.75, 0, 1.5455, 18.6272, 1.8258, 1.5455, 18.5375, 0, 1.5455, 18.6272, 1.6477, 0.955
Oh nice. Serialised vector data xD

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/EditorHUD.gd
> +
Please type these values as float

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +	if event is InputEventMouseMotion and (x_active or y_active or z_active):
```suggestion
	var mm := event as InputEventMouseMotion
	if mm != null and (x_active or y_active or z_active):
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var direction = Vector3(1 if x_active else 0, 1 if y_active else 0, 1 if z_active else 0)
```suggestion
		var direction := Vector3(x_active, y_active, z_active)
```

Conversion bool to float can be implicit

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var direction_on_screen = (camera.unproject_position(grab_position + direction) - grab_position_on_screen).normalized()
```suggestion
		var camera := get_viewport().get_camera()
		
		var grab_position_on_screen := camera.unproject_position(grab_position)
		var direction_on_screen := (camera.unproject_position(grab_position + direction) - grab_position_on_screen).normalized()
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		if (event.position - grab_position_on_screen).dot(direction_on_screen) < 0:
```suggestion
		if (mm.position - grab_position_on_screen).dot(direction_on_screen) < 0:
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var cam_to_new_position = camera.project_ray_normal(perpendicular_screen_point)
```suggestion
		var perpendicular_screen_point := (mm.position - grab_position_on_screen).dot(direction_on_screen) * direction_on_screen + grab_position_on_screen;
		
		var cam_to_grab_position := grab_position - camera.global_transform.origin
		var cam_to_new_position := camera.project_ray_normal(perpendicular_screen_point)
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var angle_cam_object_new = PI - cam_to_grab_position.angle_to(direction)
```suggestion
		var angle_grab_cam_new := cam_to_grab_position.angle_to(cam_to_new_position)
		# The angle at the object between the vectors to the camera and the new position
		var angle_cam_object_new := PI - cam_to_grab_position.angle_to(direction)
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var diff = cam_to_grab_position.length() \
```suggestion
		var diff := cam_to_grab_position.length() \
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +	elif event is InputEventMouseMotion and (x_rot_active or y_rot_active or z_rot_active):
```suggestion
	elif mm != null and (x_rot_active or y_rot_active or z_rot_active):
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +		var intersection_new = plane.intersects_ray(camera.translation, ray_new_mouse_position)
```suggestion
		var camera := get_viewport().get_camera()
		
		var axis := \
			Vector3(1, 0, 0) if x_rot_active else \
			Vector3(0, 1, 0) if y_rot_active else \
			Vector3(0, 0, 1)
		
		var plane := Plane(axis, get_parent().translation.dot(axis))
		
		var ray_old_mouse_position := camera.project_ray_normal(event.position - event.relative)
		var ray_new_mouse_position := camera.project_ray_normal(event.position)
		
		var intersection_old := plane.intersects_ray(camera.translation, ray_old_mouse_position)
		var intersection_new := plane.intersects_ray(camera.translation, ray_new_mouse_position)
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +			var diff = (intersection_old - get_parent().translation).signed_angle_to(intersection_new - get_parent().translation, axis)
```suggestion
			var diff := (intersection_old - get_parent().translation).signed_angle_to(intersection_new - get_parent().translation, axis)
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +	elif event is InputEventMouseMotion and not any_axis_active():
```suggestion
	elif mm != null and not any_axis_active():
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +					$"z-rot/MeshInstance".get_surface_material(0).emission = Color(0.5, 0.5, 1)
Please create export vars for these colours :>

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +	return space_state.intersect_ray(from, to, [  ], 0b10)
```suggestion
	var camera := get_viewport().get_camera()
	
	var ray_length := 1000
	var mouse_pos := get_viewport().get_mouse_position()
	var from := camera.project_ray_origin(mouse_pos)
	var to := from + camera.project_ray_normal(mouse_pos) * ray_length
	
	var space_state := get_world().get_direct_space_state()
	return space_state.intersect_ray(from, to, [ ], 0b10)
```

2023-07-24 10:18 UTC, HaSa1002 commented on src/Editor/Scripts/Gizmo.gd
> +	$"z-rot/MeshInstance".get_surface_material(0).emission = Color(0, 0, 1)
Colours as export vars, please

2023-07-28 20:30 UTC, Jomosoto commented
👍 Thanks for the review and sorry for my late reply. I'm not at home for the next two weeks, but I'll do the changes right when I'm back.

2023-07-29 08:55 UTC, HaSa1002 commented
> 👍 Thanks for the review and sorry for my late reply. I'm not at home for the next two weeks, but I'll do the changes right when I'm back.

Have great holidays

2023-08-17 09:31 UTC, Jomosoto commented on src/Editor/Modules/Gizmo.tscn
> +data = PoolVector3Array( 1.9358, 0, 19.6549, 0, 0, 19.75, 1.8258, 1.5455, 18.5375, 1.8258, 1.5455, 18.5375, 0, 0, 19.75, 0, 1.5455, 18.6272, 1.8258, 1.5455, 18.5375, 0, 1.5455, 18.6272, 1.6477, 0.955
Yeah, I imported a bigger shape for the rotation circle hitbox, generated the collider and deleted the shape. Is this ok?

2023-08-17 09:48 UTC, HaSa1002 commented on src/Editor/Modules/Gizmo.tscn
> +data = PoolVector3Array( 1.9358, 0, 19.6549, 0, 0, 19.75, 1.8258, 1.5455, 18.5375, 1.8258, 1.5455, 18.5375, 0, 0, 19.75, 0, 1.5455, 18.6272, 1.8258, 1.5455, 18.5375, 0, 1.5455, 18.6272, 1.6477, 0.955
You can try saving the shape to disk but, yeah that's fine

2023-08-17 13:14 UTC, Jomosoto commented on src/Editor/Modules/Gizmo.tscn
> +data = PoolVector3Array( 1.9358, 0, 19.6549, 0, 0, 19.75, 1.8258, 1.5455, 18.5375, 1.8258, 1.5455, 18.5375, 0, 0, 19.75, 0, 1.5455, 18.6272, 1.8258, 1.5455, 18.5375, 0, 1.5455, 18.6272, 1.6477, 0.955
I saved it to disk :+1:. I wasn't sure where to save it. I put it next the scene and script files.

2023-08-17 13:34 UTC, HaSa1002 approved these changes
lgtm

2023-08-17 14:51 UTC, merged

2023-08-17 14:52 UTC, HaSa1002 commented
Thanks ❤️