Feature/persons fsm and navigation update. Issue #506. Fixes #490
Libre-TrainSim/Libre-TrainSim pull request #529
Opened 2023-08-19 03:40 UTC by custodian

Related to #506
Fixes #490 

This Pull request requires ( built on top of new Door States system PR https://github.com/Libre-TrainSim/Libre-TrainSim/pull/528 )
To simplify review changes related to persons navigation only, I have opened draft pull request to Doors branch https://github.com/custodian/Libre-TrainSim/pull/1/files

This PR also includes a few fixes required:
88f74cd70ce8a0f27d95b6d6d77bac01c3f5fbf3 - Player and Wagon might be out of sync on world shifts and `process()` calls
067814b2052d32e8aeca60cd8dc61448d09f8a35 - Dedicated plugin to draw 2d labels - used for Passengers Debug UI

7cdcdf031f99d33c077eb4775fda1f728128a1be - Not essential, but camera related and fixes issue with camera being drugged in Free Cursor mode.

2023-08-19 17:18 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
I assume it messed with the start? Because I don't think it's that much of an issue tbh. They're updated every frame after all

2023-08-19 17:55 UTC, HaSa1002 requested changes
untested eye only review. Dunno if helpful

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
I assume it messed with the start? Because I don't think it's that much of an issue tbh. They're updated every frame after all

2023-08-19 17:55 UTC, HaSa1002 commented on src/addons/basil.debug_labels/debug_label.gd
> +# Debug labels to output debug information on top of objects
Doc Comments are `##`

2023-08-19 17:55 UTC, HaSa1002 commented on src/addons/basil.debug_labels/debug_label.gd
> +	owner = mount_point
Why do you set an owner here? I'd avoid that tbh unless you want the label to be saved

2023-08-19 17:55 UTC, HaSa1002 commented on src/addons/basil.debug_labels/debug_label.gd
> +
Remove in this commit perhaps?

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +export (float) var _walking_speed: float = 1.5
Well. I'd argue exported variables are public 😅

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +			_destination_path[i] += delta
This callback is starting to get expensive. But okay. Let's roll with it and optimise if needed

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +				if not board_assigned_wagon():
Oh please go to your editor settings and enable strip whitespace

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +				.move_toward(_destination_path[0], delta*_walking_speed)
Please use a space around ops https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +func leave_current_wagon() -> bool:
I can't imagine a case when we would

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +var leave_current_station_announced: bool = false # to prevent depature re-announcement till train is refactored with a state
What a state? I thought stateless is modern 🙃

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +	assert(station_node != null)
You maybe wanna check using is_instance_valid

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +var attachedPersons := {} # Person -> occupied seat reference
underscore case

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +		route[route.size()-1].z -= 1.3
Does that break with different trains? Like, that is setting some hard facts how wide the trains are, right?

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +		_debug_passenger_state_label.set_text( "W:%d\nPassenger: %d / %d" % [get_instance_id(), attachedPersons.size(), total_seats])
One empty line pls

2023-08-19 17:55 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	person.owner = self
Not needed as they shouldn't be saved

2023-08-19 18:14 UTC, custodian commented on src/addons/basil.debug_labels/debug_label.gd
> +
This has been already removed, not sure why this popped up, let me check on this one

2023-08-19 18:14 UTC, custodian commented on src/Data/Scripts/Person.gd
> +export (float) var _walking_speed: float = 1.5
My bad, yes

2023-08-19 18:16 UTC, custodian commented on src/addons/basil.debug_labels/debug_label.gd
> +	owner = mount_point
No intention to save the label, just to make sure destruction occurs whenever owner destroyed, since that's a plugin

2023-08-19 18:19 UTC, custodian commented on src/Data/Scripts/Wagon.gd
> +		route[route.size()-1].z -= 1.3
That's the way how it was before those states, proper way would be introducing those shifts within `PassengerDoor`/or train.
Left it as is for now, might be marked as TODO: 
I haven't finished my first train yet, so I don't quite understand what are the pros and cons in terms of support for this one

2023-08-19 18:21 UTC, custodian commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
Wagons are updated, yes, but if you spawn at the station, and people decide to board, they will receive an invalid route from the station to the door, as rail, station and wagon already spawned and placed, world has been shifted, and that shift moved player, station and persons but not wagons, so first destination point in the path is far far away from the station (initial world shift delta).

We can of course make a sanity check for the destination distance at Person class (i.e. distance/destination should be within station bounds), but this looks like an workaround rather a proper system functioning.

2023-08-19 18:23 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
Hmm. I thought the drive(0) in initialize sets the transform. That's why I am asking

2023-08-19 18:25 UTC, HaSa1002 commented on src/addons/basil.debug_labels/debug_label.gd
> +	owner = mount_point
Destruction is not by owner but by tree. So when it is in the tree and the parent is deleted so are also the children. Owner have nothing to with that afaik

2023-08-19 18:25 UTC, custodian commented on src/Data/Scripts/World.gd
> +	person.owner = self
Didn't know it might affect `PackedScene`

2023-08-19 18:25 UTC, HaSa1002 commented on src/addons/basil.debug_labels/debug_label.gd
> +
It's removed in the next commit

2023-08-19 18:25 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +		route[route.size()-1].z -= 1.3
Is fine. Was a general remark

2023-08-19 18:26 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	person.owner = self
Well only if they are saved

2023-08-19 18:40 UTC, custodian commented on src/addons/basil.debug_labels/debug_label.gd
> +
I'll amend commits to be clean

2023-08-19 21:07 UTC, TrojanerHD reviewed
Didn't extensively test the changes but I have got some remarks mostly about naming schemes

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Station.gd
> +	_debug_passanger_state()
```suggestion
	_debug_passenger_state()
```
Small typo ^^

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Person.gd
> +		Destination.SEAT, Destination.DOOR_INSIDE:
Did you consider adding `SEAT_IDLE` here? Although you don't need it in your case, I imagine if this function might get re-used in other contexts it could lead to confusion if that's not included here

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Person.gd
> +func leave_current_wagon() -> bool:
Maybe rename to `can_leave_current_wagon`? It confused me a bit when reading the code that this function does not actually set `_destination` e. g.

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Player.gd
> +var _station_doors_wagons: Array = []
```suggestion
var _station_doors := []
var _station_doors_wagons := []
```

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Person.gd
> +			if global_transform.origin.distance_to(_destination_path[0]) < _destination_tolerance:
Really nitpicky and I'm only remarking this because you did it elsewhere that way too:
```suggestion
		elif global_transform.origin.distance_to(_destination_path[0]) < _destination_tolerance:
```

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Station.gd
> +	return [get_random_transform_at_platform().origin]
As of now, this function doesn't need to return an array but can instead return the Vector3 directly

2023-08-19 21:07 UTC, TrojanerHD commented on src/Data/Scripts/Wagon.gd
> +func get_random_free_seat_index() -> Spatial:
```suggestion
func get_random_free_seat() -> Spatial:
```
This actually returns the seat itself, not the index

2023-08-19 21:17 UTC, custodian commented on src/Data/Scripts/Person.gd
> +func leave_current_wagon() -> bool:
may be `try_leave_current_wagon`? and same for `board_assigned_wagon` -> `try_board_assigned_wagon`?

2023-08-19 21:22 UTC, custodian commented on src/Data/Scripts/Station.gd
> +	return [get_random_transform_at_platform().origin]
While we do not have multiple points right now, path might be more complex in the future.
I would insist on having same return type for all navigation related functions, i.e. if you receive destination, you know it's a path.

2023-08-19 21:23 UTC, custodian commented on src/Data/Scripts/Wagon.gd
> +func get_random_free_seat_index() -> Spatial:
yep, a left over after cleanup

2023-08-19 22:25 UTC, custodian commented on src/Data/Scripts/Person.gd
> +			_destination_path[i] += delta
We can move it one level up to the station, where we will have 1 connection for all affected station passengers (as persons on the trains are not affected anyway.

2023-08-19 22:31 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +			_destination_path[i] += delta
Yeah the world origin shift is a prima candidate for optimisation. I mean, deferring the execution of these things over multiple frames is probably enough and fine.

2023-08-19 22:35 UTC, custodian commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
At the time of `initialize` and first call to `drive(0)` and `set_transform_on_rail` world shift is set to loaded from map/scenario value, and later is shifted once again to camera position (to route start point) and that's where it desyncs

We can also make this connection `CONNECT_ONESHOT` since it is required only once after spawn (at least for now till we get AI trains and peek function, which might highlight more issues)

2023-08-19 22:41 UTC, custodian commented on src/Data/Scripts/Player.gd
> +	assert(station_node != null)
I would prefer an assert here, as if we have something within `station_table` but it does not have proper signal meta info - something gone completely wrong after `get_calculated_station_points` (scenario start) and before arrival to the station.

But I guess we can actually use `current_station_node` right away. Not sure why I choose to go with `get_signal` in the first place

2023-08-19 22:46 UTC, custodian commented on src/Data/Scripts/Person.gd
> +		Destination.SEAT, Destination.DOOR_INSIDE:
Yep, it should be added here!

Technically, `SEAT_IDLE` and `STATION_IDLE` are not required as separate states for proper navigation and states handling. 

I decided to explicitly add those to highlight that Person might have some other stuff to do while traveling within the wagon (i.e. animated chat/yawn animations from time to time, or even toiler trip), or at the station (i.e. not just walk around but take a sit at the bench, checkout some vending machines/etc.

2023-08-19 22:50 UTC, HaSa1002 commented on src/Data/Scripts/Wagon.gd
> +	Root.connect("world_origin_shifted", self, "_on_world_origin_shifted")
Yeah, I'd favor that solution, with a TODO maybe

2023-08-19 22:52 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +	assert(station_node != null)
Oh wait. I mean inside the assert. The null check will fail on freed objects that we still point to...
```suggestion
	assert(is_instance_valid(station_node))
```

2023-08-20 00:05 UTC, HaSa1002 requested changes
Test:
Verified with grey and red train in Tutorial. Working fine except noted comments.
I always get a you departed early yelling message even departing on time and way too late

2023-08-20 00:05 UTC, HaSa1002 commented on src/Data/Scripts/World.gd
> +	person.owner = self
```suggestion
```
Causes owner invalid error

2023-08-20 09:55 UTC, custodian commented on src/Data/Scripts/Person.gd
> +			if global_transform.origin.distance_to(_destination_path[0]) < _destination_tolerance:
I explicitly using `else: if` to high expressions leading to the statement, so it it will be not miss-interpreted as a precondition if you ever need to refactor or add more branches:

Imagine the following:
```
if A:
  if B:
    do_first()
else:
  if C:
    do_second()
do_overwise()
```
We can do an equivalent of:
```
if A and B:
  do_first
elif C:
  do_second()
do_overwise()
```
But it leads to a false impression that `A and not B` state should lead to `C` check, i.e. `A`, `not B` and `C` state combination should lead to `do_second`, while in fact check on `C` shall only depend on `not A`. 
To highlight this fact using `elif` it should be like
```
if A and B:
  do_first
elif not A and C:
  do_second()
do_overwise()
```
And this is tends to be less readable to assess all branches

2023-08-20 10:37 UTC, custodian commented on src/Data/Scripts/Person.gd
> +			if global_transform.origin.distance_to(_destination_path[0]) < _destination_tolerance:
What do you think of this one?
```
func _is_destination_reached() -> bool:
	if not _destination_path.empty():
		var current_pos = translation if _is_destination_train_bound() else global_transform.origin
		return current_pos.distance_to(_destination_path[0]) < _destination_tolerance
	return false
```
for this one?

2023-08-20 11:17 UTC, custodian commented
I will squash PR Code review before merge, `departure time check` also can be squashed. 
`prevent persons unboarding at stations without platforms` is another bug found with custom map, can be fixed here or as different PR

2023-08-20 11:46 UTC, HaSa1002 commented on src/Data/Scripts/Person.gd
> +			if global_transform.origin.distance_to(_destination_path[0]) < _destination_tolerance:
I think makes sense here

2023-08-20 12:01 UTC, HaSa1002 commented
Retested in Tutorial with red and grey. It doesn't leave the station anymore (I departed a bit late because I was waiting for all passengers to board)
![grafik](https://github.com/Libre-TrainSim/Libre-TrainSim/assets/14185889/bde2ceb1-3a07-4361-8017-528c8b957029)

Also pressing `O` to close the doors in the external view doesn't close the doors. You have to press at least twice to trigger the animation. (Not reproducible with the grey train)
![grafik](https://github.com/Libre-TrainSim/Libre-TrainSim/assets/14185889/60ad08dd-498f-4d05-be06-3b8bc5b76e47)

2023-08-22 20:52 UTC, HaSa1002 approved these changes
verified and retested with red ✅ 

All working fine. lgtm. Please make the history merge ready :>

2023-08-24 19:53 UTC, merged

2023-08-24 19:53 UTC, HaSa1002 commented
Thanks ❤️