"Test Track": load game directly from editors
Libre-TrainSim/Libre-TrainSim pull request #538
Opened 2023-09-10 12:39 UTC by Jomosoto

Resolves #187 

When pressing "Test Track" in scenario or track editor open the play menu with the scenario or route selector and then directly load the game, instead of exporting it and letting the user load it manually from the main menu.

<b> Note to reviewers: </b>
It happened a few times, that the game froze on "Starting Simulation...". I tried different conditions, but I couldn't reproduce it. It's likely that it's because of broken saves I produced while developing, but if it happens to you, too it may also be a bug in this PR.

2023-09-10 12:48 UTC, Jomosoto commented on src/Editor/Scripts/Editor.gd
> -var mod_path := ""
I removed `mod_path` and `content`, because I couldn't find any usage and it would be extra work to make the information available ingame when loading the editor (via "Back to Track Editor")

2023-09-19 12:38 UTC, HaSa1002 requested changes

2023-09-19 12:38 UTC, HaSa1002 commented on src/Data/Scripts/Singletons/Root.gd
> +var scenario_editor_test_track: bool = false
oooff. More state. Not happy about that

2023-09-19 12:38 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +		$CenterContainer/HBox/BackToTrackEditor.show()
hmm I see why. I guess it is ok, but these kinda variables tend to be misused later one. Also please don't hide QuitOS and QuitMenu

2023-09-19 12:38 UTC, HaSa1002 commented on src/Data/UI/pause.gd
> +	get_tree().change_scene_to(load("res://Editor/Modules/scenario_editor.tscn"))
Not necessarily your business but I'd prefer these variables getting set in the loading screen

2023-09-19 12:38 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +		hide()
I'd prefer a member variable here

2023-09-19 12:38 UTC, HaSa1002 commented on src/Data/UI/play_menu.gd
> +		hide()
member var here, too

2023-09-19 12:38 UTC, HaSa1002 commented on src/Editor/Scripts/Editor.gd
> -var mod_path := ""
I wonder why content wasn't used though. But if unused then it's fine

2023-09-19 12:38 UTC, HaSa1002 commented on src/Editor/Scripts/EditorHUD.gd
> +	if Input.is_action_just_pressed("pause", true):
nope, UI stuff is trigger on release 😅 Did you have an issue with event propagation?

2023-09-19 12:38 UTC, HaSa1002 commented on src/Editor/Scripts/pause_menu.gd
> +	if visible and (Input.is_action_just_pressed("pause", true) or Input.is_action_just_pressed("ui_cancel", true)):
see note above.

2023-09-19 12:38 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
>  		return
Is that still valid in 3.5? Anyway the popup should be rephrased to action then explanation.
```
Please use a Libre TrainSim build to test tracks. This is unfortunately a limitation when running the game inside the Godot Editor.
```

2023-09-19 12:38 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +BACK_TO_TRACK_EDITOR,Back to Track Editor,Zurück zum Strecken-Editor,,,,,,,Retour à l’éditeur de parcours
I'd vote for `Streckeneditor` instead of two words.
Also in English it should be `Back to the track editor`

2023-09-19 12:38 UTC, HaSa1002 commented on src/Translations/Ingame.csv
> +BACK_TO_SCENARIO_EDITOR,Back to Scenario Editor,Zurück zum Szenario-Editor,,,,,,,Retour à l’éditeur de scénario
same as above
`Szenarioeditor` and `Back to scenario editor`

2023-09-19 12:38 UTC, HaSa1002 commented
I didn't test your changes. This is just a code style review

2023-09-19 16:11 UTC, Jomosoto commented on src/Editor/Scripts/EditorHUD.gd
> +	if Input.is_action_just_pressed("pause", true):
There is a mix of on release and on press in the project. The play menu is on press, so when closing it with Esc the pause menu is opened on release. I'll change the play menu to on release then

2023-09-19 16:12 UTC, Jomosoto commented on src/Editor/Scripts/scenario_editor.gd
>  		return
Yes unfortunately

2023-09-23 19:51 UTC, HaSa1002 reviewed
Tested with a map. It worked but I got thrown into the main menu after I completed the scenario

2023-10-18 11:47 UTC, Jomosoto commented on src/Editor/Scripts/scenario_editor.gd
>  		return
Nevermind, it was something other that I broke by mistake. Works now :+1:

2023-10-19 16:07 UTC, HaSa1002 commented on src/Editor/Scripts/scenario_editor.gd
>  		return
great. Awaiting a force push then xD

2023-10-24 09:18 UTC, DasCapschen submitted a review, later dismissed
Looks alright to me.  I feel like it could be improved, but I don't know how much extra work that is. We still need to tidy up a lot of this code anyways. So you get my OK 👍🏻   

I'd like to get @HaSa1002's opinion before merging though.

2023-10-24 09:18 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +	print(current_station_node.length+GOODWILL_DISTANCE)
unnecessary print

2023-10-24 09:18 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +var game_start_context: int
I think we need to refactor this at some point, I feel like the player script does way too much... for now I like this solution though.

2023-10-24 09:18 UTC, DasCapschen commented on src/Data/Scripts/Player.gd
> +		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
I don't really like this being here. This seems more like something the Loading Screen should do...  
maybe  `LoadingScreen` could get a `load_scenario_editor` function. We could even do something like this:

```py
func _on_scenario_ended():
    LoadingScreen.load(game_start_context)

---
# LoadingScreen.gd
func load(game_start_context):
    match game_start_context:
        MainMenu: load_main_menu()
        TrackEditor: load_track_editor()
        ScenarioEditor: load_scenario_editor()
    # assuming this code still runs after load (🤔  ?)
    Root.reset_game_pause()
    Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
```

What do you think, @HaSa1002 ?

2023-10-24 09:18 UTC, DasCapschen commented on src/Editor/Scripts/scenario_editor.gd
> +	Root.scenario_editor = true
should these be reset to false in `func _exit_tree()` ?

2023-10-24 09:39 UTC, Jomosoto commented on src/Data/Scripts/Player.gd
> +	print(current_station_node.length+GOODWILL_DISTANCE)
Oh no, that was for debugging, I forgot to delete it 😅

2023-10-24 09:54 UTC, Jomosoto commented on src/Editor/Scripts/scenario_editor.gd
> +	Root.scenario_editor = true
Yes, they are. `_exit_tree` already existed.

2023-10-24 10:20 UTC, DasCapschen commented on src/Editor/Scripts/scenario_editor.gd
> +	Root.scenario_editor = true
Oh, alright then! Didn't see that. 👍🏻

2023-10-25 09:24 UTC, DasCapschen approved these changes

2023-10-27 23:07 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +var game_start_context: int
agreed. But later

2023-10-27 23:08 UTC, HaSa1002 commented on src/Data/Scripts/Player.gd
> +		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
agreed, but later. _exit_tree is at least called for sure. _load may be forgotten. But I'd like to see this snippet as a new PR

2023-10-27 23:17 UTC, HaSa1002 approved these changes
lgtm. I don't have the capacity to test again, so let's just merge and fixup if something breaks

In general I am not so super happy with the play menu/loading screen context but it's probably fine. I don't like when things behave (vastly) different based on a parameter. eg. when a parameter becomes a sole control flow driver changing the meaning of the code.

But we discussed all that. I just wanted to reemphasis my opinion here. I think it is ok for this hack here but we're close to a line :D

Enough talkin'

2023-10-27 23:17 UTC, merged

2023-10-27 23:18 UTC, HaSa1002 commented
Thank you so much ❤️ and my apologies for this lengthy review