remove speed limit indicator
Libre-TrainSim/Libre-TrainSim pull request #546
Opened 2023-10-24 13:45 UTC by DasCapschen

fixes #531 - if we actually do want to get rid of it :)  

(also makes the code a bit more legible, I hope)

2023-10-27 23:39 UTC, HaSa1002 requested changes
minor code style picking.
Not super sure about it's removal. Would like to keep the discussion open for a little longer first. (iirc some ppl can still raise their voice)

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	command_rotation_100percent = deg2rad(command_rotation_100percent)
isn't that constable or at least var initable?

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	speed_rotation_per_kmh = (speed_rotation_100kmh - speed_rotation_0kmh)/100.0
and that behind onready var?

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	command_rotation_per_percent = (command_rotation_100percent - command_rotation_0percent)
onready var, here too

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	$CommandPointer.rotation = move_toward($CommandPointer.rotation, command_target, delta*4.0)
```suggestion
	$CommandPointer.rotation = move_toward($CommandPointer.rotation, command_target, 4 * delta)
```
lerp is shorter xD

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
>  					speedLimit: float, engine: bool, reverser: int):
defuq is that 👀

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +export (float) var speed_rotation_100kmh: float
```suggestion
export var speed_rotation_100kmh: float
```

2023-10-27 23:39 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +export (float) var command_rotation_100percent: float
```suggestion
export var command_rotation_100percent: float
```

and all exports together pls

2023-10-30 11:02 UTC, DasCapschen commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	$CommandPointer.rotation = move_toward($CommandPointer.rotation, command_target, delta*4.0)
What, how is lerp shorter? You mean the word `lerp` is shorter than `move_toward` ? 😅 
Well yes, but they accomplish different things.  
with `lerp` we move a percentage of the way to our goal, this leads to a quick start and slow end (and theoretically we never reach our target at all!)  
with `move_toward` we move a fixed step toward our target, leading to a linear movement, and reach it.

2023-10-30 11:02 UTC, DasCapschen commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
>  					speedLimit: float, engine: bool, reverser: int):
always been like that 😂  but yeah, it's not pretty...

2023-10-30 11:56 UTC, DasCapschen commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	command_rotation_100percent = deg2rad(command_rotation_100percent)
Those are the export vars, I don't think that's possible.

2023-10-30 11:57 UTC, DasCapschen commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	speed_rotation_per_kmh = (speed_rotation_100kmh - speed_rotation_0kmh)/100.0
I mean, I could, but this is the _ready function, so it makes absolutely no difference.  
I'll put the `$SpeedPointer.rotation` in an onready var, because that's simple, but not so sure about the calculation

2023-11-07 14:48 UTC, HaSa1002 commented on src/Data/Screens/ScreenSpeedometer/screen_speedometer.gd
> +	$CommandPointer.rotation = move_toward($CommandPointer.rotation, command_target, delta*4.0)
ah nevermind then

2023-12-02 09:27 UTC, HaSa1002 approved these changes
lgtm. Sorry for the *very* late review. Didn't notice you pushed an update

2023-12-02 09:30 UTC, HaSa1002 commented
just squashed the two commits

2023-12-02 09:30 UTC, merged

2023-12-02 09:30 UTC, HaSa1002 commented
Thanks ❤️