WIP: Driving Backwards
Libre-TrainSim/Libre-TrainSim pull request #95
Opened 2021-08-21 23:13 UTC by DasCapschen

Implement driving backwards.  Solves #77.  
There are quite a lot of changes to core driving logic, so you probably want to review this properly.  
So far I have done some limited testing on the tutorial map, but it seemed to work fine there.

Known issues:   
- [ ] Going across a green light at the end of a station turns it red, going backwards over it again does *not* turn it green again. This probably requires resetting "nextStation" or so. I haven't yet looked into station code. Will do soon.

2021-08-22 09:00 UTC, Jean28518 commented
Thanks, I will review it!
That issue with the signal: I wouldn't reset any station variable because signals are not connected to stations in any way.

I would implement in this way: The train stores every overdriven signal in an array. If the train detects a signal in front, which is stored in this array, the train should turn that signal status to 1.

2021-08-22 09:33 UTC, DasCapschen commented
Okay, here is a short summary on how I implemented it:
- I store all signal names and route positions in arrays when baking the route. These arrays are already sorted, so `baked_route_signalNames[0]` will be the first signal the player passes.
- I keep track of the upcoming signal with an index `nextSignalIndex`
- in `check_signals` I check the player position on route against the signal position on route, and if passed, `nextSignalIndex += 1` (if driving backwards `nextSignalIndex -= 1`)
- I then find the last signal (with index < nextSignalIndex) of type "Signal" and call `giveSignalFree()`

Looks like `giveSignalFree()` is the problem, it only works if the signal is a block signal, but the signal at the end of the station is not. I guess I should just use `status = 1` right away.

Oh and I didn't yet check if you can drive past a station, then reverse into it and still service it. I think the game tells you "you drove past a station, go to the next one". So we would probably need to reset the station when reversing into it.

2021-08-22 09:37 UTC, Jean28518 commented
Very nice and clean code!

At newer contributions I try to respect the following code guidelines: https://www.gdquest.com/docs/guidelines/best-practices/godot-gdscript/
Would be great if you could do this too in the future :-) 

Could you please explain me the difference between distance and distanceOnRoute?

2021-08-22 09:53 UTC, DasCapschen commented
Oh, of course. I can do a bit of refactoring to follow the code guidelines, no problem. :)

Oh, `distanceOnRoute` is `distance`, I actually just renamed the variable, because there was already `distanceOnRail` and I got confused by what `distance` is, so I thought calling it `distanceOnRoute` makes it a bit more clear.

2021-08-22 10:10 UTC, Jean28518 commented
Okay, yeah, good Idea!

2021-08-22 10:32 UTC, Jean28518 reviewed
Code is okay in general :+1:

2021-08-22 11:03 UTC, DasCapschen commented
I tested it on Hainfurt now and also had the AI and Autopilot problems, that is fixed now :)
Station signals (`blockSignal = false`) will now also turn green.

I will look into signals being handled too early now :+1:

2021-08-22 11:21 UTC, DasCapschen commented
Signals should no longer trigger early. This was indeed due to wrong initial distanceOnRoute, if `forward = false` for startRail.

2021-08-22 19:26 UTC, Jean28518 commented
Why did you made the reverse state global? :)

2021-08-22 19:38 UTC, DasCapschen commented
Because it is accessed from multiple files, not just in Player.gd, and it's nicer to just write `ReverserState.FORWARD` than `player.ReverserState.FORWARD`, because really it's a constant, and not something intrinsic to the player.   
Remember this is just the Enum for the possible values, the current value of the player is `player.reverser` and not global :)

2021-09-02 14:10 UTC, DasCapschen commented
I have now refactored the Station logic, which makes it easier to read and understand, and I've also changed it a little.

The station now only counts as missed if the *whole* train went past the station. (`distance-distanceOnStationBeginning > stationLength` changed to `distance-distanceOnStationBeginning > stationLength + length`)

Just like when the end of train is not yet in the station, when the train drives past the station a bit, `whole_train_in_station` is false, and the player is told to reverse into the station and try again.

Also fixed a bug where people got out of the train when the player passed the station signal and opened the doors, but the train was not yet fully in the station. (people would walk in mid air)

2021-09-05 13:51 UTC, HaSa1002 requested changes
I only did brain compilation but looks good overall. Just some style stuff

2021-09-05 13:51 UTC, HaSa1002 commented on src/Resources/Basic/Screens/ScreenReverser/Reverser.gd
> +	$"VBoxContainer/Reverse".set_text(TranslationServer.translate("REVERSE"))
```suggestion
	$VBoxContainer/Forward.set_text(tr("FORWARD"))
	$VBoxContainer/Neutral.set_text(tr("NEUTRAL"))
	$VBoxContainer/Reverse.set_text(tr("REVERSE"))
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Modules/TrainInfo.tscn
> +[node name="dot" type="TextureRect" parent="ScrollContainer/VBoxContainer/Reverser"]
```suggestion
[node name="Dot" type="TextureRect" parent="ScrollContainer/VBoxContainer/Reverser"]
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Enums/ReverserState.gd
> +    REVERSE = -1
```suggestion
    FORWARD = 1,
    NEUTRAL = 0,
    BACKWARD = -1
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if reverser == ReverserState.REVERSE:
```suggestion
	if reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if reverser == ReverserState.REVERSE:
```suggestion
	if reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if not forward and (reverser == ReverserState.REVERSE):
```suggestion
	if not forward and (reverser == ReverserState.BACKWARD):
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if reverser == ReverserState.REVERSE:
```suggestion
	if reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if forward and (reverser == ReverserState.REVERSE):
```suggestion
	if forward and (reverser == ReverserState.BACKWARD):
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if reverser == ReverserState.REVERSE:
```suggestion
	if reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +		if reverser == ReverserState.REVERSE:
```suggestion
		if reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +var is_first_station = true # if this is the first station (where the player spawns)
```suggestion
var is_last_station := false # if this is the last station on the route
var is_first_station := true # if this is the first station (where the player spawns)
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +		if upcoming == null: return
```suggestion
		var upcoming = get_next_signal()
		if upcoming == null:
			return
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +func get_next_Signal():
```suggestion
func get_next_signal():
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +		if upcoming == null: return
```suggestion
		var upcoming = get_next_station()
		if upcoming == null:
			return
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +func get_next_Station():
```suggestion
func get_next_station():
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	if (currentStationName != "" and speed == 0 and not isInStation and distance_on_route-distanceOnStationBeginning>=length):
```suggestion
	if (currentStationName != "" and speed == 0 and not isInStation and distance_on_route - distanceOnStationBeginning >= length):
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	signal_to_free = signal_instance
I suspect we may leak memory here, so just in case:
```suggestion
	assert(signal_to_free == null)
	signal_to_free = signal_instance
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +			else: reverser = ReverserState.REVERSE
```suggestion
		ReverserState.NEUTRAL:
			jAudioManager.play_game_sound("res://Resources/Basic/Sounds/click.ogg")
			if change > 0:
				reverser = ReverserState.FORWARD
			else: 
				reverser = ReverserState.BACKWARD
```
or inline:
```suggestion
		ReverserState.NEUTRAL:
			jAudioManager.play_game_sound("res://Resources/Basic/Sounds/click.ogg")
			reverser = ReverserState.FORWARD if change > 0 else ReverserState.BACKWARD
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +				reverser = ReverserState.NEUTRAL
```suggestion
		ReverserState.BACKWARD:
			if change > 0:
				reverser = ReverserState.NEUTRAL
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
> +var attachedSignals = []
Why not a dictionary?

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/TrainInfo.gd
> +		$"ScrollContainer/VBoxContainer/Reverser/dot".texture = green
```suggestion
		$ScrollContainer/VBoxContainer/Reverser/Dot.texture = red
	else:
		$ScrollContainer/VBoxContainer/Reverser/Dot.texture = green
```
Why do we set the texture and not just use `self_modulate` or `modulate`?

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Wagon.gd
> +		if player.reverser == ReverserState.REVERSE:
```suggestion
		if player.reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Wagon.gd
> +	if not forward and (player.reverser == ReverserState.REVERSE):
```suggestion
	if not forward and (player.reverser == ReverserState.BACKWARD):
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Wagon.gd
> +	if player.reverser == ReverserState.REVERSE:
```suggestion
	if player.reverser == ReverserState.BACKWARD:
```

2021-09-05 13:51 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Wagon.gd
> +	if forward and (player.reverser == ReverserState.REVERSE):
```suggestion
	if forward and (player.reverser == ReverserState.BACKWARD):
```

2021-09-05 15:07 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/TrainInfo.gd
> +		$"ScrollContainer/VBoxContainer/Reverser/dot".texture = green
Because the texture is not white. iirc, it has a white outline with the color in the middle. We cannot modulate that.

2021-09-05 15:11 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	signal_to_free = signal_instance
I don't think this assertion is necessary. We are not freeing the signal as in deleting it, we are only setting it to "green".
So there is no memory which is allocated or can be leaked. We are only remembering a pointer to a node basically, and then overriding it.

2021-09-05 15:13 UTC, DasCapschen commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
> +var attachedSignals = []
Because I want to sort them, so they need to be in some definite order. A dictionary is not ordered in any way, and cannot be accessed over indices, only over keys. This is not useful in this case (check where attachedSignals is used in Player.gd)

2021-09-05 15:14 UTC, DasCapschen commented
@HaSa1002 
I've merged some of your changes, but why all the changes of "Reverse" to "Backward"?

2021-09-05 15:16 UTC, HaSa1002 commented
I believe your rather drive backwards than driving reverse

2021-09-05 15:18 UTC, DasCapschen commented
Well, in a car the "Rückwärtsgang" is the "Reverse gear", so I'd say you are driving "in reverse", rather than "backwards".
It doesn't really make much of a difference, I think.

2021-09-05 15:19 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Player.gd
> +	signal_to_free = signal_instance
oh my bad. I am still desperate to find these memory leaks ^^

2021-09-05 15:19 UTC, HaSa1002 commented on src/addons/Libre_Train_Sim_Editor/Data/Scripts/Rail.gd
> +var attachedSignals = []
good point

2021-09-05 15:22 UTC, HaSa1002 commented
Then it is personal preference, I guess. I have no strong opinion about that as I am not a native speaker. Both is understandable IMO. Func fact: There is a comment in your code under a `.REVERSE` talking about backwards driving.

2021-09-05 15:45 UTC, HaSa1002 commented
I forgot to ask you to rename your files to `snake_case` per https://docs.godotengine.org/en/stable/getting_started/workflow/project_setup/project_organization.html#style-guide

2021-09-05 21:37 UTC, DasCapschen commented
Will do :+1:

2021-09-06 21:57 UTC, HaSa1002 commented
* The go back message does not include the controls
* No hint is shown if you throttle up and the reverser is neutral
* In the middle on control board the directions are all displayed, but don't appear to have a function
* `R` and `F` feel inverted, because R is above F but reverses
* Controller mappings are missing (maybe, use DPAD, but we run out of buttons on controllers, so we need to find a better solution anyway)

2021-09-06 21:59 UTC, HaSa1002 commented
The mobile version needs buttons for the reverser as well

2021-09-06 22:10 UTC, DasCapschen commented
>     * The go back message does not include the controls
>     * No hint is shown if you throttle up and the reverser is neutral
Will fix these, no problem :)

>     * Controller mappings are missing (maybe, use DPAD, but we run out of buttons on controllers, so we need to find a better solution anyway)
There will be #108 at some point, which might help reduce controller mappings.
I will check what bindings TSW2 and TS2021 use.

> The mobile version needs buttons for the reverser as well
This will need UI work. Don't want to overload a tiny mobile screen with more and more controls.
I think eventually the mobile will *need* to be a subset of the PC version (like forcing simple mode)

>     * In the middle on control board the directions are all displayed, but don't appear to have a function
There are the 3 possible directions and a knob next to it (might be hard to see, the cabin lighting is awfully dark) that points to the selected direction. This will be useful for #108.

>     * `R` and `F` feel inverted, because R is above F but reverses
This is a but of a weird one. Yes, R being above F, you'd think that *R* goes forward and *F* goes backwards, but also **R**everse and **F**orward. So I'm not sure which is less confusing 😅

2021-09-06 22:13 UTC, HaSa1002 commented
> This will need UI work. Don't want to overload a tiny mobile screen with more and more controls.
I think eventually the mobile will need to be a subset of the PC version (like forcing simple mode)

I think #108 will fix that, but not the controller stuff, as you don't want to use a cursor through a controller. I am thinking about a radial or quick slot menu.

2021-09-06 22:31 UTC, DasCapschen commented
I think #108 will work fine on controllers. I was thinking of doing it like TSW2 (they have an xbox version on which this works fine):

you don't enable the mouse cursor and move that around, rather you have a little "crosshair" in the center of your screen and whatever control is below that gets selected. When you press the interact button, the view gets locked and moving the view stick / mouse around then moves the control.

On a mobile, of course you could do all that with your finger.

I am not opposed at all to a radial menu though, that is actually a really good idea! Even for PC. 
Although it should go into it's own issue / PR :)

2021-09-09 06:44 UTC, DasCapschen commented
About the mobile HUD, I've just had an idea:
We have the up and down button, which are used to control the combined brake / acceleration lever. 
What if we also make them control the reverser? Like this:
- player is stopped (speed == 0)
- player clicks arrow up -> Reverser changes to FORWARD -> click / hold arrow up more -> accelerate
- player clicks arrow down -> Reverser changes to REVERSE -> click / hold arrow down more -> accelerate

And then while driving: 
- if FORWARD: arrow down -> brake
- if REVERSE: arrow up -> brake

Basically making the arrows choose the direction you want to go in.

2021-09-16 06:33 UTC, DasCapschen commented
I would say this merge request is done. 
Feel free to test it extensively before you merge it. :)

2021-09-16 08:49 UTC, HaSa1002 approved these changes
You can't close the doors via controller anymore, but not a blocker since we need to rework controller input anyhow.
LGTM.

2021-09-16 08:53 UTC, DasCapschen commented
You should still be able to close the doors. I changed to behaviour so that when you press "doors right" and the doors are already open, they will then close.
But I thought about reworking how the doors work anyways :smile:

2021-09-16 08:55 UTC, HaSa1002 commented
A good to know. But yeah not a problem really, as it was added in this dev version

2021-09-21 15:24 UTC, merged